import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { chmod, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import test from "node:test";
import { NodeStagedPromotionGit } from "../../../src/adapters/staged-git.js";
import type { GitTransportCommandRunner } from "../../../src/adapters/git-transport.js";
import { sanitizedGitEnvironment } from "../../../src/adapters/git-transport.js";
import { createPayloadPlan } from "../../../src/promotion/payload.js";

const execute=promisify(execFile),git="/usr/bin/git",fakeUrl="https://github.com/acme/destination.git";
async function run(path:string,args:string[]):Promise<string>{return (await execute(git,["-C",path,...args],{encoding:"utf8",env:sanitizedGitEnvironment()})).stdout.trim();}
async function fixture(){const root=await mkdtemp(join(tmpdir(),"shipyard-staged-payload-")),destination=join(root,"destination.git"),development=join(root,"development");await execute(git,["init","--bare",destination],{encoding:"utf8",env:sanitizedGitEnvironment()});await execute(git,["clone",destination,development],{encoding:"utf8",env:sanitizedGitEnvironment()});await run(development,["config","user.name","Test"]);await run(development,["config","user.email","test@example.test"]);await writeFile(join(development,"old.txt"),"remove me\n");await writeFile(join(development,"company.yml"),"destination-owned\n");await run(development,["add","."]);await run(development,["commit","-m","destination baseline"]);await run(development,["branch","-M","main"]);await run(development,["push","origin","main"]);const baseline=await run(development,["rev-parse","HEAD"]);await run(development,["remote","rename","origin","development"]);await run(development,["checkout","-b","shipyard/delivery"]);await writeFile(join(development,"run.sh"),"#!/bin/sh\necho first\n");await chmod(join(development,"run.sh"),0o755);await symlink("run.sh",join(development,"current"));await writeFile(join(development,"asset.bin"),Buffer.from([0,255,1,2,3]));await writeFile(join(development,"replacement-�.txt"),"valid UTF-8\n");await execute("/bin/mkdir",["-p",join(development,".shipyard")]);await writeFile(join(development,".shipyard","evidence.json"),"private\n");await rm(join(development,"old.txt"));await run(development,["add","-A"]);await run(development,["commit","-m","reviewed product"]);return {root,destination,development,baseline,source:await run(development,["rev-parse","HEAD"])};}
function redirectedRunner(destination:string):GitTransportCommandRunner{return {run:async command=>{const [dashC,path,...rest]=command.argv,fileUrl=`file://${destination}`,argv=dashC==="-C"&&path?[dashC,path,"-c",`url.${fileUrl}.insteadOf=${fakeUrl}`,...rest]:[...command.argv];try{const result=await execute(command.executable,argv,{encoding:"utf8",env:sanitizedGitEnvironment(command.env),timeout:command.timeoutMs,maxBuffer:command.maxOutputBytes,killSignal:"SIGKILL"});return {exitCode:0,stdout:result.stdout,stderr:result.stderr};}catch(error){const value=error as {code?:unknown;stdout?:string;stderr?:string};return {exitCode:typeof value.code==="number"?value.code:1,stdout:value.stdout??"",stderr:value.stderr??"failed"};}}};}
const credentials={resolve:async()=>({token:"test-token-never-persist",verifiedActorLogin:"actor"})};
function plan(observation:Awaited<ReturnType<NodeStagedPromotionGit["stage"]>>["observation"],parentEntries=observation.destinationMainEntries,parentSha=observation.destinationMainSha){const source=new Map(observation.sourceEntries.map(entry=>[entry.path,entry.path.startsWith(".shipyard/")?"development-record":entry.path==="company.yml"?"destination-only":"product"] as const)),destination=new Map(parentEntries.map(entry=>[entry.path,entry.path==="company.yml"?"destination-only":"product"] as const));return createPayloadPlan({sourceSha:observation.sourceSha,parentDestinationSha:parentSha,sourceEntries:observation.sourceEntries,destinationEntries:parentEntries,classification:{source,destination}});}

test("Git-native staged promotion preserves cargo, excludes records, and adopts exact interrupted initial/revision pushes",async()=>{const f=await fixture();try{const adapter=new NodeStagedPromotionGit(credentials,redirectedRunner(f.destination));const request={repositoryPath:f.development,actorLogin:"actor",developmentBranch:"shipyard/delivery",expectedSourceSha:f.source,destination:{owner:"acme",name:"destination",remote:{name:"destination",url:fakeUrl},defaultBranch:"main"},destinationBranch:"shipyard/delivery"} as const;
  const initial=await adapter.stage(request),initialPlan=plan(initial.observation),first=await initial.publish(initialPlan,{deliveryId:"delivery",revision:1,destinationBranch:request.destinationBranch});await initial.release();assert.equal(first.destinationParentSha,f.baseline);assert.equal(await execute(git,["--git-dir",f.destination,"rev-parse","refs/heads/shipyard/delivery^"],{encoding:"utf8"}).then(value=>value.stdout.trim()),f.baseline);const names=(await execute(git,["--git-dir",f.destination,"ls-tree","-r","-z","--name-only",first.destinationCommitSha],{encoding:"utf8"})).stdout.split("\0").filter(Boolean);assert.deepEqual(names,["asset.bin","company.yml","current","replacement-�.txt","run.sh"]);assert.equal(await execute(git,["--git-dir",f.destination,"ls-tree",first.destinationCommitSha,"run.sh"],{encoding:"utf8"}).then(value=>value.stdout.slice(0,6)),"100755");
  const retried=await adapter.stage(request),adopted=await retried.publish(plan(retried.observation),{deliveryId:"delivery",revision:1,destinationBranch:request.destinationBranch});await retried.release();assert.equal(adopted.destinationCommitSha,first.destinationCommitSha);
  await writeFile(join(f.development,"run.sh"),"#!/bin/sh\necho revised\n");await chmod(join(f.development,"run.sh"),0o644);await writeFile(join(f.development,"new.txt"),"new\n");await run(f.development,["add","-A"]);await run(f.development,["commit","-m","reviewed revision"]);const revised=await run(f.development,["rev-parse","HEAD"]),revisionRequest={...request,expectedSourceSha:revised,expectedPreviousSourceSha:f.source,expectedDestinationParentSha:first.destinationCommitSha},revision=await adapter.stage(revisionRequest),revisionPlan=createPayloadPlan({sourceSha:revised,parentDestinationSha:first.destinationCommitSha,sourceEntries:revision.observation.sourceEntries,destinationEntries:revision.observation.recordedDestinationParentEntries!,classification:{source:new Map(revision.observation.sourceEntries.map(entry=>[entry.path,entry.path.startsWith(".shipyard/")?"development-record":entry.path==="company.yml"?"destination-only":"product"] as const)),destination:new Map(revision.observation.recordedDestinationParentEntries!.map(entry=>[entry.path,entry.path==="company.yml"?"destination-only":"product"] as const))}}),second=await revision.publish(revisionPlan,{deliveryId:"delivery",revision:2,destinationBranch:request.destinationBranch,expectedRemoteHead:first.destinationCommitSha});await revision.release();assert.equal(await execute(git,["--git-dir",f.destination,"rev-parse",`${second.destinationCommitSha}^`],{encoding:"utf8"}).then(value=>value.stdout.trim()),first.destinationCommitSha);assert.equal(await execute(git,["--git-dir",f.destination,"ls-tree",second.destinationCommitSha,"run.sh"],{encoding:"utf8"}).then(value=>value.stdout.slice(0,6)),"100644");
  const revisionRetry=await adapter.stage(revisionRequest),adoptedRevision=await revisionRetry.publish(createPayloadPlan({sourceSha:revised,parentDestinationSha:first.destinationCommitSha,sourceEntries:revisionRetry.observation.sourceEntries,destinationEntries:revisionRetry.observation.recordedDestinationParentEntries!,classification:{source:new Map(revisionRetry.observation.sourceEntries.map(entry=>[entry.path,entry.path.startsWith(".shipyard/")?"development-record":entry.path==="company.yml"?"destination-only":"product"] as const)),destination:new Map(revisionRetry.observation.recordedDestinationParentEntries!.map(entry=>[entry.path,entry.path==="company.yml"?"destination-only":"product"] as const))}}),{deliveryId:"delivery",revision:2,destinationBranch:request.destinationBranch,expectedRemoteHead:first.destinationCommitSha});await revisionRetry.release();assert.equal(adoptedRevision.destinationCommitSha,second.destinationCommitSha);assert.equal(await readFile(join(f.development,".shipyard","evidence.json"),"utf8"),"private\n");
}finally{await rm(f.root,{recursive:true,force:true});}});

test("staging rejects any writable destination remote variant retained by the development clone",async()=>{for(const remoteUrl of ["https://github.com/acme/destination","https://github.com:443/ACME/DESTINATION.git","git@github.com:acme/destination.git","ssh://git@github.com/acme/destination.git","ssh://git@github.com:22/ACME/DESTINATION.git"]){const f=await fixture();try{await run(f.development,["remote","add","destination",remoteUrl]);const adapter=new NodeStagedPromotionGit(credentials,redirectedRunner(f.destination));await assert.rejects(adapter.stage({repositoryPath:f.development,actorLogin:"actor",developmentBranch:"shipyard/delivery",expectedSourceSha:f.source,destination:{owner:"acme",name:"destination",remote:{name:"destination",url:fakeUrl},defaultBranch:"main"},destinationBranch:"shipyard/delivery"}),/writable destination remote/i);}finally{await rm(f.root,{recursive:true,force:true});}}});

test("post-merge verification pins the original destination baseline instead of requiring merged main to precede development",async()=>{const f=await fixture();try{const adapter=new NodeStagedPromotionGit(credentials,redirectedRunner(f.destination)),request={repositoryPath:f.development,actorLogin:"actor",developmentBranch:"shipyard/delivery",expectedSourceSha:f.source,destination:{owner:"acme",name:"destination",remote:{name:"destination",url:fakeUrl},defaultBranch:"main"},destinationBranch:"shipyard/delivery"} as const,initial=await adapter.stage(request),published=await initial.publish(plan(initial.observation),{deliveryId:"delivery",revision:1,destinationBranch:request.destinationBranch});await initial.release();const mergeTree=(await execute(git,["--git-dir",f.destination,"rev-parse",`${published.destinationCommitSha}^{tree}`],{encoding:"utf8"})).stdout.trim(),identity={...sanitizedGitEnvironment(),GIT_AUTHOR_NAME:"Team",GIT_AUTHOR_EMAIL:"team@example.test",GIT_COMMITTER_NAME:"Team",GIT_COMMITTER_EMAIL:"team@example.test"},squash=(await execute(git,["--git-dir",f.destination,"commit-tree",mergeTree,"-p",f.baseline,"-m","human squash merge"],{encoding:"utf8",env:identity})).stdout.trim();await execute(git,["--git-dir",f.destination,"update-ref","refs/heads/main",squash,f.baseline],{encoding:"utf8"});await assert.rejects(adapter.stage({...request,expectedDestinationParentSha:f.baseline}),/required destination baseline/i);const verified=await adapter.stage({...request,expectedDestinationParentSha:f.baseline,sourceBaselineSha:f.baseline});assert.equal(verified.observation.destinationMainSha,squash);assert.equal(verified.observation.destinationBranchHeadSha,published.destinationCommitSha);await verified.release();}finally{await rm(f.root,{recursive:true,force:true});}});
