import assert from "node:assert/strict";
import test from "node:test";
import { promotionManifestContents, validatePromotionManifest, validatePromotionJournal, appendJournalEntry } from "../../src/promotion/schema.js";

const sha=(value:string)=>value.repeat(40),digest=(value:string)=>value.repeat(64),repo={owner:"acme",name:"repo",remote:{name:"origin",url:"https://github.com/acme/repo.git"},defaultBranch:"main"},evidence={productSha:sha("a"),ledgerSha:sha("b"),manifestDigest:digest("a"),acceptanceDigest:digest("b"),reviewId:"r-1",reviewRequestDigest:digest("c"),reviewResultDigest:digest("d"),reviewedLedgerSha:sha("c"),reviewerBundleDigest:digest("e"),evaluatedAt:"2026-08-04T00:00:00.000Z"},mapping={revision:1,developmentSha:sha("a"),destinationParentSha:sha("b"),destinationCommitSha:sha("c"),destinationTreeSha:sha("d"),projectedProductTreeSha:sha("d"),policyDigest:digest("f"),projectionDigest:digest("0"),evidence,promotedAt:"2026-08-04T00:00:00.000Z"},manifest={schemaVersion:1 as const,deliveryId:"d",actorLogin:"actor",development:{repository:{...repo,name:"dev"},branch:"shipyard/d"},destination:{repository:{...repo,name:"dest"},branch:"shipyard/d",baselineSha:sha("b")},mappings:[mapping],phase:"promoting" as const};
test("promotion manifest round-trips canonical mappings",()=>{const parsed=validatePromotionManifest(JSON.parse(promotionManifestContents(manifest)));assert.deepEqual(parsed,manifest);assert.ok(Object.isFrozen(parsed)&&Object.isFrozen(parsed.mappings));});
test("manifest rejects duplicate/reordered/non-descendant mappings and forged tree equivalence",()=>{assert.throws(()=>validatePromotionManifest({...manifest,mappings:[mapping,{...mapping,revision:2,developmentSha:sha("e"),destinationCommitSha:sha("f"),destinationParentSha:sha("9")}]}));assert.throws(()=>validatePromotionManifest({...manifest,mappings:[{...mapping,destinationTreeSha:sha("e")}]}));assert.throws(()=>validatePromotionManifest({...manifest,extra:"authority"}));});
test("manifest rejects mixed Git object formats",()=>{assert.throws(()=>validatePromotionManifest({...manifest,destination:{...manifest.destination,baselineSha:"a".repeat(64)}}));assert.throws(()=>validatePromotionManifest({...manifest,mappings:[{...mapping,evidence:{...mapping.evidence,ledgerSha:"b".repeat(64)}}]}));});
test("journal is append-only by idempotency key",()=>{const empty=validatePromotionJournal({schemaVersion:1,deliveryId:"d",entries:[]}),entry={step:"destination-branch-published" as const,idempotencyKey:"branch:c",observedSha:sha("c"),completedAt:"2026-08-04T00:00:00.000Z"},once=appendJournalEntry(empty,entry),twice=appendJournalEntry(once,{...entry,completedAt:"2099-01-01T00:00:00.000Z"});assert.equal(once.entries.length,1);assert.equal(twice.entries.length,1);assert.equal(twice.entries[0]!.completedAt,entry.completedAt);});
