import { createHash } from "node:crypto";
import type { LedgerStore } from "../ledger/types.js";
import { validLedgerPath } from "../ledger/transaction.js";
import { createLaneRecord } from "./classification.js";
import type { LaneRecord } from "./types.js";

/** Deliberately the only authority-shaped data which is serialised in a planning lane. */
export type PlanningPin = Readonly<{ productSha: string; historicalBaseLedgerSha: string; profileName: string; profileFingerprint: string; actorLogin: "visualjc"; topologyDigest: string; commonDirectoryDigest: string; objectFormat: "sha1" | "sha256" }>;
export type PlanningCheckpoint = Readonly<{ schemaVersion: 1; record: LaneRecord; pin: PlanningPin }>;
export type PlanningArtifact = Readonly<{ step: string; path: string; sha256: string }>;
export type ProviderCheckpoint = Readonly<{ schemaVersion: 1; kind: "planning-provider"; recordId: string; baseDigest: string; provider: "codex"; phase: "diagnosed" | "planned"; resumeCheckpoint: string; artifacts: readonly PlanningArtifact[] }>;
export type ReviewIntent = Readonly<{ schemaVersion: 1; kind: "review-intent"; recordId: string; baseDigest: string; target: Readonly<{ owner: string; name: string; number: number; url: string; baseBranch: string; headSha: string }> }>;

const sha = (value: unknown, format?: "sha1" | "sha256"): value is string => typeof value === "string" && (format === "sha1" ? /^[a-f0-9]{40}$/.test(value) : format === "sha256" ? /^[a-f0-9]{64}$/.test(value) : (/^[a-f0-9]{40}$/.test(value) || /^[a-f0-9]{64}$/.test(value)));
const digest = (contents: string) => createHash("sha256").update(contents, "utf8").digest("hex");
const plain = (value: unknown, seen = new Set<object>(), depth = 0): unknown => {
  if (depth > 16) throw new Error("Planning document is invalid."); if (value === null || ["string", "number", "boolean"].includes(typeof value)) return value;
  if (!value || typeof value !== "object" || seen.has(value) || Object.getPrototypeOf(value) !== Object.prototype && !Array.isArray(value)) throw new Error("Planning document is invalid.");
  seen.add(value);
  const descriptors = Object.getOwnPropertyDescriptors(value);
  if (Reflect.ownKeys(value).some(key => typeof key !== "string") || Object.entries(descriptors).some(([key, item]) => !("value" in item) || (key !== "length" && !item.enumerable))) throw new Error("Planning document is invalid.");
  const length = descriptors.length?.value; if (Array.isArray(value) && (!Number.isSafeInteger(length) || (length as number) > 64 || Object.keys(descriptors).some(key => key !== "length" && !/^(0|[1-9][0-9]*)$/.test(key)))) throw new Error("Planning document is invalid."); const result = Array.isArray(value) ? Array.from({ length: length as number }, (_, index) => { const field = descriptors[String(index)]; if (!field || !("value" in field)) throw new Error("Planning document is invalid."); return plain(field.value, seen, depth + 1); }) : Object.fromEntries(Object.keys(descriptors).sort().map(key => [key, plain(descriptors[key]!.value, seen, depth + 1)]));
  seen.delete(value); return result;
};
const stable = (value: unknown): string => JSON.stringify(plain(value));
function exact(value: Record<string, unknown>, keys: readonly string[]): void { if (Object.keys(value).length !== keys.length || Object.keys(value).some(key => !keys.includes(key))) throw new Error("Planning document is invalid."); }
function text(value: unknown, pattern: RegExp, limit: number): string { if (typeof value !== "string" || value.length === 0 || value.length > limit || !pattern.test(value)) throw new Error("Planning document is invalid."); return value; }
function freeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as Record<string, unknown>)) freeze(child); Object.freeze(value); } return value; }
function detached<T>(value: T): T { return freeze(structuredClone(value)); }

export function planningRecordPath(recordId: string): string { text(recordId, /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/, 128); if (recordId.includes("..")) throw new Error("Planning record ID is invalid."); return `planning/${recordId}.json`; }
function providerRecordPath(recordId: string): string { return `planning/${recordId}/provider.json`; }
function reviewRecordPath(recordId: string): string { return `planning/${recordId}/review-intent.json`; }
export function topologyDigest(value: unknown): string { return digest(stable(value)); }

/** The base document is immutable. Provider and review documents can only point at its digest. */
export function canonicalPlanningCheckpoint(raw: PlanningCheckpoint): string {
  const value = plain(raw) as Record<string, unknown>; exact(value, ["pin", "record", "schemaVersion"]);
  if (value.schemaVersion !== 1) throw new Error("Planning checkpoint is invalid.");
  const rawRecord = plain(value.record) as Record<string, unknown>; exact(rawRecord, ["blockers", "decision", "dependencyStates", "nextSafeAction", "phase", "recordId", "schemaVersion"]);
  const record = createLaneRecord({ recordId: rawRecord.recordId, decision: rawRecord.decision, dependencyStates: rawRecord.dependencyStates, blockers: rawRecord.blockers });
  if (rawRecord.schemaVersion !== 1 || rawRecord.phase !== record.phase || rawRecord.nextSafeAction !== record.nextSafeAction) throw new Error("Planning checkpoint is invalid.");
  const pin = plain(value.pin) as Record<string, unknown>; exact(pin, ["actorLogin", "commonDirectoryDigest", "historicalBaseLedgerSha", "objectFormat", "productSha", "profileFingerprint", "profileName", "topologyDigest"]);
  if ((pin.objectFormat !== "sha1" && pin.objectFormat !== "sha256") || !sha(pin.productSha, pin.objectFormat) || !sha(pin.historicalBaseLedgerSha, pin.objectFormat) || !text(pin.profileName, /^[A-Za-z0-9._-]{1,128}$/, 128) || typeof pin.profileFingerprint !== "string" || !/^[a-f0-9]{64}$/.test(pin.profileFingerprint) || typeof pin.topologyDigest !== "string" || !/^[a-f0-9]{64}$/.test(pin.topologyDigest) || typeof pin.commonDirectoryDigest !== "string" || !/^[a-f0-9]{64}$/.test(pin.commonDirectoryDigest) || pin.actorLogin !== "visualjc") throw new Error("Planning checkpoint is invalid.");
  return stable({ schemaVersion: 1, record, pin });
}
export function checkpointDigest(checkpoint: PlanningCheckpoint): string { return digest(canonicalPlanningCheckpoint(checkpoint)); }
export function canonicalProviderCheckpoint(raw: ProviderCheckpoint, base?: PlanningCheckpoint): string {
  const value = plain(raw) as Record<string, unknown>; exact(value, ["artifacts", "baseDigest", "kind", "phase", "provider", "recordId", "resumeCheckpoint", "schemaVersion"]);
  if (value.schemaVersion !== 1 || value.kind !== "planning-provider" || value.provider !== "codex" || !text(value.recordId, /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/, 128) || typeof value.baseDigest !== "string" || !/^[a-f0-9]{64}$/.test(value.baseDigest) || typeof value.phase !== "string" || !["diagnosed", "planned"].includes(value.phase) || !text(value.resumeCheckpoint, /^[A-Za-z0-9._-]{1,128}$/, 128) || !Array.isArray(value.artifacts) || value.artifacts.length > 16) throw new Error("Planning provider checkpoint is invalid.");
  const recordId = text(value.recordId, /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/, 128); const paths = new Set<string>(); const artifacts = value.artifacts.map(item => { const row = plain(item) as Record<string, unknown>; exact(row, ["path", "sha256", "step"]); const path = safeArtifactPath(row.path, recordId); if (paths.has(path)) throw new Error("Planning provider checkpoint is invalid."); paths.add(path); return { step: text(row.step, /^[a-z][a-z0-9-]{0,63}$/, 64), path, sha256: text(row.sha256, /^[a-f0-9]{64}$/, 64) }; });
  const expected = base ? providerSteps(base) : value.phase === "diagnosed" ? ["diagnosing-bugs"] : undefined;
  if (!expected || value.phase !== (base?.record.decision.lane === "bug" ? "diagnosed" : "planned") || artifacts.length !== expected.length || artifacts.some((item, index) => item.step !== expected[index])) throw new Error("Planning provider checkpoint is invalid.");
  return stable({ schemaVersion: 1, kind: "planning-provider", recordId: value.recordId, baseDigest: value.baseDigest, provider: "codex", phase: value.phase, resumeCheckpoint: value.resumeCheckpoint, artifacts });
}
export function providerSteps(base: PlanningCheckpoint): readonly string[] { const decision = base.record.decision; if (decision.disposition !== "ready") throw new Error("Planning provider checkpoint is invalid."); if (decision.lane === "large") return ["wayfinder", "ccpm-prd", "ccpm-vertical-tasks"]; if (decision.lane === "small") return ["grill-with-docs", "to-spec"]; if (decision.lane === "bug") return ["diagnosing-bugs"]; throw new Error("Planning provider checkpoint is invalid."); }
export function canonicalReviewIntent(raw: ReviewIntent, base?: PlanningCheckpoint): string {
  const value = plain(raw) as Record<string, unknown>; exact(value, ["baseDigest", "kind", "recordId", "schemaVersion", "target"]);
  const target = plain(value.target) as Record<string, unknown>; exact(target, ["baseBranch", "headSha", "name", "number", "owner", "url"]);
  if (value.schemaVersion !== 1 || value.kind !== "review-intent" || !text(value.recordId, /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/, 128) || typeof value.baseDigest !== "string" || !/^[a-f0-9]{64}$/.test(value.baseDigest) || !text(target.owner, /^[A-Za-z0-9.-]{1,100}$/, 100) || !text(target.name, /^[A-Za-z0-9._-]{1,100}$/, 100) || !Number.isSafeInteger(target.number) || (target.number as number) < 1 || !text(target.baseBranch, /^[A-Za-z0-9._/-]{1,255}$/, 255) || !sha(target.headSha, base?.pin.objectFormat) || target.url !== `https://github.com/${target.owner}/${target.name}/pull/${target.number}`) throw new Error("Review intent is invalid.");
  return stable({ schemaVersion: 1, kind: "review-intent", recordId: value.recordId, baseDigest: value.baseDigest, target });
}
function safeArtifactPath(value: unknown, recordId: string): string { const path = text(value, /^[A-Za-z0-9._/-]{1,512}$/, 512); const prefix = `planning/${recordId}/artifacts/`; if (!path.startsWith(prefix) || path.includes("..") || path.includes("//") || path.endsWith("/") || /(^|\/)\.(\/|$)/.test(path) || /(^|\/)(?:product|provider|ledger|metadata)(?:\/|$)/.test(path)) throw new Error("Planning artifact path is invalid."); return path; }

export class PlanningLedger {
  constructor(private readonly store: LedgerStore) {}
  async append(checkpoint: PlanningCheckpoint): Promise<Readonly<{ checkpoint: PlanningCheckpoint; ledgerHead: string | undefined }>> {
    const path = planningRecordPath(checkpoint.record.recordId), contents = canonicalPlanningCheckpoint(checkpoint); if (!validLedgerPath(path)) throw new Error("Planning record path is invalid.");
    const snapshot = await this.store.snapshot([path]);
    // A write may have committed before its caller lost the response: exact bytes are safely adopted at any later head.
    if (snapshot.records[path] !== undefined) { if (snapshot.records[path] !== contents) throw new Error("Planning record already exists with different contents."); return freeze({ checkpoint: detached(checkpoint), ledgerHead: snapshot.head }); }
    if (snapshot.head !== checkpoint.pin.historicalBaseLedgerSha) throw new Error("Planning ledger pin is stale.");
    const ledgerHead = await this.store.transact({ expectedHead: snapshot.head, writes: [{ path, contents }], message: `append planning ${checkpoint.record.recordId}` }); return freeze({ checkpoint: detached(checkpoint), ledgerHead });
  }
  async appendProvider(base: PlanningCheckpoint, provider: ProviderCheckpoint, expectedHead: string | undefined): Promise<string> { const path = providerRecordPath(base.record.recordId), basePath = planningRecordPath(base.record.recordId), baseContents = canonicalPlanningCheckpoint(base), contents = canonicalProviderCheckpoint(provider, base); if (!validLedgerPath(path) || provider.recordId !== base.record.recordId || provider.baseDigest !== checkpointDigest(base)) throw new Error("Planning provider is not bound to its base record."); const snapshot = await this.store.snapshot([basePath, path]); if (snapshot.records[basePath] !== baseContents) throw new Error("Planning provider base record is missing or changed."); if (snapshot.records[path] !== undefined) { if (snapshot.records[path] !== contents) throw new Error("Provider checkpoint already exists with different contents."); return snapshot.head ?? ""; } if (snapshot.head !== expectedHead) throw new Error("Planning ledger advanced before provider checkpoint."); return this.store.transact({ expectedHead: snapshot.head, writes: [{ path, contents }], message: `append planning provider ${base.record.recordId}` }); }
  async appendReview(base: PlanningCheckpoint, review: ReviewIntent, expectedHead: string | undefined): Promise<string> { const path = reviewRecordPath(base.record.recordId), basePath = planningRecordPath(base.record.recordId), baseContents = canonicalPlanningCheckpoint(base), contents = canonicalReviewIntent(review, base); if (!validLedgerPath(path) || review.recordId !== base.record.recordId || review.baseDigest !== checkpointDigest(base)) throw new Error("Review intent is not bound to its base record."); const snapshot = await this.store.snapshot([basePath, path]); if (snapshot.records[basePath] !== baseContents) throw new Error("Review intent base record is missing or changed."); if (snapshot.records[path] !== undefined) { if (snapshot.records[path] !== contents) throw new Error("Review intent already exists with different contents."); return snapshot.head ?? ""; } if (snapshot.head !== expectedHead) throw new Error("Planning ledger advanced before review intent."); return this.store.transact({ expectedHead: snapshot.head, writes: [{ path, contents }], message: `append review intent ${base.record.recordId}` }); }
  async read(recordId: string): Promise<Readonly<{ head: string | undefined; checkpoint?: PlanningCheckpoint; provider?: ProviderCheckpoint; review?: ReviewIntent }>> { const path = planningRecordPath(recordId), providerPath = providerRecordPath(recordId), reviewPath = reviewRecordPath(recordId), snapshot = await this.store.snapshot([path, providerPath, reviewPath]); const contents = snapshot.records[path]; if (contents === undefined) return freeze({ head: snapshot.head }); let checkpoint: PlanningCheckpoint; try { checkpoint = JSON.parse(contents); if (canonicalPlanningCheckpoint(checkpoint) !== contents) throw new Error(); } catch { throw new Error("Planning ledger record is malformed."); } const baseDigest = checkpointDigest(checkpoint); let provider: ProviderCheckpoint | undefined; let review: ReviewIntent | undefined; try { const providerContents = snapshot.records[providerPath]; if (providerContents !== undefined) { const candidate = JSON.parse(providerContents) as ProviderCheckpoint; if (canonicalProviderCheckpoint(candidate, checkpoint) !== providerContents || candidate.recordId !== recordId || candidate.baseDigest !== baseDigest) throw new Error(); provider = candidate; } const reviewContents = snapshot.records[reviewPath]; if (reviewContents !== undefined) { const candidate = JSON.parse(reviewContents) as ReviewIntent; if (canonicalReviewIntent(candidate, checkpoint) !== reviewContents || candidate.recordId !== recordId || candidate.baseDigest !== baseDigest) throw new Error(); review = candidate; } if (provider && review) throw new Error(); } catch { throw new Error("Planning ledger linkage is malformed."); } return freeze({ head: snapshot.head, checkpoint: detached(checkpoint), ...(provider ? { provider: detached(provider) } : {}), ...(review ? { review: detached(review) } : {}) }); }
}
