import { classifyLane, createLaneRecord } from "./classification.js";
import { assertPlanningFacts, deliveryRepository, permits, type PlanningAuthority } from "./authority.js";
import { PlanningLedger, checkpointDigest, topologyDigest, type PlanningCheckpoint, type ProviderCheckpoint, type ReviewIntent } from "./ledger.js";
import { dependencyBlockedPlanningStatus, planningStatus, type PlanningStatus } from "./status.js";
import { mattSteps } from "../adapters/matt-skills.js";
import { runCodexPlanning, type CodexPlanningAdapter } from "../adapters/codex-planning.js";
import { createHash } from "node:crypto";
export interface RequestClassifier { classify(requestText: string): Promise<unknown>; }
/** The service owns the durable record identity; callers only name work and its bound repository. */
export type StartPlanningRequest = Readonly<{ requestText: string; repositoryPath: string }>;
export type ResumePlanningRequest = Readonly<{ deliveryId: string; repositoryPath: string }>;
export type ReviewTarget = Readonly<{ number: number; url: string; headSha: string; baseBranch: string; owner: string; name: string }>;
/** Observer is deliberately the only review port and must be bound by the authority composition root. */
export interface ReviewTargetObserver { observe(input: Readonly<{ owner: string; name: string; number: number; requestedHead: string }>): Promise<ReviewTarget>; }

export class ShipyardOrchestrator {
  constructor(private readonly authority: PlanningAuthority, private readonly classifier: RequestClassifier, private readonly ledger: PlanningLedger, private readonly codex?: CodexPlanningAdapter, private readonly reviews?: ReviewTargetObserver) {}
  async start(raw: StartPlanningRequest): Promise<PlanningStatus> {
    const input = request(raw); let facts = assertPlanningFacts(await this.authority.resolve(input.repositoryPath));
    if (facts.repositoryPath !== input.repositoryPath) throw new Error("Planning authority changed before dispatch.");
    if (!facts.dependencies.ready) return this.blocked(input.requestText, facts, "dependency-not-ready", "Verify the required Codex planning dependencies before dispatch.");
    const recordId = planningRecordId(input.requestText, facts);
    // A caller may have lost the response after a durable write. A complete
    // checkpoint is returned directly; a base-only checkpoint is adopted below
    // after its retry has reproduced the same immutable classification.
    const existing = await this.ledger.read(recordId);
    if (existing.checkpoint) {
      facts = assertPlanningFacts(await this.authority.resolve(input.repositoryPath, existing.checkpoint.record.decision.lane));
      if (!facts.dependencies.ready || !facts.ledgerSha) return this.blocked(input.requestText, facts, "dependency-not-ready", "Verify the selected planning lane dependencies before dispatch.");
      await this.revalidate(facts, input.repositoryPath, existing.head, existing.checkpoint.record.decision.lane);
      if (!matchesCheckpoint(existing.checkpoint, facts)) throw new Error("Planning record is not bound to the current authority.");
      if (existing.provider || existing.review || existing.checkpoint.record.phase === "awaiting-clarification") return planningStatus(existing.checkpoint, existing.provider, existing.review, existing.head ?? existing.checkpoint.pin.historicalBaseLedgerSha);
    }
    await this.revalidate(facts, input.repositoryPath);
    let classified: unknown; try { classified = snapshot(await this.classifier.classify(input.requestText)); } catch { throw new Error("Planning classification could not be completed."); }
    await this.revalidate(facts, input.repositoryPath);
    const decision = classifyLane(decisionSource(classified));
    facts = assertPlanningFacts(await this.authority.resolve(input.repositoryPath, decision.lane));
    if (!facts.dependencies.ready || !facts.ledgerSha) return this.blocked(input.requestText, facts, "dependency-not-ready", "Verify the selected planning lane dependencies before dispatch.");
    const boundReviewTarget = decision.lane === "review-only" ? this.bindReviewTarget(classified, facts) : undefined;
    if (decision.lane === "review-only" && (!permits(facts, "review") || !this.reviews)) throw new Error("A bound read-only review observer is required before recording a review intent.");
    // The review target is part of a review-only request's immutable identity,
    // while remaining a detached digest rather than a second authority object.
    const recordDecision = boundReviewTarget ? Object.freeze({ ...decision, reasons: Object.freeze([...decision.reasons, Object.freeze({ code: "review-target", evidence: reviewTargetDigest(boundReviewTarget) })]) }) : decision;
    const record = createLaneRecord({ recordId, decision: recordDecision, dependencyStates: facts.dependencies.findings.map(row => ({ dependency: row.dependency, state: row.state })), blockers: recordDecision.disposition === "ready" ? [] : [{ code: recordDecision.disposition, message: "Clarify the recorded planning decision before delivery." }] });
    const candidate = this.checkpoint(record, facts, existing.checkpoint?.pin.historicalBaseLedgerSha);
    if (existing.checkpoint && checkpointDigest(existing.checkpoint) !== checkpointDigest(candidate)) throw new Error("Planning retry does not match the immutable record.");
    const checkpoint = existing.checkpoint ?? candidate; await this.revalidate(facts, input.repositoryPath, existing.head ?? facts.ledgerSha, decision.lane); const appended = existing.checkpoint ? { checkpoint, ledgerHead: existing.head } : await this.ledger.append(checkpoint);
    if (decision.disposition !== "ready") return planningStatus(checkpoint, undefined, undefined, appended.ledgerHead ?? checkpoint.pin.historicalBaseLedgerSha);
    if (decision.lane === "review-only") return this.review(checkpoint, boundReviewTarget!, facts, input.repositoryPath, appended.ledgerHead);
    if (!this.codex) return planningStatus(checkpoint, undefined, undefined, appended.ledgerHead ?? checkpoint.pin.historicalBaseLedgerSha);
    await this.revalidate(facts, input.repositoryPath, appended.ledgerHead, decision.lane);
    const lane = decision.lane as "large" | "small" | "bug";
    let result; try { result = await runCodexPlanning(this.codex, { role: "planner", recordId: record.recordId, repositoryPath: facts.repositoryPath, productSha: facts.productSha, objectFormat: facts.objectFormat, lane, steps: mattSteps(lane, "ready"), requestText: input.requestText }, lane === "large" ? { role: "planner", recordId: record.recordId, repositoryPath: facts.repositoryPath, productSha: facts.productSha, objectFormat: facts.objectFormat, steps: ["ccpm-prd", "ccpm-vertical-tasks"], requestText: input.requestText, acceptanceAuthority: false } : undefined, async () => this.revalidate(facts, input.repositoryPath, appended.ledgerHead, decision.lane)); } catch { throw new Error("Planning provider could not be completed."); }
    await this.revalidate(facts, input.repositoryPath, appended.ledgerHead, decision.lane);
    const provider: ProviderCheckpoint = Object.freeze({ schemaVersion: 1, kind: "planning-provider", recordId: record.recordId, baseDigest: checkpointDigest(checkpoint), provider: "codex", phase: lane === "bug" ? "diagnosed" : "planned", resumeCheckpoint: result.resumeCheckpoint, artifacts: result.artifacts });
    await this.revalidate(facts, input.repositoryPath, appended.ledgerHead, decision.lane); const providerHead = await this.ledger.appendProvider(checkpoint, provider, appended.ledgerHead); return planningStatus(checkpoint, provider, undefined, providerHead);
  }
  async resume(raw: ResumePlanningRequest): Promise<PlanningStatus> { const input = resume(raw); const preflight = assertPlanningFacts(await this.authority.resolve(input.repositoryPath)); if (preflight.repositoryPath !== input.repositoryPath || !preflight.dependencies.ready) throw new Error("Planning authority changed before dispatch."); const found = await this.ledger.read(input.deliveryId); if (!found.checkpoint) throw new Error("Planning record was not found."); const facts = assertPlanningFacts(await this.authority.resolve(input.repositoryPath, found.checkpoint.record.decision.lane)); await this.revalidate(facts, input.repositoryPath, found.head, found.checkpoint.record.decision.lane); if (facts.repositoryPath !== input.repositoryPath || !facts.dependencies.ready || !facts.ledgerSha) throw new Error("Planning authority changed before dispatch."); const checkpoint = found.checkpoint; if (!matchesCheckpoint(checkpoint, facts)) throw new Error("Planning authority changed before dispatch."); return planningStatus(checkpoint, found.provider, found.review, found.head ?? checkpoint.pin.historicalBaseLedgerSha); }
  private bindReviewTarget(classified: unknown, facts: ReturnType<typeof assertPlanningFacts>): ReviewTarget { const target = reviewTarget(classified, facts.objectFormat), repository = deliveryRepository(facts); if (target.owner !== repository.owner || target.name !== repository.name || target.baseBranch !== repository.defaultBranch) throw new Error("Review target is not the exact bound repository pull request."); return target; }
  private async review(base: PlanningCheckpoint, target: ReviewTarget, facts: ReturnType<typeof assertPlanningFacts>, repositoryPath: string, head: string | undefined): Promise<PlanningStatus> { if (!permits(facts, "review") || !this.reviews) throw new Error("A bound read-only review observer is required."); const repository = deliveryRepository(facts), lane = base.record.decision.lane; await this.revalidate(facts, repositoryPath, head, lane); let before: ReviewTarget; try { before = snapshot(await this.reviews.observe({ owner: repository.owner, name: repository.name, number: target.number, requestedHead: target.headSha })) as ReviewTarget; } catch { throw new Error("Review target observation could not be completed."); } if (!sameTarget(target, before, repository.owner, repository.name, repository.defaultBranch)) throw new Error("Review target is not the exact bound repository pull request."); await this.revalidate(facts, repositoryPath, head, lane); let after: ReviewTarget; try { after = snapshot(await this.reviews.observe({ owner: repository.owner, name: repository.name, number: target.number, requestedHead: target.headSha })) as ReviewTarget; } catch { throw new Error("Review target observation could not be completed."); } if (!sameTarget(before, after, repository.owner, repository.name, repository.defaultBranch)) throw new Error("Review target changed while observing it."); await this.revalidate(facts, repositoryPath, head, lane); const intent: ReviewIntent = Object.freeze({ schemaVersion: 1, kind: "review-intent", recordId: base.record.recordId, baseDigest: checkpointDigest(base), target: after }); const reviewHead = await this.ledger.appendReview(base, intent, head); return planningStatus(base, undefined, intent, reviewHead); }
  private checkpoint(record: ReturnType<typeof createLaneRecord>, facts: ReturnType<typeof assertPlanningFacts>, historicalBaseLedgerSha = facts.ledgerSha): PlanningCheckpoint { if (!historicalBaseLedgerSha) throw new Error("Planning ledger is not ready."); return Object.freeze({ schemaVersion: 1, record, pin: Object.freeze({ productSha: facts.productSha, historicalBaseLedgerSha, profileName: facts.profile.name, profileFingerprint: facts.binding.profileFingerprint, actorLogin: "visualjc", topologyDigest: topologyDigest(facts.binding.topology), commonDirectoryDigest: digest(facts.binding.commonDirectory), objectFormat: facts.objectFormat }) }); }
  private async revalidate(expected: ReturnType<typeof assertPlanningFacts>, path: string, expectedLedgerHead: string | undefined = expected.ledgerSha, lane?: import("../dependencies/types.js").CapabilityLane): Promise<void> { try { const current = assertPlanningFacts(await this.authority.resolve(path, lane)); if (path !== expected.repositoryPath || current.repositoryPath !== expected.repositoryPath || current.productSha !== expected.productSha || current.ledgerSha !== expectedLedgerHead || current.profile.name !== expected.profile.name || current.binding.profileFingerprint !== expected.binding.profileFingerprint || current.profile.actor.login !== expected.profile.actor.login || current.profile.actor.login !== "visualjc" || topologyDigest(current.binding.topology) !== topologyDigest(expected.binding.topology) || digest(current.binding.commonDirectory) !== digest(expected.binding.commonDirectory) || current.objectFormat !== expected.objectFormat || JSON.stringify(current.dependencies) !== JSON.stringify(expected.dependencies) || !current.dependencies.ready) throw new Error(); } catch { throw new Error("Planning authority changed before dispatch."); } }
  private blocked(requestText: string, facts: ReturnType<typeof assertPlanningFacts>, code: string, message: string): PlanningStatus { return dependencyBlockedPlanningStatus({ recordId: planningRecordId(requestText, facts), productSha: facts.productSha, ledgerSha: facts.ledgerSha, blockers: [{ code, message }], nextSafeCommand: facts.dependencies.nextSafeAction }); }
}
function digest(value: string): string { return createHash("sha256").update(value, "utf8").digest("hex"); }
function snapshot(value: unknown, seen = new Set<object>(), depth = 0): unknown { if (depth > 12 || value === null || ["string", "number", "boolean"].includes(typeof value)) return value; if (!value || typeof value !== "object" || seen.has(value) || Reflect.ownKeys(value).some(key => typeof key !== "string")) throw new Error("Planning classifier response is invalid."); seen.add(value); const d = Object.getOwnPropertyDescriptors(value); if (Object.values(d).some(item => !("value" in item))) throw new Error("Planning classifier response is invalid."); if (Array.isArray(value)) { const length = d.length; if (!length || !("value" in length) || typeof length.value !== "number" || !Number.isSafeInteger(length.value) || length.value > 64 || Object.keys(d).some(key => key !== "length" && !/^(0|[1-9][0-9]*)$/.test(key))) throw new Error("Planning classifier response is invalid."); const out: unknown[] = []; for (let i = 0; i < length.value; i++) { const item = d[String(i)]; if (!item || !("value" in item) || !item.enumerable) throw new Error("Planning classifier response is invalid."); out.push(snapshot(item.value, seen, depth + 1)); } seen.delete(value); return out; } if (Object.values(d).some(item => !item.enumerable)) throw new Error("Planning classifier response is invalid."); const out = Object.fromEntries(Object.keys(d).map(key => [key, snapshot(d[key]!.value, seen, depth + 1)])); seen.delete(value); return out; }
function request(value: unknown): StartPlanningRequest { const v = snapshot(value) as Record<string, unknown>; if (!v || Array.isArray(v) || Object.keys(v).sort().join(",") !== "repositoryPath,requestText" || typeof v.requestText !== "string" || !v.requestText.trim() || v.requestText.length > 16384 || typeof v.repositoryPath !== "string" || !v.repositoryPath.startsWith("/")) throw new Error("Planning request is invalid."); return Object.freeze(v as StartPlanningRequest); }
/**
 * A stable opaque ID lets a retried start adopt the exact durable record without
 * asking a human or an adapter to choose a ledger path. The preimage is never
 * persisted in the ID: it is a domain-separated canonical tuple of bound facts
 * and the exact request text (not the local repository path).
 */
function planningRecordId(requestText: string, facts: ReturnType<typeof assertPlanningFacts>): string {
  const tuple = JSON.stringify(["agentic-shipyard/planning-record-id/v1", facts.productSha, facts.objectFormat, facts.binding.profileFingerprint, topologyDigest(facts.binding.topology), requestText]);
  return `plan-${createHash("sha256").update(tuple, "utf8").digest("hex")}`;
}
function matchesCheckpoint(checkpoint: PlanningCheckpoint, facts: ReturnType<typeof assertPlanningFacts>): boolean {
  return checkpoint.pin.productSha === facts.productSha && checkpoint.pin.profileName === facts.profile.name && checkpoint.pin.profileFingerprint === facts.binding.profileFingerprint && checkpoint.pin.actorLogin === facts.profile.actor.login && checkpoint.pin.topologyDigest === topologyDigest(facts.binding.topology) && checkpoint.pin.commonDirectoryDigest === digest(facts.binding.commonDirectory) && checkpoint.pin.objectFormat === facts.objectFormat;
}
function reviewTargetDigest(target: ReviewTarget): string { return createHash("sha256").update(JSON.stringify([target.owner, target.name, target.number, target.url, target.baseBranch, target.headSha]), "utf8").digest("hex"); }
function resume(value: unknown): ResumePlanningRequest { const v = snapshot(value) as Record<string, unknown>; if (!v || Array.isArray(v) || Object.keys(v).sort().join(",") !== "deliveryId,repositoryPath" || typeof v.repositoryPath !== "string" || !v.repositoryPath.startsWith("/") || typeof v.deliveryId !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(v.deliveryId)) throw new Error("Planning resume request is invalid."); return Object.freeze(v as ResumePlanningRequest); }
function decisionSource(raw: unknown): unknown { if (!raw || typeof raw !== "object" || Array.isArray(raw)) return raw; const row = raw as Record<string, unknown>; return Object.keys(row).length === 2 && "decision" in row && "reviewTarget" in row ? row.decision : raw; }
function reviewTarget(raw: unknown, format: "sha1" | "sha256"): ReviewTarget { const row = raw as Record<string, unknown>, target = row?.reviewTarget; if (!target || typeof target !== "object" || Array.isArray(target)) throw new Error("Review target is required."); const v = target as Record<string, unknown>, sha = format === "sha1" ? /^[a-f0-9]{40}$/ : /^[a-f0-9]{64}$/; if (Object.keys(v).sort().join(",") !== "baseBranch,headSha,name,number,owner,url" || !Number.isSafeInteger(v.number) || (v.number as number) < 1 || typeof v.owner !== "string" || typeof v.name !== "string" || typeof v.baseBranch !== "string" || typeof v.url !== "string" || v.url !== `https://github.com/${v.owner}/${v.name}/pull/${v.number}` || typeof v.headSha !== "string" || !sha.test(v.headSha)) throw new Error("Review target is invalid."); return Object.freeze(v as ReviewTarget); }
function sameTarget(a: ReviewTarget, b: ReviewTarget, owner: string, name: string, branch: string): boolean { return a.number === b.number && a.url === b.url && a.headSha === b.headSha && a.owner === owner && a.name === name && a.baseBranch === branch && b.owner === owner && b.name === name && b.baseBranch === branch && b.url === a.url && b.headSha === a.headSha; }
