import { isAbsolute, join, resolve } from "node:path";
import { graphCacheIdentity, graphDecision, graphOperationLockIdentity, validateGraphDescriptor } from "./freshness.js";
import { snapshotGraphCommandResult } from "./command.js";
import { snapshotGraphSource, type GraphSourceReader } from "./fingerprint.js";
import { snapshotGraphExecutableObservation, withGraphOperationLock, type GraphDescriptorPublisher, type GraphOperationLock, type LocalGraphCommand } from "./graphify.js";
import type { GraphBaseline, GraphDecision, GraphDescriptor, GraphSource } from "./types.js";
import { consumeGraphSeedAuthorization, type GraphSeedAuthorization } from "./baseline.js";

export const CODEGRAPH_RECEIPT = "codegraph@1.5.0#49c11fc2e0c02170742be8411e66a31af611f4b7";
export interface CodeGraphFiles { excluded(path: string, entry: string): Promise<boolean>; addMachineLocalExclude(path: string, entry: string): Promise<void>; tracked(path: string): Promise<boolean>; exists(path: string): Promise<boolean>; canonicalPath(path: string): Promise<string | undefined>; copy?(from: string, to: string): Promise<void>; remove?(path: string): Promise<void>; }
export interface CodeGraphOptions { enabled: boolean; localOnlyApproved: boolean; reviewedToolSource: string; nodeExecutablePath?: string; codegraphExecutablePath?: string; now?(): Date; lock?: GraphOperationLock; sourceReader?: GraphSourceReader; descriptorPublisher?: GraphDescriptorPublisher; command: LocalGraphCommand; files: CodeGraphFiles; }
function plain(value: unknown): Record<string, unknown> | undefined { try { if (!value || typeof value !== "object" || Object.getPrototypeOf(value) !== Object.prototype) return undefined; const d = Object.getOwnPropertyDescriptors(value); if (Object.values(d).some((x) => !("value" in x))) return undefined; return Object.fromEntries(Object.entries(d).map(([k, x]) => [k, x.value])); } catch { return undefined; } }
function binary(value: unknown): string | undefined { return typeof value === "string" && isAbsolute(value) && resolve(value) === value ? value : undefined; }
async function observed(command: LocalGraphCommand, executable: string, receipt: string): Promise<boolean> { try { const v = snapshotGraphExecutableObservation(await command.observe(executable)); return !!v && v.executable === executable && v.sourceReceipt === receipt && v.version.length > 0; } catch { return false; } }
function successful(value: unknown): boolean { const v = snapshotGraphCommandResult(value); return !!v && v.code === 0 && !v.timedOut && v.stderr === ""; }
const fts5 = ["--experimental-sqlite", "-e", "const{DatabaseSync}=require('node:sqlite');const d=new DatabaseSync(':memory:');d.exec('CREATE VIRTUAL TABLE x USING fts5(v)')"] as const;

export async function seedCodeGraph(source: GraphSource, authorization: GraphSeedAuthorization, options: CodeGraphOptions): Promise<{ decision: GraphDecision; descriptor?: GraphDescriptor }> { const authorized = consumeGraphSeedAuthorization(authorization); if (!authorized) return { decision: graphDecision("invalid", "CodeGraph seed requires live Git baseline authorization.") }; try { const target = (await import("./validation.js")).validateGraphSource(source); if (JSON.stringify(target) !== JSON.stringify(authorized.featureSource) || authorized.baseline.descriptor.adapter !== "codegraph" || authorized.baseline.descriptor.reviewedToolSource !== CODEGRAPH_RECEIPT) return { decision: graphDecision("invalid", "Graph seed authorization does not match this exact adapter and feature source.") }; return await operate(target, options, authorized.baseline); } catch { return { decision: graphDecision("failed", "CodeGraph seed boundary failed safely.") }; } }
export async function refreshCodeGraph(source: GraphSource, options: CodeGraphOptions): Promise<{ decision: GraphDecision; descriptor?: GraphDescriptor }> { try { return await operate(source, options); } catch { return { decision: graphDecision("failed", "CodeGraph refresh boundary failed safely.") }; } }

async function operate(source: GraphSource, input: CodeGraphOptions, baseline?: GraphBaseline): Promise<{ decision: GraphDecision; descriptor?: GraphDescriptor }> {
  const o = plain(input); if (!o || typeof o.enabled !== "boolean" || typeof o.localOnlyApproved !== "boolean" || typeof o.reviewedToolSource !== "string") return { decision: graphDecision("invalid", "CodeGraph options are invalid.") };
  if (!o.enabled || !o.localOnlyApproved) return { decision: graphDecision("disabled", "CodeGraph is experimental and requires an explicit local-only enabled profile.") };
  const node = binary(o.nodeExecutablePath), codegraph = binary(o.codegraphExecutablePath);
  if (o.reviewedToolSource !== CODEGRAPH_RECEIPT || !node || !codegraph || !o.lock || !o.sourceReader || !o.command || !o.files) return { decision: graphDecision("invalid", "CodeGraph enabled operation lacks a guarded local boundary.") };
  let checked: GraphSource; try { const { validateGraphSource } = await import("./validation.js"); checked = validateGraphSource(source); } catch { return { decision: graphDecision("invalid", "CodeGraph source is invalid.") }; }
  const fileValues = plain(o.files), commandValues = plain(o.command), readerValues = plain(o.sourceReader), lockValues = plain(o.lock), publisherValues = o.descriptorPublisher === undefined ? undefined : plain(o.descriptorPublisher);
  if (!fileValues || !commandValues || !readerValues || !lockValues || typeof fileValues.canonicalPath !== "function" || typeof fileValues.exists !== "function" || typeof fileValues.excluded !== "function" || typeof fileValues.addMachineLocalExclude !== "function" || typeof fileValues.tracked !== "function" || typeof commandValues.observe !== "function" || typeof commandValues.run !== "function" || typeof readerValues.canonicalWorktree !== "function" || typeof readerValues.worktreeInstanceId !== "function" || typeof readerValues.headSha !== "function" || typeof readerValues.worktreeStatus !== "function" || typeof lockValues.acquire !== "function" || typeof lockValues.release !== "function" || (publisherValues && (typeof publisherValues.write !== "function" || typeof publisherValues.remove !== "function"))) return { decision: graphDecision("invalid", "CodeGraph guarded ports are invalid.") };
  const files = fileValues as unknown as CodeGraphFiles, command = commandValues as unknown as LocalGraphCommand, reader = readerValues as unknown as GraphSourceReader, operationLock = lockValues as unknown as GraphOperationLock;
  const worktreeRoot = await files.canonicalPath(checked.worktreeRoot); const cacheRoot = worktreeRoot && await files.canonicalPath(join(worktreeRoot, ".codegraph"));
  if (!worktreeRoot || !cacheRoot || worktreeRoot !== checked.worktreeRoot || cacheRoot !== join(worktreeRoot, ".codegraph")) return { decision: graphDecision("invalid", "CodeGraph cache must be the canonical worktree-local .codegraph root.") };
  const seedSha = baseline ? baseline.source.headSha : undefined, identity = graphCacheIdentity("codegraph", CODEGRAPH_RECEIPT, checked, seedSha), lockIdentity = graphOperationLockIdentity("codegraph", CODEGRAPH_RECEIPT, checked);
  const outcome = await withGraphOperationLock(operationLock, cacheRoot, lockIdentity, async () => {
    if (!await observed(command, node, "node:sqlite-fts5") || !await observed(command, codegraph, CODEGRAPH_RECEIPT)) return { decision: graphDecision("unavailable", "CodeGraph executable observation failed.") };
    if (!successful(await command.run(node, fts5, { cwd: worktreeRoot, env: { CODEGRAPH_TELEMETRY: "0" } }))) return { decision: graphDecision("unavailable", "Selected Node runtime cannot create an SQLite FTS5 table.") };
    if (baseline && (!files.copy || !files.remove || await files.exists(cacheRoot))) return { decision: graphDecision("invalid", "CodeGraph seed cache must be new.") };
    await files.addMachineLocalExclude(worktreeRoot, ".codegraph/");
    if (!await files.excluded(worktreeRoot, ".codegraph/") || await files.tracked(cacheRoot)) return { decision: graphDecision("failed", "CodeGraph cache exclusion is absent or tracked.") };
    if (baseline) {
      try { await files.copy!(baseline.descriptor.cacheRoot, cacheRoot); if (!await files.exists(cacheRoot) || await files.tracked(cacheRoot)) throw new Error(); }
      catch { try { await files.remove!(cacheRoot); } catch {} return { decision: graphDecision("failed", "CodeGraph seed verification failed.") }; }
    } else if (!successful(await command.run(codegraph, ["index"], { cwd: worktreeRoot, env: { CODEGRAPH_TELEMETRY: "0" } })) || !await files.exists(cacheRoot)) return { decision: graphDecision("failed", "CodeGraph refresh verification failed.") };
    let after: GraphSource; try { after = await snapshotGraphSource(reader, worktreeRoot); } catch { return { decision: graphDecision("stale", "Graph source cannot be reread after operation.") }; }
    if (!await files.excluded(worktreeRoot, ".codegraph/") || await files.tracked(cacheRoot)) return { decision: graphDecision("failed", "CodeGraph post-operation exclusion verification failed.") };
    if (after.headSha !== checked.headSha || after.workingTreeFingerprint !== checked.workingTreeFingerprint || after.worktreeInstanceId !== checked.worktreeInstanceId || after.worktreeRoot !== checked.worktreeRoot) return { decision: graphDecision("stale", "Graph source changed while operation ran.") };
    const descriptor: GraphDescriptor = Object.freeze({ adapter: "codegraph", reviewedToolSource: CODEGRAPH_RECEIPT, cacheIdentity: identity, cacheRoot, worktreeRoot, worktreeInstanceId: checked.worktreeInstanceId, indexedCommit: checked.headSha, workingTreeFingerprint: checked.workingTreeFingerprint, refreshedAt: typeof o.now === "function" ? (o.now as () => Date)().toISOString() : "1970-01-01T00:00:00.000Z", ...(seedSha ? { seededFromSha: seedSha } : {}) });
    const decision = validateGraphDescriptor(after, descriptor, "codegraph", CODEGRAPH_RECEIPT); if (!decision.authoritative) return { decision };
    if (publisherValues) await (publisherValues as unknown as GraphDescriptorPublisher).write(descriptor);
    return { decision, descriptor };
  }, join(resolve(worktreeRoot), "..", ".shipyard-graph-state"), publisherValues ? () => (publisherValues as unknown as GraphDescriptorPublisher).remove() : undefined);
  return "state" in outcome ? { decision: outcome } : outcome;
}
