import type { CapabilityDependency, CapabilityManifest, ContentReceipt, DependencyId, ObservedDependencyReceipt, RuntimeReceipt, SourceReceipt } from "./types.js";

export type DependencyFailureCode = "invalid-dependency-document" | "dependency-not-ready";
export class DependencyError extends Error { readonly name = "DependencyError"; constructor(readonly code: DependencyFailureCode, message: string) { super(message); } }
const IDS = new Set<DependencyId>(["matt-skills", "ccpm", "codex", "claude-code", "cursor-pstack"]);
const HOSTS = new Set(["codex", "claude-code", "cursor-pstack"]);
const LANES = new Set(["large", "small", "bug", "review-only"]);
const SOURCES: Readonly<Record<"matt-skills" | "ccpm", SourceReceipt>> = Object.freeze({
  "matt-skills": { kind: "git-commit", repository: "https://github.com/mattpocock/skills", commit: "2ab958093e83e0ec752e6c1c5932da465bf23e0c" },
  ccpm: { kind: "git-commit", repository: "https://github.com/visualjc/ccpm", commit: "cdb97474904ab2cdc7d391aa17393b444a28be3e" },
});
const fail = (): never => { throw new DependencyError("invalid-dependency-document", "Dependency input is not a bounded canonical v1 document."); };
type Plain = Record<string, unknown>;
const data = (value: PropertyDescriptor | undefined): value is PropertyDescriptor & { value: unknown } => Boolean(value && "value" in value);
function snapshot(value: unknown, seen = new Set<object>(), depth = 0): unknown { try { if (depth > 10) fail(); if (value === null || typeof value === "boolean" || typeof value === "number" || typeof value === "string") return value; if (!value || typeof value !== "object" || seen.has(value)) fail(); const object = value as object; seen.add(object); if (Array.isArray(value)) { const all = Object.getOwnPropertyDescriptors(object) as Record<string, PropertyDescriptor>, length = all["length"]; if (!data(length) || typeof length.value !== "number" || !Number.isSafeInteger(length.value) || length.value > 512 || Reflect.ownKeys(object).some(key => key !== "length" && (typeof key !== "string" || !/^(0|[1-9][0-9]*)$/.test(key)))) fail(); const result: unknown[] = []; for (let index = 0; index < length.value; index++) { const descriptor = all[String(index)]; if (!data(descriptor) || !descriptor.enumerable) fail(); result.push(snapshot((descriptor as { value: unknown }).value, seen, depth + 1)); } seen.delete(object); return result; } if (Object.getPrototypeOf(object) !== Object.prototype) fail(); const result: Plain = {}; for (const rawKey of Reflect.ownKeys(object)) { if (typeof rawKey !== "string") fail(); const key = rawKey as string, descriptor = Object.getOwnPropertyDescriptor(object, key); if (!data(descriptor) || !descriptor.enumerable) fail(); result[key] = snapshot((descriptor as { value: unknown }).value, seen, depth + 1); } seen.delete(object); return result; } catch { fail(); } }
function exact(value: unknown, keys: readonly string[], optional: readonly string[] = []): Plain { const snap = snapshot(value); if (!snap || typeof snap !== "object" || Array.isArray(snap)) fail(); const record = snap as Plain; if (Object.keys(record).some(key => !keys.includes(key)) || keys.some(key => !optional.includes(key) && !(key in record))) fail(); return record; }
function text(value: unknown, max = 4096): string { if (typeof value !== "string" || value.trim() === "" || value !== value.trim() || value.includes("\0") || value.length > max) fail(); return value as string; }
function path(value: unknown): string { const result = text(value, 512); if (result.startsWith("/") || result.includes("\\") || result.split("/").some(part => part === "" || part === "." || part === "..")) fail(); return result; }
function sha1(value: unknown): string { const result = text(value, 40); if (!/^[a-f0-9]{40}$/.test(result)) fail(); return result; }
function freeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as Record<string, unknown>)) freeze(child); Object.freeze(value); } return value; }
function strings(value: unknown, max: number, allowed?: ReadonlySet<string>, allowEmpty = false): readonly string[] { if (!Array.isArray(value) || (!allowEmpty && value.length === 0) || value.length > max) fail(); const result = (value as unknown[]).map((item: unknown) => text(item)); if (new Set(result).size !== result.length || (allowed && result.some((item: string) => !allowed.has(item)))) fail(); return Object.freeze(result); }
function source(value: unknown, id: DependencyId, enforce = false): SourceReceipt | undefined { if (value === undefined) return undefined; const row = exact(value, ["kind", "repository", "commit"]); if (row.kind !== "git-commit") fail(); const result = freeze({ kind: "git-commit" as const, repository: text(row.repository), commit: sha1(row.commit) }); const expected = id === "matt-skills" || id === "ccpm" ? SOURCES[id] : undefined; if (enforce && expected && (result.repository !== expected.repository || result.commit !== expected.commit)) fail(); return result; }
function content(value: unknown): ContentReceipt { const row = exact(value, ["kind", "skills", "subpath", "treeSha", "requiredFiles"], ["skills", "subpath", "treeSha", "requiredFiles"]); if (row.kind === "none") { if (Object.keys(row).length !== 1) fail(); return freeze({ kind: "none" }); } if (row.kind === "git-tree") { if (row.skills !== undefined) fail(); return freeze({ kind: "git-tree", subpath: path(row.subpath), treeSha: sha1(row.treeSha), requiredFiles: strings(row.requiredFiles, 32).map(path) }); } if (row.kind === "matt-skill-trees") { if (!Array.isArray(row.skills) || row.skills.length !== 20 || row.subpath !== undefined || row.treeSha !== undefined || row.requiredFiles !== undefined) fail(); const skills = (row.skills as unknown[]).map((value: unknown) => { const item = exact(value, ["name", "sourcePath", "treeSha", "requiredFiles"]); return freeze({ name: text(item.name, 128), sourcePath: path(item.sourcePath), treeSha: sha1(item.treeSha), requiredFiles: strings(item.requiredFiles, 16).map(path) }); }); if (new Set(skills.map((item) => item.name)).size !== 20 || new Set(skills.map((item) => item.sourcePath)).size !== 20) fail(); return freeze({ kind: "matt-skill-trees", skills }); } return fail(); }
function runtime(value: unknown): RuntimeReceipt { const row = exact(value, ["kind", "host", "version"]); if (row.kind !== "runtime-version" || typeof row.host !== "string" || !HOSTS.has(row.host)) fail(); return freeze({ kind: "runtime-version", host: text(row.host) as RuntimeReceipt["host"], version: text(row.version, 128) }); }
function invocation(value: unknown) { const row = exact(value, ["command", "frontmatterName", "requiredFiles"]); return freeze({ command: text(row.command, 128), frontmatterName: text(row.frontmatterName, 128), requiredFiles: strings(row.requiredFiles, 32, undefined, true).map(path) }); }
export function validateCapabilityManifest(value: unknown): CapabilityManifest { const root = exact(value, ["schemaVersion", "dependencies"]); if (root.schemaVersion !== 1 || !Array.isArray(root.dependencies) || root.dependencies.length === 0 || root.dependencies.length > 8) fail(); const dependencies = (root.dependencies as unknown[]).map((value: unknown) => { const row = exact(value, ["id", "source", "content", "runtime", "hosts", "lanes", "invocation", "canonicalDiscovery"], ["source", "runtime"]); const id = text(row.id) as DependencyId; if (!IDS.has(id)) fail(); const checkedSource = source(row.source, id, true); const result: CapabilityDependency = { id, ...(checkedSource ? { source: checkedSource } : {}), content: content(row.content), ...(row.runtime === undefined ? {} : { runtime: runtime(row.runtime) }), hosts: strings(row.hosts, 3, HOSTS) as CapabilityDependency["hosts"], lanes: strings(row.lanes, 4, LANES) as CapabilityDependency["lanes"], invocation: invocation(row.invocation), canonicalDiscovery: strings(row.canonicalDiscovery, 32, undefined, true).map(path) }; return freeze(result); }); if (new Set(dependencies.map((item) => item.id)).size !== dependencies.length) fail(); return freeze({ schemaVersion: 1, dependencies }); }
export function validateObservedDependencyReceipt(value: unknown): ObservedDependencyReceipt { const root = exact(value, ["id", "source", "content", "discoveryPaths", "invocation", "skillMetadata", "runtimes"], ["source", "content", "invocation", "skillMetadata"]); const id = text(root.id) as DependencyId; if (!IDS.has(id)) fail(); const invocationValue = root.invocation === undefined ? undefined : exact(root.invocation, ["command", "frontmatterName"], ["command", "frontmatterName"]); const skillMetadata = root.skillMetadata === undefined ? undefined : (() => { if (!Array.isArray(root.skillMetadata) || root.skillMetadata.length > 20) fail(); const values = (root.skillMetadata as unknown[]).map((entry: unknown) => { const row = exact(entry, ["name", "frontmatterName", "files"]); return freeze({ name: text(row.name, 128), frontmatterName: text(row.frontmatterName, 128), files: strings(row.files, 16).map(path) }); }); if (new Set(values.map(item => item.name)).size !== values.length) fail(); return Object.freeze(values); })(); return freeze({ id, ...(root.source === undefined ? {} : { source: source(root.source, id) }), ...(root.content === undefined ? {} : { content: content(root.content) }), discoveryPaths: strings(root.discoveryPaths, 32, undefined, true).map(path), ...(invocationValue === undefined ? {} : { invocation: freeze({ ...(invocationValue.command === undefined ? {} : { command: text(invocationValue.command) }), ...(invocationValue.frontmatterName === undefined ? {} : { frontmatterName: text(invocationValue.frontmatterName) }) }) }), ...(skillMetadata ? { skillMetadata } : {}), runtimes: (() => { if (!Array.isArray(root.runtimes) || root.runtimes.length > 8) fail(); const results = (root.runtimes as unknown[]).map(runtime); if (new Set(results.map((item) => item.host)).size !== results.length) fail(); return Object.freeze(results); })() }); }
