import { DependencyError, validateCapabilityManifest, validateObservedDependencyReceipt } from "./schema.js";
import type { CapabilityHost, CapabilityLane, CapabilityManifest, ContentReceipt, DependencyFinding, DependencyStatus, ObservedDependencyReceipt } from "./types.js";
export { DependencyError } from "./schema.js";
const freeze = <T>(value: T): T => { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as Record<string, unknown>)) freeze(child); Object.freeze(value); } return value; };
const finding = (dependency: DependencyFinding["dependency"], state: DependencyFinding["state"], remediation: string): DependencyFinding => freeze({ dependency, state, remediation });
const data = (descriptor: PropertyDescriptor | undefined): descriptor is PropertyDescriptor & { value: unknown } => Boolean(descriptor && "value" in descriptor);
function snapshotObservations(value: unknown): readonly unknown[] { try { if (!Array.isArray(value)) throw new Error(); const object = value as object, length = Object.getOwnPropertyDescriptor(object, "length"); if (!data(length) || typeof length.value !== "number" || !Number.isSafeInteger(length.value) || length.value > 16) throw new Error(); const result: unknown[] = []; for (let index = 0; index < length.value; index++) { const descriptor = Object.getOwnPropertyDescriptor(object, String(index)); if (!data(descriptor) || !descriptor.enumerable) throw new Error(); result.push(descriptor.value); } if (Reflect.ownKeys(object).some(key => key !== "length" && (typeof key !== "string" || !/^(0|[1-9][0-9]*)$/.test(key)))) throw new Error(); return Object.freeze(result); } catch { throw new DependencyError("invalid-dependency-document", "Dependency observations must be a bounded plain collection."); } }
function safeSelected(value: unknown): Readonly<{ host: CapabilityHost; lane: CapabilityLane }> { try { if (!value || typeof value !== "object" || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) throw new Error(); const object = value as object, keys = Reflect.ownKeys(object); if (keys.length !== 2 || keys.some(key => key !== "host" && key !== "lane")) throw new Error(); const host = Object.getOwnPropertyDescriptor(object, "host"), lane = Object.getOwnPropertyDescriptor(object, "lane"); if (!data(host) || !data(lane) || !host.enumerable || !lane.enumerable || typeof host.value !== "string" || typeof lane.value !== "string" || !["codex", "claude-code", "cursor-pstack"].includes(host.value) || !["large", "small", "bug", "review-only"].includes(lane.value)) throw new Error(); return Object.freeze({ host: host.value as CapabilityHost, lane: lane.value as CapabilityLane }); } catch { throw new DependencyError("invalid-dependency-document", "Selected host and lane must be a bounded plain document."); } }
function sameContent(expected: ContentReceipt, observed: ContentReceipt | undefined): boolean { if (!observed || expected.kind !== observed.kind) return false; if (expected.kind === "none") return true; if (expected.kind === "git-tree" && observed.kind === "git-tree") return expected.subpath === observed.subpath && expected.treeSha === observed.treeSha && JSON.stringify(expected.requiredFiles) === JSON.stringify(observed.requiredFiles); if (expected.kind === "matt-skill-trees" && observed.kind === "matt-skill-trees") return JSON.stringify(expected.skills) === JSON.stringify(observed.skills); return false; }
/** Compare bounded observations only. These values can never grant operation or provider authority. */
export function verifyDependencies(manifest: unknown, observations: unknown, selected: unknown): DependencyStatus {
  const safeManifest = validateCapabilityManifest(manifest), safeObservations = snapshotObservations(observations).map(validateObservedDependencyReceipt), safeSelection = safeSelected(selected), results: DependencyFinding[] = [];
  for (const dependency of safeManifest.dependencies) {
    const required = dependency.hosts.includes(safeSelection.host) && dependency.lanes.includes(safeSelection.lane);
    if (!required) { results.push(finding(dependency.id, "not-required", "No action: this dependency is outside the selected Codex v1 lane.")); continue; }
    const matches = safeObservations.filter(item => item.id === dependency.id);
    if (matches.length === 0) { results.push(finding(dependency.id, "missing", "Install the recorded reviewed receipt using its owning maintenance workflow.")); continue; }
    if (matches.length !== 1 || matches[0]!.discoveryPaths.length !== dependency.canonicalDiscovery.length || matches[0]!.discoveryPaths.some((path, index) => path !== dependency.canonicalDiscovery[index])) { results.push(finding(dependency.id, "duplicate", "Expose exactly the canonical discovery definitions before retrying.")); continue; }
    const observed = matches[0]!;
    if (dependency.source && !observed.source) { results.push(finding(dependency.id, "missing", "Record the reviewed source receipt from its owning maintenance workflow.")); continue; }
    if (dependency.source && observed.source && observed.source.repository !== dependency.source.repository) { results.push(finding(dependency.id, "incompatible", "Use the required v1 dependency source; do not substitute an arbitrary path.")); continue; }
    if (dependency.source && observed.source && observed.source.commit !== dependency.source.commit) { results.push(finding(dependency.id, "unverified", "Review and explicitly approve this changed receipt before updating the capability manifest.")); continue; }
    if (!observed.content) { results.push(finding(dependency.id, "missing", "Record the required reviewed content receipt from its owning maintenance workflow.")); continue; }
    if (!sameContent(dependency.content, observed.content)) { results.push(finding(dependency.id, "modified", "Restore the reviewed content receipt; Shipyard will not repair or vendor it.")); continue; }
    if (dependency.content.kind === "matt-skill-trees" && (!observed.skillMetadata || observed.skillMetadata.length !== dependency.content.skills.length || dependency.content.skills.some(skill => { const metadata = observed.skillMetadata!.find(item => item.name === skill.name); return !metadata || metadata.frontmatterName !== skill.name || !skill.requiredFiles.every(file => metadata.files.includes(file)); }))) { results.push(finding(dependency.id, "incompatible", "Restore each Matt skill's own frontmatter name and required files from the reviewed receipt.")); continue; }
    if (observed.invocation?.command !== dependency.invocation.command || observed.invocation?.frontmatterName !== dependency.invocation.frontmatterName) { results.push(finding(dependency.id, "incompatible", "Restore required skill metadata from the reviewed receipt.")); continue; }
    if (dependency.runtime) { const runtime = observed.runtimes.find(item => item.host === dependency.runtime!.host); if (!runtime) { results.push(finding(dependency.id, "missing", "Install the selected tested runtime without changing Shipyard.")); continue; } if (runtime.version !== dependency.runtime.version) { results.push(finding(dependency.id, "unverified", "The runtime differs from the tested v1 receipt; review it explicitly before use.")); continue; } }
    if (safeSelection.host !== "codex") { results.push(finding(dependency.id, "incompatible", "Claude Code and Cursor/Pstack are deferred and unsupported in v1.")); continue; }
    results.push(finding(dependency.id, "ready", "Ready; no dependency change is authorized."));
  }
  const ready = results.filter(item => item.state !== "not-required").every(item => item.state === "ready");
  return freeze({ schemaVersion: 1, findings: Object.freeze(results), ready, nextSafeAction: ready ? "shipyard" : "shipyard-setup" });
}
