import assert from "node:assert/strict";
import test from "node:test";
import type { Profile } from "../../src/contracts/types.js";
import { profileFingerprint } from "../../src/profile/fingerprint.js";
import { MutationLockService } from "../../src/locking/mutation-lock.js";
import { createPayloadPlan } from "../../src/promotion/payload.js";
import { destinationMarker } from "../../src/promotion/provider.js";
import type { PromotionManifest } from "../../src/promotion/types.js";
import { promotionManifestDigest } from "../../src/promotion/manifest.js";
import { createTrustedStagedFinalizationOperation } from "../../src/finalization/service.js";
import type { FinalizationIntent, FinalizationReceipt } from "../../src/finalization/types.js";
import { verifyDestinationMerge } from "../../src/finalization/merge-policy.js";
import { FakeProcess, MemoryFilesystem } from "../helpers/fakes.js";

const sha=(letter:string)=>letter.repeat(40),digest=(letter:string)=>letter.repeat(64),sourceSha=sha("a"),parentSha=sha("b"),destinationCommit=sha("c"),destinationTree=sha("d"),mergeSha=sha("e"),mainSha=sha("f"),development={owner:"acme",name:"development",remote:{name:"origin",url:"https://github.com/acme/development.git"},defaultBranch:"main"},destination={owner:"acme",name:"destination",remote:{name:"destination",url:"https://github.com/acme/destination.git"},defaultBranch:"main"},topology={kind:"staged-pair" as const,development,destination},entry=(objectId:string)=>({path:"app.ts",mode:"100644" as const,objectId}),plan=createPayloadPlan({sourceSha,parentDestinationSha:parentSha,sourceEntries:[entry(sourceSha)],destinationEntries:[entry(parentSha)],classification:{source:new Map([["app.ts","product"]]),destination:new Map([["app.ts","product"]])}}),evidence={productSha:sourceSha,ledgerSha:sha("1"),manifestDigest:digest("1"),acceptanceDigest:digest("2"),reviewId:"review",reviewRequestDigest:digest("3"),reviewResultDigest:digest("4"),reviewedLedgerSha:sha("2"),reviewerBundleDigest:digest("5"),evaluatedAt:"2026-08-04T00:00:00.000Z"};
const openPull={id:"PR_dest",number:7,url:"https://github.com/acme/destination/pull/7",marker:destinationMarker("delivery"),repository:{owner:"acme",name:"destination"},headRepository:{owner:"acme",name:"destination"},baseRepository:{owner:"acme",name:"destination"},headRef:"shipyard/delivery",baseRef:"main",headSha:destinationCommit,state:"open" as const,isCrossRepository:false as const},mergedPull={...openPull,state:"merged" as const,mergeCommitSha:mergeSha},records={issue:{id:"I_dev",number:2,url:"https://github.com/acme/development/issues/2",state:"open" as const},pullRequest:{id:"PR_dev",number:3,url:"https://github.com/acme/development/pull/3",state:"open" as const,merged:false,headRef:"shipyard/delivery",headSha:sourceSha}};
const initialManifest:PromotionManifest={schemaVersion:1,deliveryId:"delivery",actorLogin:"actor",development:{repository:development,branch:"shipyard/delivery"},destination:{repository:destination,branch:"shipyard/delivery",baselineSha:parentSha},mappings:[{revision:1,developmentSha:sourceSha,destinationParentSha:parentSha,destinationCommitSha:destinationCommit,destinationTreeSha:destinationTree,projectedProductTreeSha:destinationTree,policyDigest:plan.policyDigest,projectionDigest:plan.projectionDigest,evidence,promotedAt:"2026-08-04T00:00:00.000Z"}],pullRequest:openPull,phase:"awaiting-human-merge"};
function receipt(){return Object.freeze({schemaVersion:1 as const,issueId:"JG-1",deliveryId:"delivery",actorLogin:"actor",...evidence,reviewId:"review",decision:Object.freeze({promotionEligible:true,acceptanceFresh:true,reviewFresh:true,blockingFindingIds:Object.freeze([] as string[]),staleRecordIds:Object.freeze([] as string[]),blockers:Object.freeze([] as string[]),nextAction:"proceed-to-promotion-gate" as const})});}

test("human merge finalization resumes after observed provider and branch-delete mutations and seals the complete journal last",async()=>{const profile:Profile={schemaVersion:1,name:"test",actor:{login:"actor"},topology,allowedOperations:["finalize"],pathPolicy:{schemaVersion:1,rules:[{owner:"product",pattern:"**"}]}},fingerprint=profileFingerprint(profile),authority={profileName:"test",commonDirectory:"/repo/.git",profileFingerprint:fingerprint,actorLogin:"actor",topology},events:string[]=[],fs=new MemoryFilesystem(),journalEntries:any[]=[];let manifest=structuredClone(initialManifest) as PromotionManifest,intent:FinalizationIntent|undefined,finalReceipt:FinalizationReceipt|undefined,issueClosed=false,prClosed=false,failAfterIssueClose=true,failCleanup=true,failDestinationDelete=true,eligible=true,developmentBranchSha:string|undefined=sourceSha,destinationBranchSha:string|undefined=destinationCommit;
  const promotionLedger={read:async()=>({head:sha("8"),manifest,journal:{schemaVersion:1,deliveryId:"delivery",entries:journalEntries}}),writeManifest:async(_snapshot:unknown,next:PromotionManifest)=>{events.push(`manifest:${next.phase}`);manifest=structuredClone(next) as PromotionManifest;return sha("8");},append:async(_snapshot:unknown,item:any)=>{if(!journalEntries.some(entry=>entry.idempotencyKey===item.idempotencyKey)){journalEntries.push({...item,sequence:journalEntries.length+1});events.push(`journal:${item.step}`);}return sha("8");}};
  const finalizationLedger={read:async()=>({head:sha("8"),...(intent?{intent}:{}),...(finalReceipt?{receipt:finalReceipt}:{})}),writeIntent:async(value:FinalizationIntent)=>{events.push("intent");intent=structuredClone(value);return sha("8");},writeReceipt:async(value:FinalizationReceipt)=>{events.push("receipt");finalReceipt=structuredClone(value);return sha("8");},durableRecordPaths:async()=>["deliveries/delivery/finalization/intent.json","deliveries/delivery/finalization/receipt.json","deliveries/delivery/promotion/journal.json","deliveries/delivery/promotion/manifest.json"],seal:async()=>{events.push("seal");return sha("9");}};
  const providerSession={reconcileDestinationPullRequest:async()=>{throw new Error("not promoting");},updateDestinationDossier:async()=>{throw new Error("not promoting");},observeDestinationPullRequest:async()=>mergedPull,observeDevelopmentRecords:async()=>({issue:{...records.issue,state:issueClosed?"closed" as const:"open" as const},pullRequest:{...records.pullRequest,state:prClosed?"closed" as const:"open" as const}}),closeDevelopmentPullRequest:async()=>{events.push("close-pr");prClosed=true;},closeDevelopmentIssue:async()=>{events.push("close-issue");issueClosed=true;if(failAfterIssueClose){failAfterIssueClose=false;throw new Error("provider response lost");}}};
  const gitSession=()=>({observation:{destinationMainSha:mainSha,developmentMainSha:parentSha,...(destinationBranchSha?{destinationBranchSha}:{}),...(developmentBranchSha?{developmentBranchSha}:{}),mergeCommitSha:mergeSha,mergeCommitTreeSha:destinationTree,mergeParents:[parentSha],mergeCommitAncestorOfMain:true,finalDestinationCommitAncestorOfMerge:false},ensureReviewedTag:async()=>{events.push("tag");return sha("7");},synchronizeDevelopmentMain:async()=>{events.push("sync-main");},deleteDevelopmentBranch:async()=>{events.push("delete-dev-branch");developmentBranchSha=undefined;},deleteDestinationBranch:async()=>{events.push("delete-destination-branch");destinationBranchSha=undefined;if(failDestinationDelete){failDestinationDelete=false;throw new Error("destination delete response lost");}},publishLedger:async()=>{events.push("publish-seal");},release:async()=>{}});
  const operation=createTrustedStagedFinalizationOperation({repositoryPath:"/repo",authority:{resolve:async()=>authority},profiles:{read:async()=>profile},deliveries:{resolve:async()=>({binding:{schemaVersion:1,profileName:"test",commonDirectory:"/repo/.git",topology,profileFingerprint:fingerprint,boundAt:"2026-08-04T00:00:00.000Z"},workspace:{schemaVersion:1,state:"ready",creationToken:"11111111-1111-4111-8111-111111111111",deliveryId:"delivery",commonDirectory:"/repo/.git",branch:"shipyard/delivery",worktreePath:"/repo-delivery"}})},evidence:{evaluate:async()=>({...receipt().decision,promotionEligible:eligible}),evaluateReceipt:async()=>({...receipt(),decision:{...receipt().decision,promotionEligible:eligible}})},stagedGit:{stage:async request=>{assert.equal(request.sourceBaselineSha,parentSha);return {observation:{objectFormat:"sha1",sourceSha,sourceTreeSha:sourceSha,sourceEntries:[entry(sourceSha)],destinationMainSha:parentSha,destinationMainEntries:[entry(parentSha)],destinationBranchHeadSha:destinationCommit,destinationBranchTreeSha:destinationTree,destinationBranchEntries:[entry(sourceSha)],recordedDestinationParentEntries:[entry(parentSha)]},publish:async()=>{throw new Error("not publishing");},release:async()=>{}};}},git:{open:async()=>gitSession()},provider:{open:async()=>providerSession},promotionLedger:promotionLedger as any,finalizationLedger:finalizationLedger as any,cleanup:{removeOwned:async()=>{events.push("cleanup");if(failCleanup){failCleanup=false;throw new Error("cleanup response lost");}}},mergePolicy:{resolve:async()=>"squash"},locks:new MutationLockService(fs,new FakeProcess()),lockPath:()=>"/finalize.lock",now:()=>new Date("2026-08-04T00:00:00.000Z")});
  await assert.rejects(operation.observeAndFinalize({deliveryId:"delivery"}),/provider response lost/);assert.ok(intent);assert.equal(manifest.phase,"finalizing");assert.equal(manifest.pullRequest!.state,"merged");assert.equal(promotionManifestDigest({...manifest,pullRequest:openPull,phase:"awaiting-human-merge"}),intent!.manifestDigest);assert.equal(prClosed,true);assert.equal(issueClosed,true);assert.ok(!events.includes("seal"));eligible=false;const tagsBefore=events.filter(event=>event==="tag").length;await assert.rejects(operation.observeAndFinalize({deliveryId:"delivery"}),/receipt changed/i);assert.equal(events.filter(event=>event==="tag").length,tagsBefore);eligible=true;await assert.rejects(operation.observeAndFinalize({deliveryId:"delivery"}),/cleanup response lost/);assert.ok(journalEntries.some(entry=>entry.step==="development-branch-delete-started"));assert.equal(developmentBranchSha,undefined);await assert.rejects(operation.observeAndFinalize({deliveryId:"delivery"}),/destination delete response lost/);assert.ok(journalEntries.some(entry=>entry.step==="destination-branch-delete-started"));assert.equal(destinationBranchSha,undefined);const result=await operation.observeAndFinalize({deliveryId:"delivery"});assert.equal(result.phase,"complete");assert.equal(result.sealSha,sha("9"));assert.equal(manifest.phase,"complete");assert.equal(finalReceipt!.developmentPullRequestState,"closed-unmerged");assert.ok(events.indexOf("seal")>events.indexOf("receipt"));assert.ok(events.indexOf("seal")>events.lastIndexOf("journal:final-receipt-recorded"));assert.ok(events.indexOf("publish-seal")>events.indexOf("seal"));
});

test("merge verification honors declared merge, squash, and rebase policies while allowing main to advance",()=>{const intent={finalDestinationCommitSha:destinationCommit,finalDestinationTreeSha:destinationTree,destinationMergeSha:mergeSha,destinationMainSha:mainSha},base={destinationMainSha:mainSha,developmentMainSha:parentSha,mergeCommitSha:mergeSha,mergeCommitTreeSha:destinationTree,mergeParents:[parentSha,destinationCommit],mergeCommitAncestorOfMain:true,finalDestinationCommitAncestorOfMerge:true};assert.doesNotThrow(()=>verifyDestinationMerge("merge-commit",intent,base));assert.doesNotThrow(()=>verifyDestinationMerge("squash",intent,{...base,mergeParents:[parentSha],finalDestinationCommitAncestorOfMerge:false}));assert.doesNotThrow(()=>verifyDestinationMerge("rebase",intent,{...base,mergeParents:[parentSha],finalDestinationCommitAncestorOfMerge:false}));assert.throws(()=>verifyDestinationMerge("merge-commit",intent,{...base,mergeParents:[parentSha]}),/does not contain/i);assert.throws(()=>verifyDestinationMerge("squash",intent,{...base,mergeCommitTreeSha:sha("9")}),/does not preserve/i);assert.throws(()=>verifyDestinationMerge("rebase",intent,{...base,mergeCommitAncestorOfMain:false}),/not reachable/i);});
