import { canonicalJson } from "../evidence/schema.js";
import { stableDeliveryId } from "../delivery/registry.js";
import { PromotionError } from "./errors.js";
import type { DestinationPullRequest, PromotionEvidencePin, PromotionJournal, PromotionJournalEntry, PromotionJournalStep, PromotionManifest, PromotionMapping } from "./types.js";

const PHASES=new Set(["promoting","awaiting-human-merge","finalizing","complete"]),STEPS=new Set<PromotionJournalStep>(["destination-branch-published","destination-pr-created","destination-pr-updated","final-intent-recorded","reviewed-tag-published","development-main-synchronized","development-pr-closed","development-issue-closed","development-branch-delete-started","development-branch-deleted","destination-branch-delete-started","destination-branch-deleted","final-receipt-recorded"]);

export function promotionManifestContents(value:PromotionManifest):string{return canonicalJson(validatePromotionManifest(value));}
export function promotionJournalContents(value:PromotionJournal):string{return canonicalJson(validatePromotionJournal(value));}

export function validatePromotionManifest(value:unknown):PromotionManifest{try{const root=record(value,["schemaVersion","deliveryId","actorLogin","development","destination","mappings","pullRequest","phase"],["pullRequest"]);if(root.schemaVersion!==1||!text(root.actorLogin)||!PHASES.has(String(root.phase))||!Array.isArray(root.mappings))invalid();const deliveryId=stableDeliveryId(root.deliveryId),development=record(root.development,["repository","branch"]),destination=record(root.destination,["repository","branch","baselineSha"]),mappings=root.mappings.map((entry,index)=>mapping(entry,index+1));if(mappings.length===0||new Set(mappings.map(entry=>entry.developmentSha)).size!==mappings.length||new Set(mappings.map(entry=>entry.destinationCommitSha)).size!==mappings.length)invalid();for(let index=1;index<mappings.length;index++)if(mappings[index]!.destinationParentSha!==mappings[index-1]!.destinationCommitSha)invalid();const manifest:PromotionManifest={schemaVersion:1,deliveryId,actorLogin:root.actorLogin as string,development:{repository:repository(development.repository),branch:branch(development.branch)},destination:{repository:repository(destination.repository),branch:branch(destination.branch),baselineSha:sha(destination.baselineSha)},mappings:Object.freeze(mappings),...(root.pullRequest===undefined?{}:{pullRequest:pullRequest(root.pullRequest)}),phase:root.phase as PromotionManifest["phase"]};if(manifest.mappings[0]!.destinationParentSha!==manifest.destination.baselineSha)invalid();const objectLength=manifest.destination.baselineSha.length,objectIds=manifest.mappings.flatMap(item=>[item.developmentSha,item.destinationParentSha,item.destinationCommitSha,item.destinationTreeSha,item.projectedProductTreeSha,item.evidence.productSha,item.evidence.ledgerSha,item.evidence.reviewedLedgerSha]);if(objectIds.some(objectId=>objectId.length!==objectLength))invalid();if(manifest.pullRequest){if(manifest.pullRequest.headRef!==manifest.destination.branch||manifest.pullRequest.baseRef!==manifest.destination.repository.defaultBranch||manifest.pullRequest.headSha!==manifest.mappings.at(-1)!.destinationCommitSha||manifest.pullRequest.headSha.length!==objectLength||manifest.pullRequest.repository.owner!==manifest.destination.repository.owner||manifest.pullRequest.repository.name!==manifest.destination.repository.name)invalid();}if(manifest.phase==="awaiting-human-merge"&&manifest.pullRequest?.state!=="open"||new Set(["finalizing","complete"]).has(manifest.phase)&&manifest.pullRequest?.state!=="merged")invalid();return freeze(manifest);}catch(error){if(error instanceof PromotionError)throw error;invalid();}}

export function validatePromotionJournal(value:unknown):PromotionJournal{try{const root=record(value,["schemaVersion","deliveryId","entries"]);if(root.schemaVersion!==1||!Array.isArray(root.entries))invalid();const deliveryId=stableDeliveryId(root.deliveryId),entries=root.entries.map((entry,index)=>journalEntry(entry,index+1));if(new Set(entries.map(entry=>entry.idempotencyKey)).size!==entries.length)invalid();return freeze({schemaVersion:1,deliveryId,entries:Object.freeze(entries)});}catch(error){if(error instanceof PromotionError)throw error;invalid();}}

export function appendJournalEntry(journal:PromotionJournal,entry:Omit<PromotionJournalEntry,"sequence">):PromotionJournal{const current=validatePromotionJournal(journal);if(current.entries.some(item=>item.idempotencyKey===entry.idempotencyKey))return current;return validatePromotionJournal({...current,entries:[...current.entries,{...entry,sequence:current.entries.length+1}]});}

function mapping(value:unknown,revision:number):PromotionMapping{const root=record(value,["revision","developmentSha","destinationParentSha","destinationCommitSha","destinationTreeSha","projectedProductTreeSha","policyDigest","projectionDigest","evidence","promotedAt"]);if(root.revision!==revision||!date(root.promotedAt))invalid();const evidence=evidencePin(root.evidence),developmentSha=sha(root.developmentSha);if(evidence.productSha!==developmentSha)invalid();const mapping:PromotionMapping={revision,developmentSha,destinationParentSha:sha(root.destinationParentSha),destinationCommitSha:sha(root.destinationCommitSha),destinationTreeSha:sha(root.destinationTreeSha),projectedProductTreeSha:sha(root.projectedProductTreeSha),policyDigest:digest(root.policyDigest),projectionDigest:digest(root.projectionDigest),evidence,promotedAt:root.promotedAt as string};if(mapping.destinationTreeSha!==mapping.projectedProductTreeSha)invalid();return freeze(mapping);}
function evidencePin(value:unknown):PromotionEvidencePin{const root=record(value,["productSha","ledgerSha","manifestDigest","acceptanceDigest","reviewId","reviewRequestDigest","reviewResultDigest","reviewedLedgerSha","reviewerBundleDigest","evaluatedAt"]);if(!text(root.reviewId)||!date(root.evaluatedAt))invalid();return freeze({productSha:sha(root.productSha),ledgerSha:sha(root.ledgerSha),manifestDigest:digest(root.manifestDigest),acceptanceDigest:digest(root.acceptanceDigest),reviewId:root.reviewId as string,reviewRequestDigest:digest(root.reviewRequestDigest),reviewResultDigest:digest(root.reviewResultDigest),reviewedLedgerSha:sha(root.reviewedLedgerSha),reviewerBundleDigest:digest(root.reviewerBundleDigest),evaluatedAt:root.evaluatedAt as string});}
function pullRequest(value:unknown):DestinationPullRequest{const root=record(value,["id","number","url","marker","repository","headRepository","baseRepository","headRef","baseRef","headSha","state","isCrossRepository","mergeCommitSha"],["mergeCommitSha"]);if(!text(root.id)||!Number.isSafeInteger(root.number)||(root.number as number)<=0||!safeUrl(root.url)||!text(root.marker)||!text(root.headRef)||!text(root.baseRef)||!new Set(["open","closed","merged"]).has(String(root.state))||root.isCrossRepository!==false)invalid();const state=root.state as DestinationPullRequest["state"],merge=root.mergeCommitSha===undefined?undefined:sha(root.mergeCommitSha);if(state==="merged"?!merge:merge!==undefined)invalid();return freeze({id:root.id as string,number:root.number as number,url:root.url as string,marker:root.marker as string,repository:repoIdentity(root.repository),headRepository:repoIdentity(root.headRepository),baseRepository:repoIdentity(root.baseRepository),headRef:branch(root.headRef),baseRef:branch(root.baseRef),headSha:sha(root.headSha),state,isCrossRepository:false,...(merge?{mergeCommitSha:merge}:{})});}
function journalEntry(value:unknown,sequence:number):PromotionJournalEntry{const root=record(value,["sequence","step","idempotencyKey","observedSha","providerId","completedAt"],["observedSha","providerId"]);if(root.sequence!==sequence||!STEPS.has(root.step as PromotionJournalStep)||!text(root.idempotencyKey)||!date(root.completedAt)||(root.observedSha===undefined&&root.providerId===undefined))invalid();return freeze({sequence,step:root.step as PromotionJournalStep,idempotencyKey:root.idempotencyKey as string,...(root.observedSha===undefined?{}:{observedSha:sha(root.observedSha)}),...(root.providerId===undefined?{}:{providerId:nonempty(root.providerId)}),completedAt:root.completedAt as string});}
function repository(value:unknown){const root=record(value,["owner","name","remote","defaultBranch"]),remote=record(root.remote,["name","url"]);return freeze({owner:nonempty(root.owner),name:nonempty(root.name),remote:{name:nonempty(remote.name),url:githubUrl(remote.url)},defaultBranch:branch(root.defaultBranch)});}
function repoIdentity(value:unknown):Readonly<{owner:string;name:string}>{const root=record(value,["owner","name"]);return freeze({owner:nonempty(root.owner),name:nonempty(root.name)});}
function record(value:unknown,keys:readonly string[],optional:readonly string[]=[]):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)invalid();const out:Record<string,unknown>={};for(const key of Reflect.ownKeys(value)){if(typeof key!=="string"||!keys.includes(key))invalid();const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor||!descriptor.enumerable||!("value" in descriptor))invalid();out[key]=descriptor.value;}if(keys.some(key=>!optional.includes(key)&&!(key in out)))invalid();return out;}
function branch(value:unknown):string{const result=nonempty(value);if(!/^[A-Za-z0-9][A-Za-z0-9._/-]{0,255}$/.test(result)||result.includes("//")||result.endsWith("/")||result.split("/").some(part=>part==="."||part===".."))invalid();return result;}
function sha(value:unknown):string{if(typeof value!=="string"||!(/^[a-f0-9]{40}$/.test(value)||/^[a-f0-9]{64}$/.test(value)))invalid();return value;}
function digest(value:unknown):string{if(typeof value!=="string"||!/^[a-f0-9]{64}$/.test(value))invalid();return value;}
function githubUrl(value:unknown):string{const result=nonempty(value);let url:URL;try{url=new URL(result);}catch{invalid();}if(url.protocol!=="https:"||url.hostname!=="github.com"||url.username||url.password||url.search||url.hash||!/^\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+(?:\.git)?$/.test(url.pathname))invalid();return result;}
function safeUrl(value:unknown):value is string{if(typeof value!=="string")return false;try{const url=new URL(value);return url.protocol==="https:"&&url.hostname==="github.com"&&!url.username&&!url.password;}catch{return false;}}
function nonempty(value:unknown):string{if(!text(value)||value!==value.trim())invalid();return value;}
function text(value:unknown):value is string{return typeof value==="string"&&value.trim()!==""&&value.length<=4096;}
function date(value:unknown):value is string{return typeof value==="string"&&new Date(value).toISOString()===value;}
function invalid():never{throw new PromotionError("invalid-state","Promotion state is not a canonical version 1 document.");}
function freeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){for(const child of Object.values(value as Record<string,unknown>))freeze(child);Object.freeze(value);}return value;}
