import type { TrustedAcceptanceGate, TrustedAcceptanceReceipt } from "../acceptance/gate.js";
import type { DeliveryResolver } from "../delivery/resolver.js";
import type { MutationLockService } from "../locking/mutation-lock.js";
import type { BoundProfileAuthority, BoundProfileAuthorityResolver } from "../profile/bound-authority.js";
import { profileFingerprint } from "../profile/fingerprint.js";
import { requireProfileAuthorization, sameTopology, type ProfileReader } from "../profile/policy.js";
import { classifyProfilePath, PathPolicyError } from "../policy/path-classifier.js";
import { PromotionError } from "./errors.js";
import type { StagedPromotionGit, StagedPromotionSession } from "./git.js";
import { PromotionLedger } from "./manifest.js";
import { createPayloadPlan } from "./payload.js";
import { destinationDossier, type StagedProviderAuthority, type StagedProviderSession } from "./provider.js";
import { evidencePin, type GitTreeEntry, type PromotionManifest, type PromotionMapping, type PromotionStatus } from "./types.js";

export type TrustedStagedPromotionDependencies=Readonly<{
  repositoryPath:string;authority:BoundProfileAuthorityResolver;profiles:ProfileReader;deliveries:Pick<DeliveryResolver,"resolve">;
  evidence:TrustedAcceptanceGate;git:StagedPromotionGit;provider:StagedProviderAuthority;ledger:PromotionLedger;
  locks:MutationLockService;lockPath(commonDirectory:string):string;now?:()=>Date;
}>;
export interface TrustedStagedPromotionOperation {promoteInitial(input:Readonly<{deliveryId:string}>):Promise<PromotionStatus>;appendRevision(input:Readonly<{deliveryId:string}>):Promise<PromotionStatus>;}

export function createTrustedStagedPromotionOperation(raw:TrustedStagedPromotionDependencies):TrustedStagedPromotionOperation{const dependencies=construction(raw),operation=new StagedPromotionService(dependencies),trusted:TrustedStagedPromotionOperation={promoteInitial:(input:Readonly<{deliveryId:string}>)=>operation.run(input,"initial"),appendRevision:(input:Readonly<{deliveryId:string}>)=>operation.run(input,"revision")};return Object.freeze(trusted);}

class StagedPromotionService {
  constructor(private readonly dependencies:TrustedStagedPromotionDependencies){}
  async run(input:Readonly<{deliveryId:string}>,kind:"initial"|"revision"):Promise<PromotionStatus>{const deliveryId=selection(input),pre=await this.dependencies.authority.resolve(this.dependencies.repositoryPath,"promote"),lock=await this.dependencies.locks.acquire(this.dependencies.lockPath(pre.commonDirectory),pre.commonDirectory,"promote");try{
    const scope=await this.scope(deliveryId,pre),receipt=await this.receipt(scope),checkpoint=await this.dependencies.ledger.read(deliveryId),existing=checkpoint.manifest;this.requireKind(kind,existing,receipt.productSha);
    const last=existing?.mappings.at(-1),resuming=last?.developmentSha===receipt.productSha,destinationBranch=`shipyard/${deliveryId}`,stage=await this.dependencies.git.stage({repositoryPath:scope.worktreePath,actorLogin:scope.authority.actorLogin,developmentBranch:scope.branch,expectedSourceSha:receipt.productSha,...(last?{...(resuming&&existing!.mappings.length>1?{expectedPreviousSourceSha:existing!.mappings.at(-2)!.developmentSha}:{expectedPreviousSourceSha:last.developmentSha}),expectedDestinationParentSha:resuming?last.destinationParentSha:last.destinationCommitSha}:{}),destination:scope.authority.topology.destination,destinationBranch});
    try{return await this.promote(kind,scope,receipt,stage,existing,destinationBranch);}finally{await stage.release();}
  }finally{await lock.release();}}

  private async promote(kind:"initial"|"revision",scope:Scope,receipt:TrustedAcceptanceReceipt,stage:StagedPromotionSession,existing:PromotionManifest|undefined,destinationBranch:string):Promise<PromotionStatus>{const observation=stage.observation,last=existing?.mappings.at(-1),resuming=last?.developmentSha===receipt.productSha,parent=resuming?last.destinationParentSha:last?.destinationCommitSha??observation.destinationMainSha,parentEntries=last?observation.recordedDestinationParentEntries:observation.destinationMainEntries;if(receipt.productSha!==observation.sourceSha||!parentEntries)throw changed();if(existing&&observation.destinationMainSha!==existing.destination.baselineSha)throw new PromotionError("git-observation-changed","Destination main changed during an active staged delivery; human reconciliation is required.");if(last&&(!observation.destinationBranchHeadSha||resuming&&observation.destinationBranchHeadSha!==last.destinationCommitSha))throw changed();
    const classification={source:this.classify(scope.profile,observation.sourceEntries),destination:this.classify(scope.profile,parentEntries)},plan=createPayloadPlan({sourceSha:receipt.productSha,parentDestinationSha:parent,sourceEntries:observation.sourceEntries,destinationEntries:parentEntries,classification});
    if(last?.developmentSha===receipt.productSha){if(last.policyDigest!==plan.policyDigest||last.projectionDigest!==plan.projectionDigest||last.destinationTreeSha!==last.projectedProductTreeSha)throw new PromotionError("checkpoint-conflict","Existing exact-SHA promotion mapping no longer verifies against current policy.");return this.ensureProvider(scope,existing!,last,destinationBranch,false);}
    await this.revalidate(scope,receipt);const revision=(last?.revision??0)+1,publication=await stage.publish(plan,{deliveryId:scope.deliveryId,revision,destinationBranch,...(last?{expectedRemoteHead:last.destinationCommitSha}:{})});if(publication.destinationParentSha!==parent||publication.sourceSha!==receipt.productSha||publication.destinationTreeSha.length!==receipt.productSha.length)throw changed();
    const mapping:PromotionMapping=freeze({revision,developmentSha:receipt.productSha,destinationParentSha:parent,destinationCommitSha:publication.destinationCommitSha,destinationTreeSha:publication.destinationTreeSha,projectedProductTreeSha:publication.destinationTreeSha,policyDigest:plan.policyDigest,projectionDigest:plan.projectionDigest,evidence:evidencePin(receipt),promotedAt:this.now()}),manifest:PromotionManifest=existing?freeze({...existing,mappings:Object.freeze([...existing.mappings,mapping]),phase:"promoting",pullRequest:existing.pullRequest?freeze({...existing.pullRequest,headSha:mapping.destinationCommitSha,state:"open" as const,mergeCommitSha:undefined}):undefined}):freeze({schemaVersion:1,deliveryId:scope.deliveryId,actorLogin:scope.authority.actorLogin,development:{repository:scope.authority.topology.development,branch:scope.branch},destination:{repository:scope.authority.topology.destination,branch:destinationBranch,baselineSha:observation.destinationMainSha},mappings:Object.freeze([mapping]),phase:"promoting"});
    await this.dependencies.ledger.writeManifest(await this.dependencies.ledger.read(scope.deliveryId),manifest);await this.journal(scope.deliveryId,"destination-branch-published",`branch:${mapping.destinationCommitSha}`,mapping.destinationCommitSha);return this.ensureProvider(scope,manifest,mapping,destinationBranch,kind==="revision");}

  private async ensureProvider(scope:Scope,manifest:PromotionManifest,mapping:PromotionMapping,destinationBranch:string,revision:boolean):Promise<PromotionStatus>{await this.revalidate(scope,mapping.evidence);const session=await this.dependencies.provider.open({actorLogin:scope.authority.actorLogin,development:scope.authority.topology.development,destination:scope.authority.topology.destination}),dossier=destinationDossier(scope.deliveryId,manifest.mappings);let pull=manifest.pullRequest;
    if(!pull){pull=await session.reconcileDestinationPullRequest({deliveryId:scope.deliveryId,branch:destinationBranch,base:scope.authority.topology.destination.defaultBranch,headSha:mapping.destinationCommitSha,title:`Deliver ${scope.deliveryId}`,dossier});await this.journal(scope.deliveryId,"destination-pr-created",`destination-pr:${pull.id}`,undefined,pull.id);}else{pull=await session.updateDestinationDossier({pullRequest:pull,headSha:mapping.destinationCommitSha,dossier});if(revision)await this.journal(scope.deliveryId,"destination-pr-updated",`destination-pr-head:${mapping.destinationCommitSha}`,mapping.destinationCommitSha,pull.id);}
    const durable:PromotionManifest=freeze({...manifest,pullRequest:pull,phase:"awaiting-human-merge"});await this.dependencies.ledger.writeManifest(await this.dependencies.ledger.read(scope.deliveryId),durable);return status(durable);}

  private async scope(deliveryId:string,expected:BoundProfileAuthority):Promise<Scope>{const resolved=await this.dependencies.deliveries.resolve({repositoryPath:this.dependencies.repositoryPath,deliveryId}),authority=await this.dependencies.authority.resolve(resolved.workspace.worktreePath,"promote"),profile=await this.dependencies.profiles.read(authority.profileName);if(authority.topology.kind!=="staged-pair"||authority.commonDirectory!==expected.commonDirectory||resolved.binding.commonDirectory!==authority.commonDirectory||resolved.binding.profileFingerprint!==authority.profileFingerprint||!sameTopology(resolved.binding.topology,authority.topology)||profile.name!==authority.profileName||profile.actor.login!==authority.actorLogin||profileFingerprint(profile)!==authority.profileFingerprint||!sameTopology(profile.topology,authority.topology))throw new PromotionError("authority-changed","Binding, delivery, profile, actor, or staged-pair topology changed.");try{requireProfileAuthorization(profile,"promote");}catch{throw new PromotionError("authority-changed","Profile no longer authorizes promotion.");}const stagedAuthority=authority as BoundProfileAuthority&{topology:Extract<BoundProfileAuthority["topology"],{kind:"staged-pair"}>};return freeze({deliveryId,worktreePath:resolved.workspace.worktreePath,branch:resolved.workspace.branch,authority:stagedAuthority,profile});}
  private async receipt(scope:Scope):Promise<TrustedAcceptanceReceipt>{const receipt=await this.dependencies.evidence.evaluateReceipt();if(!receipt.decision.promotionEligible||receipt.deliveryId!==scope.deliveryId||receipt.actorLogin!==scope.authority.actorLogin)throw new PromotionError("evidence-stale","Complete current exact-SHA acceptance and independent review are required.");return receipt;}
  private async revalidate(scope:Scope,expected:TrustedAcceptanceReceipt|PromotionMapping["evidence"],skipReceipt=false):Promise<void>{const current=await this.dependencies.authority.resolve(scope.worktreePath,"promote"),profile=await this.dependencies.profiles.read(current.profileName);if(current.profileName!==scope.authority.profileName||current.commonDirectory!==scope.authority.commonDirectory||current.profileFingerprint!==scope.authority.profileFingerprint||current.actorLogin!==scope.authority.actorLogin||!sameTopology(current.topology,scope.authority.topology)||profileFingerprint(profile)!==scope.authority.profileFingerprint)throw new PromotionError("authority-changed","Promotion authority changed before mutation.");if(!skipReceipt){const receipt=await this.receipt(scope);if(receipt.productSha!==expected.productSha||receipt.manifestDigest!==expected.manifestDigest||receipt.acceptanceDigest!==expected.acceptanceDigest||receipt.reviewId!==expected.reviewId||receipt.reviewRequestDigest!==expected.reviewRequestDigest||receipt.reviewResultDigest!==expected.reviewResultDigest||receipt.reviewedLedgerSha!==expected.reviewedLedgerSha||receipt.reviewerBundleDigest!==expected.reviewerBundleDigest)throw new PromotionError("evidence-stale","Exact-SHA evidence changed before mutation.");}}
  private classify(profile:Scope["profile"],entries:readonly GitTreeEntry[]):ReadonlyMap<string,import("../contracts/types.js").PathOwner>{const values=new Map<string,import("../contracts/types.js").PathOwner>();try{for(const entry of entries)values.set(entry.path,classifyProfilePath(profile,entry.path));return values;}catch(error){if(error instanceof PathPolicyError)throw new PromotionError("path-policy",error.message);throw error;}}
  private requireKind(kind:"initial"|"revision",manifest:PromotionManifest|undefined,sourceSha:string):void{if(kind==="initial"&&manifest!==undefined&&manifest.mappings.at(-1)?.developmentSha!==sourceSha)throw new PromotionError("invalid-state","Initial promotion cannot append or replace an active revision history; use appendRevision.");if(kind==="revision"&&!manifest?.pullRequest)throw new PromotionError("invalid-state","A revision requires an existing destination PR checkpoint.");}
  private async journal(deliveryId:string,step:import("./types.js").PromotionJournalStep,key:string,observedSha?:string,providerId?:string):Promise<void>{const current=await this.dependencies.ledger.read(deliveryId);await this.dependencies.ledger.append(current,{step,idempotencyKey:key,...(observedSha?{observedSha}:{}),...(providerId?{providerId}:{}),completedAt:this.now()});}
  private now():string{const value=(this.dependencies.now??(()=>new Date()))();if(!(value instanceof Date)||!Number.isFinite(value.getTime()))throw new PromotionError("invalid-state","Trusted promotion clock is unavailable.");return value.toISOString();}
}

type Scope=Readonly<{deliveryId:string;worktreePath:string;branch:string;authority:BoundProfileAuthority&{topology:Extract<BoundProfileAuthority["topology"],{kind:"staged-pair"}>};profile:Awaited<ReturnType<ProfileReader["read"]>>}>;
function selection(value:unknown):string{try{if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).join(",")!=="deliveryId")throw new Error();const id=(value as {deliveryId?:unknown}).deliveryId;if(typeof id!=="string"||!/^[a-z0-9][a-z0-9._-]{0,63}$/.test(id)||id.includes(".."))throw new Error();return id;}catch{throw new PromotionError("invalid-state","Promotion accepts only one stable delivery ID.");}}
function construction(value:unknown):TrustedStagedPromotionDependencies{const keys=["repositoryPath","authority","profiles","deliveries","evidence","git","provider","ledger","locks","lockPath","now"],optional=["now"];if(!value||typeof value!=="object"||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)throw new PromotionError("invalid-state","Trusted promotion dependencies are invalid.");const out:Record<string,unknown>={};for(const key of Reflect.ownKeys(value)){if(typeof key!=="string"||!keys.includes(key))throw new PromotionError("invalid-state","Trusted promotion dependencies are invalid.");const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor||!("value" in descriptor))throw new PromotionError("invalid-state","Trusted promotion dependencies are invalid.");out[key]=descriptor.value;}if(keys.some(key=>!optional.includes(key)&&!(key in out))||typeof out.repositoryPath!=="string"||!out.repositoryPath.trim())throw new PromotionError("invalid-state","Trusted promotion dependencies are invalid.");return out as TrustedStagedPromotionDependencies;}
function status(manifest:PromotionManifest):PromotionStatus{const mapping=manifest.mappings.at(-1)!;return freeze({phase:manifest.phase,deliveryId:manifest.deliveryId,developmentSha:mapping.developmentSha,destinationSha:mapping.destinationCommitSha,destinationBranch:manifest.destination.branch,...(manifest.pullRequest?{destinationPullRequest:{number:manifest.pullRequest.number,url:manifest.pullRequest.url,state:manifest.pullRequest.state}}:{}),blockers:Object.freeze([]),nextSafeAction:"Wait for human/team merge, or append a newly accepted and reviewed revision."});}
function changed():PromotionError{return new PromotionError("git-observation-changed","Source or destination Git state changed before promotion.");}
function freeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){for(const child of Object.values(value as Record<string,unknown>))freeze(child);Object.freeze(value);}return value;}
