import { randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import { mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { isAbsolute, join } from "node:path";
import { canonicalJson, validateReviewRequest, validateReviewResult } from "../evidence/schema.js";
import type { ReviewRequest } from "../evidence/types.js";
import { ReviewError } from "../review/errors.js";
import type { EphemeralProcessRunner, IndependentReviewAdapter, ReviewDispatch } from "../review/types.js";
const LIMIT=1_000_000;
export const nodeEphemeralProcessRunner:EphemeralProcessRunner={run(input){return new Promise((resolve,reject)=>{let child;try{child=spawn(input.executable,[...input.args],{cwd:input.cwd,env:input.env,stdio:["pipe","pipe","pipe"]});}catch{return reject(new Error("spawn-failed"));}let stdout="",stderr="",stdoutBytes=0,stderrBytes=0,timedOut=false,oversize=false,settled=false;const kill=()=>child.kill("SIGKILL");const add=(which:"stdout"|"stderr",chunk:Buffer)=>{const bytes=chunk.byteLength;if(which==="stdout"){stdoutBytes+=bytes;if(stdoutBytes>LIMIT){oversize=true;return kill();}stdout+=chunk.toString("utf8");}else{stderrBytes+=bytes;if(stderrBytes>LIMIT){oversize=true;return kill();}stderr+=chunk.toString("utf8");}};const timer=setTimeout(()=>{timedOut=true;kill();},input.timeoutMs);child.stdout.on("data",b=>add("stdout",b));child.stderr.on("data",b=>add("stderr",b));child.on("error",()=>{if(!settled){settled=true;clearTimeout(timer);reject(new Error("process-failed"));}});child.on("close",code=>{if(!settled){settled=true;clearTimeout(timer);resolve({stdout,stderr,processId:child.pid??0,sessionId:input.env.SHIPYARD_REVIEW_SESSION??"",exitCode:code??undefined,timedOut,oversize});}});child.stdin.on("error",()=>kill());child.stdin.end(input.stdin);});}};
export type CodexReviewConfig=Readonly<{executable:string;runtimePath:string;codeHome:string;model:string;profile:string;commandVersion:string;timeoutMs?:number}>;
const outputSchema={type:"object",additionalProperties:false,required:["reviewId","productSha","reviewer","startedAt","finishedAt","findings","successful"],properties:{reviewId:{type:"string"},productSha:{type:"string"},reviewer:{type:"string"},startedAt:{type:"string"},finishedAt:{type:"string"},successful:{type:"boolean"},findings:{type:"array",items:{type:"object",additionalProperties:false,required:["id","severity","disposition","evidenceRefs","recordedAt"],properties:{id:{type:"string"},severity:{enum:["critical","high","medium","low"]},disposition:{enum:["accepted","rejected","informational","resolved"]},evidenceRefs:{type:"array",minItems:1,items:{type:"string"}},recordedAt:{type:"string"}}}}}} as const;
export class CodexReviewAdapter implements IndependentReviewAdapter {
  private readonly config:CodexReviewConfig;
  constructor(rawConfig:CodexReviewConfig,private readonly runner:EphemeralProcessRunner=nodeEphemeralProcessRunner){this.config=JSON.parse(canonicalJson(rawConfig));for(const key of ["executable","runtimePath","codeHome","model","profile","commandVersion"] as const)if(typeof this.config[key]!=="string"||this.config[key].trim()==="")throw new ReviewError("review-process-failed","Codex review configuration is invalid.");if(!isAbsolute(this.config.executable)||!isAbsolute(this.config.codeHome))throw new ReviewError("review-process-failed","Codex executable and home must be absolute.");}
  async review(rawDispatch:ReviewDispatch,rawRequest:ReviewRequest){const dispatch=JSON.parse(canonicalJson(rawDispatch)) as ReviewDispatch,request=validateReviewRequest(rawRequest);if(dispatch.host!=="codex"||dispatch.role!=="reviewer"||request.reviewerEnvelopePath!==dispatch.reviewerEnvelopePath||!isAbsolute(dispatch.repoRoot))throw new ReviewError("review-role-mismatch","Codex accepts one sealed trusted reviewer dispatch.");if(this.runner===nodeEphemeralProcessRunner){try{if(!(await stat(this.config.executable)).isFile())throw new Error();if(!(await stat(this.config.codeHome)).isDirectory())throw new Error();}catch{throw new ReviewError("review-process-failed","Codex executable or isolated home is unavailable.");}}
    const sessionId=randomUUID(),dir=await mkdtemp(join(tmpdir(),"shipyard-review-"));try{const resultPath=join(dir,"result.json"),schemaPath=join(dir,"result.schema.json");await writeFile(schemaPath,JSON.stringify(outputSchema));const args=["exec","--ephemeral","--ignore-user-config","--ignore-rules","--sandbox","read-only","-C",dispatch.repoRoot,"--model",this.config.model,"--profile",this.config.profile,"--output-schema",schemaPath,"-o",resultPath,"-"];const env={PATH:this.config.runtimePath,CODEX_HOME:this.config.codeHome,SHIPYARD_REVIEW_SESSION:sessionId,SHIPYARD_REVIEW_SESSION_DIR:dir};const stdin=`Review exact product SHA: ${request.productSha}. Reviewer envelope only: ${dispatch.reviewerEnvelopePath}. Review request only: ${dispatch.reviewRequestPath}. Return only the required review result.`;let run;try{run=await this.runner.run({executable:this.config.executable,args,env,stdin,cwd:dispatch.repoRoot,timeoutMs:this.config.timeoutMs??30_000});}catch{throw new ReviewError("review-process-failed","Independent reviewer could not be started.");}if(run.oversize)throw new ReviewError("review-process-failed","Independent reviewer exceeded output bounds.");if(run.timedOut)throw new ReviewError("review-process-timeout","Independent reviewer exceeded its runtime bound.");if(run.exitCode!==0)throw new ReviewError("review-process-failed","Independent reviewer exited unsuccessfully.");if(run.reused||!run.processId||!run.sessionId)throw new ReviewError("review-process-reused","Reviewer process must be new.");let parsed;try{parsed=JSON.parse(await readFile(resultPath,"utf8"));}catch{throw new ReviewError("review-invalid-result","Reviewer result is missing or malformed.");}const result=validateReviewResult({schemaVersion:1,...parsed,process:{processId:run.processId,sessionId:run.sessionId,fresh:true}});if(result.reviewId!==request.reviewId||result.productSha!==request.productSha)throw new ReviewError("review-invalid-result","Reviewer result does not match the sealed request.");return Object.freeze({result,attestation:Object.freeze({processId:run.processId,sessionId:run.sessionId,fresh:true as const,commandVersion:this.config.commandVersion})});}finally{await rm(dir,{recursive:true,force:true});}}
}
