import type { GitHubApiCredentialResolver, GitHubRestClient, GitHubRestClientFactory } from "../github/types.js";
import { stableShipyardMarker } from "../github/markers.js";
import { PromotionError } from "../promotion/errors.js";
import { destinationMarker, type DevelopmentRecordObservation, type StagedProviderAuthority, type StagedProviderSession } from "../promotion/provider.js";
import type { DestinationPullRequest } from "../promotion/types.js";
import type { RepositoryRef } from "../contracts/types.js";

type RecordShape={id?:unknown;node_id?:unknown;number?:unknown;html_url?:unknown;body?:unknown;state?:unknown;merged?:unknown;merged_at?:unknown;merge_commit_sha?:unknown;head?:{ref?:unknown;sha?:unknown;repo?:unknown};base?:{ref?:unknown;repo?:unknown};pull_request?:unknown};
const MAX_PAGES=100;

/** One verified actor yields only destination-PR and exact development-close capabilities; there is no destination-issue method. */
export class GitHubStagedProviderAuthority implements StagedProviderAuthority {
  constructor(private readonly credentials:GitHubApiCredentialResolver,private readonly clients:GitHubRestClientFactory){}
  async open(request:Readonly<{actorLogin:string;development:RepositoryRef;destination:RepositoryRef}>):Promise<StagedProviderSession>{const client=await this.verified(request.actorLogin),development=repository(request.development),destination=repository(request.destination);const session:StagedProviderSession={
    reconcileDestinationPullRequest:async input=>{const marker=destinationMarker(input.deliveryId),found=await discover(client,destination,"pulls",marker,input.resumeNumber);if(found){const observed=destinationPull(found,destination,marker);requireDestination(observed,input.branch,input.base,input.headSha);return observed;}await assertViewer(client,request.actorLogin);const created=await client.request<RecordShape>({method:"POST",path:`${base(destination)}/pulls`,body:{title:input.title,body:withMarker(safeDossier(input.dossier,development),marker),head:input.branch,base:input.base}}),confirmed=await discover(client,destination,"pulls",marker,number(created));if(!confirmed||id(confirmed)!==id(created))throw new PromotionError("unsafe-recovery","Destination PR creation was not uniquely confirmed; inspect marked PRs before retrying.");const observed=destinationPull(confirmed,destination,marker);requireDestination(observed,input.branch,input.base,input.headSha);return observed;},
    updateDestinationDossier:async input=>{let current=destinationPull(await exactPull(client,destination,input.pullRequest.number),destination,input.pullRequest.marker);requireSamePr(current,input.pullRequest);requireDestination(current,input.pullRequest.headRef,input.pullRequest.baseRef,input.headSha);await assertViewer(client,request.actorLogin);await client.request({method:"PATCH",path:`${base(destination)}/pulls/${current.number}`,body:{body:withMarker(safeDossier(input.dossier,development),current.marker)}});current=destinationPull(await exactPull(client,destination,current.number),destination,current.marker);requireDestination(current,input.pullRequest.headRef,input.pullRequest.baseRef,input.headSha);return current;},
    observeDestinationPullRequest:async input=>destinationPull(await exactPull(client,destination,input.number),destination,input.marker),
    observeDevelopmentRecords:async deliveryId=>developmentRecords(await Promise.all([discover(client,development,"issues",stableShipyardMarker(deliveryId),undefined,true),discover(client,development,"pulls",stableShipyardMarker(deliveryId))])),
    closeDevelopmentPullRequest:async expected=>{const current=developmentPull(await exactPull(client,development,expected.number));if(!sameDevelopmentPull(current,expected)||current.merged)throw new PromotionError("provider-mismatch","Development PR changed or was merged; refusing close.");if(current.state==="closed")return;await assertViewer(client,request.actorLogin);await client.request({method:"PATCH",path:`${base(development)}/pulls/${expected.number}`,body:{state:"closed"}});const after=developmentPull(await exactPull(client,development,expected.number));if(after.state!=="closed"||after.merged)throw new PromotionError("unsafe-recovery","Development PR close was not safely confirmed.");},
    closeDevelopmentIssue:async expected=>{const current=issue(await exactIssue(client,development,expected.number));if(!sameIssue(current,expected))throw new PromotionError("provider-mismatch","Development issue changed; refusing close.");if(current.state==="closed")return;await assertViewer(client,request.actorLogin);await client.request({method:"PATCH",path:`${base(development)}/issues/${expected.number}`,body:{state:"closed"}});const after=issue(await exactIssue(client,development,expected.number));if(after.state!=="closed")throw new PromotionError("unsafe-recovery","Development issue close was not safely confirmed.");},
  };return Object.freeze(session);}
  private async verified(actor:string):Promise<GitHubRestClient>{let credential;try{credential=await this.credentials.resolve();}catch{throw new PromotionError("authority-changed","GitHub credential resolution failed safely.");}if(!credential?.authorizationValue)throw new PromotionError("authority-changed","GitHub credentials are required.");let client:GitHubRestClient;try{client=this.clients.forCredential(credential);}catch{throw new PromotionError("authority-changed","GitHub credential session could not be created.");}await assertViewer(client,actor);return client;}
}

async function assertViewer(client:GitHubRestClient,actor:string):Promise<void>{let viewer:{login?:unknown};try{viewer=await client.request({method:"GET",path:"/user"});}catch{throw new PromotionError("authority-changed","GitHub actor verification failed safely.");}if(viewer.login!==actor)throw new PromotionError("authority-changed","GitHub actor no longer matches the bound profile.");}
async function discover(client:GitHubRestClient,repo:RepositoryRef,kind:"issues"|"pulls",marker:string,resumeNumber?:number,issuesOnly=false):Promise<RecordShape|undefined>{let found:RecordShape|undefined,exhausted=false;for(let page=1;page<=MAX_PAGES;page++){const values=await client.request<unknown>({method:"GET",path:`${base(repo)}/${kind}?state=all&per_page=100&page=${page}`});if(!Array.isArray(values))throw new PromotionError("provider-mismatch","GitHub returned an invalid record listing.");for(const value of values){if(!shape(value)||issuesOnly&&"pull_request" in value||typeof value.body!=="string"||!value.body.split(/\r?\n/).includes(marker))continue;if(found)throw new PromotionError("provider-mismatch","Multiple marked provider records prevent safe resume.");found=value;}if(values.length<100){exhausted=true;break;}}if(!exhausted)throw new PromotionError("provider-mismatch","Provider discovery exceeded its safe page limit.");if(resumeNumber!==undefined&&(!found||number(found)!==resumeNumber))throw new PromotionError("provider-mismatch","Checkpointed provider record is missing or replaced.");return found;}
async function exactPull(client:GitHubRestClient,repo:RepositoryRef,number:number):Promise<RecordShape>{const value=await client.request<unknown>({method:"GET",path:`${base(repo)}/pulls/${number}`});if(!shape(value))throw new PromotionError("provider-mismatch","GitHub returned an invalid pull request.");return value;}
async function exactIssue(client:GitHubRestClient,repo:RepositoryRef,number:number):Promise<RecordShape>{const value=await client.request<unknown>({method:"GET",path:`${base(repo)}/issues/${number}`});if(!shape(value)||"pull_request" in value)throw new PromotionError("provider-mismatch","GitHub returned an invalid issue.");return value;}
function destinationPull(value:RecordShape,repo:RepositoryRef,marker:string):DestinationPullRequest{const state=value.merged===true||value.merged_at?"merged":value.state==="open"?"open":value.state==="closed"?"closed":undefined,merge=state==="merged"?sha(value.merge_commit_sha):undefined,headRepo=repoIdentity(value.head?.repo),baseRepo=repoIdentity(value.base?.repo);if(!state||!markerLine(value.body,marker)||!id(value)||!number(value)||typeof value.html_url!=="string"||typeof value.head?.ref!=="string"||typeof value.base?.ref!=="string")throw new PromotionError("provider-mismatch","Destination PR is incomplete or lost its marker.");const observed:DestinationPullRequest={id:id(value)!,number:number(value)!,url:value.html_url,marker,repository:{owner:repo.owner,name:repo.name},headRepository:headRepo,baseRepository:baseRepo,headRef:value.head.ref,baseRef:value.base.ref,headSha:sha(value.head.sha),state,isCrossRepository:false,...(merge?{mergeCommitSha:merge}:{})};if(!sameRepo(headRepo,repo)||!sameRepo(baseRepo,repo))throw new PromotionError("provider-mismatch","Destination PR is forked or cross-repository.");return freeze(observed);}
function requireDestination(value:DestinationPullRequest,head:string,baseRef:string,shaValue:string):void{if(value.state!=="open"||value.headRef!==head||value.baseRef!==baseRef||value.headSha!==shaValue||value.isCrossRepository!==false)throw new PromotionError("provider-mismatch","Destination PR head, base, repository, or state changed.");}
function requireSamePr(left:DestinationPullRequest,right:DestinationPullRequest):void{if(left.id!==right.id||left.number!==right.number||left.marker!==right.marker||left.url!==right.url)throw new PromotionError("provider-mismatch","Destination PR identity changed.");}
function developmentRecords(values:readonly [RecordShape|undefined,RecordShape|undefined]):DevelopmentRecordObservation{if(!values[0]||!values[1])throw new PromotionError("provider-mismatch","Development issue or PR is missing.");return freeze({issue:issue(values[0]),pullRequest:developmentPull(values[1])});}
function developmentPull(value:RecordShape):DevelopmentRecordObservation["pullRequest"]{if(!id(value)||!number(value)||typeof value.html_url!=="string"||typeof value.head?.ref!=="string")throw new PromotionError("provider-mismatch","Development PR is invalid.");return freeze({id:id(value)!,number:number(value)!,url:value.html_url,state:value.state==="open"?"open":"closed",merged:value.merged===true||Boolean(value.merged_at),headRef:value.head.ref,headSha:sha(value.head.sha)});}
function issue(value:RecordShape):DevelopmentRecordObservation["issue"]{if(!id(value)||!number(value)||typeof value.html_url!=="string")throw new PromotionError("provider-mismatch","Development issue is invalid.");return freeze({id:id(value)!,number:number(value)!,url:value.html_url,state:value.state==="open"?"open":"closed"});}
function sameDevelopmentPull(a:DevelopmentRecordObservation["pullRequest"],b:DevelopmentRecordObservation["pullRequest"]):boolean{return a.id===b.id&&a.number===b.number&&a.url===b.url&&a.headRef===b.headRef&&a.headSha===b.headSha;}
function sameIssue(a:DevelopmentRecordObservation["issue"],b:DevelopmentRecordObservation["issue"]):boolean{return a.id===b.id&&a.number===b.number&&a.url===b.url;}
function safeDossier(value:string,development:RepositoryRef):string{if(typeof value!=="string"||value.length>60_000||value.includes(`${development.owner}/${development.name}`)||value.includes(development.remote.url)||/shipyard-ledger|refs\/shipyard|authorization\s*:|https?:\/\/[^\s/@]+@/i.test(value))throw new PromotionError("unsafe-payload","Destination dossier contains development-only or credential material.");return value;}
function repository(value:RepositoryRef):RepositoryRef{if(!value.owner||!value.name||!value.defaultBranch)return fail();return freeze(structuredClone(value));}
function repoIdentity(value:unknown):Readonly<{owner:string;name:string}>{if(!value||typeof value!=="object")return fail();const repo=value as {name?:unknown;full_name?:unknown;owner?:{login?:unknown}};if(typeof repo.name!=="string"||typeof repo.owner?.login!=="string"||repo.full_name!==`${repo.owner.login}/${repo.name}`)return fail();return freeze({owner:repo.owner.login,name:repo.name});}
function sameRepo(value:Readonly<{owner:string;name:string}>,repo:RepositoryRef):boolean{return value.owner===repo.owner&&value.name===repo.name;}
function base(repo:RepositoryRef):string{return `/repos/${repo.owner}/${repo.name}`;}
function withMarker(body:string,marker:string):string{return `${body.trim()}\n\n${marker}`;}
function markerLine(value:unknown,marker:string):boolean{return typeof value==="string"&&value.split(/\r?\n/).includes(marker);}
function id(value:RecordShape):string|undefined{return typeof value.node_id==="string"&&value.node_id?value.node_id:typeof value.id==="string"&&value.id?value.id:typeof value.id==="number"&&Number.isFinite(value.id)?String(value.id):undefined;}
function number(value:RecordShape):number|undefined{return typeof value.number==="number"&&Number.isSafeInteger(value.number)&&value.number>0?value.number:undefined;}
function sha(value:unknown):string{if(typeof value!=="string"||!(/^[a-f0-9]{40}$/.test(value)||/^[a-f0-9]{64}$/.test(value)))return fail();return value;}
function shape(value:unknown):value is RecordShape{return typeof value==="object"&&value!==null&&!Array.isArray(value);}
function fail():never{throw new PromotionError("provider-mismatch","Provider record does not match exact staged-pair authority.");}
function freeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){for(const child of Object.values(value as Record<string,unknown>))freeze(child);Object.freeze(value);}return value;}
