import { execFile } from "node:child_process";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import type { RepositoryRef } from "../contracts/types.js";
import type { UnderLockMainSyncGit } from "../sync/git.js";
import type { GitTransportCredentialResolver } from "../sync/transport.js";
import { requireSourceFreePublication } from "../sync/transport.js";
import { DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES, DEFAULT_GIT_COMMAND_TIMEOUT_MS, DEFAULT_NODE_GIT_EXECUTABLE, type GitTransportCommandRunner, nodeGitTransportCommandRunner, sanitizedGitEnvironment } from "./git-transport.js";
import { FinalizationError } from "../finalization/errors.js";
import type { FinalizationGitAuthority, FinalizationGitSession } from "../finalization/git.js";
import type { MergeObservation } from "../finalization/types.js";

const exec=promisify(execFile);
export class NodeFinalizationGitAuthority implements FinalizationGitAuthority {
  constructor(private readonly credentials:GitTransportCredentialResolver,private readonly mainSync:UnderLockMainSyncGit,private readonly runner:GitTransportCommandRunner=nodeGitTransportCommandRunner,private readonly executable=DEFAULT_NODE_GIT_EXECUTABLE){}
  async open(request:Readonly<{repositoryPath:string;actorLogin:string;development:RepositoryRef;destination:RepositoryRef;developmentBranch:string;destinationBranch:string;expectedMergeSha:string;expectedFinalDevelopmentSha:string;expectedFinalDestinationSha:string}>):Promise<FinalizationGitSession>{if(!request.actorLogin.trim()||!fullSha(request.expectedMergeSha)||!fullSha(request.expectedFinalDevelopmentSha)||!fullSha(request.expectedFinalDestinationSha)||!safeBranch(request.developmentBranch)||!safeBranch(request.destinationBranch))throw invalid();const credential=await this.credentials.resolve(request.actorLogin);if(!credential?.token.trim()||credential.verifiedActorLogin!==request.actorLogin)throw new FinalizationError("authority-changed","A verified command-scoped Git credential is required.");const format=await this.local(request.repositoryPath,["rev-parse","--show-object-format"]);if(format!=="sha1"&&format!=="sha256")throw invalid();const directory=await mkdtemp(join(tmpdir(),"shipyard-finalize-"));let released=false;try{
    await this.local(directory,["init","--bare",`--object-format=${format}`,directory],false);await this.local(directory,["remote","add","development",request.development.remote.url]);await this.local(directory,["remote","add","destination",request.destination.remote.url]);
    const destinationMain=await this.fetchHead(directory,"destination",request.destination.defaultBranch,"refs/shipyard/destination-main",credential.token),destinationBranch=await this.fetchOptionalHead(directory,"destination",request.destinationBranch,"refs/shipyard/destination-branch",credential.token),developmentMain=await this.fetchHead(directory,"development",request.development.defaultBranch,"refs/shipyard/development-main",credential.token),developmentBranch=await this.fetchOptionalHead(directory,"development",request.developmentBranch,"refs/shipyard/development-branch",credential.token),localDevelopmentMain=await this.local(request.repositoryPath,["rev-parse",`refs/heads/${request.development.defaultBranch}`]);
    if(destinationBranch!==undefined&&destinationBranch!==request.expectedFinalDestinationSha)throw new FinalizationError("merge-unverified","Destination delivery branch no longer names the reviewed final commit.");const merge=await this.local(directory,["rev-parse","--verify",`${request.expectedMergeSha}^{commit}`]);if(merge!==request.expectedMergeSha)throw new FinalizationError("merge-unverified","Expected destination merge commit is unavailable.");const ancestry=(await this.local(directory,["rev-list","--parents","-n","1",merge])).split(" "),mergeTree=await this.local(directory,["rev-parse",`${merge}^{tree}`]),observation:MergeObservation=freeze({destinationMainSha:destinationMain,developmentMainSha:localDevelopmentMain,...(destinationBranch?{destinationBranchSha:destinationBranch}:{}),...(developmentBranch?{developmentBranchSha:developmentBranch}:{}),mergeCommitSha:merge,mergeCommitTreeSha:mergeTree,mergeParents:Object.freeze(ancestry.slice(1)),mergeCommitAncestorOfMain:await this.ancestor(directory,merge,destinationMain),finalDestinationCommitAncestorOfMerge:await this.ancestor(directory,request.expectedFinalDestinationSha,merge)});if(developmentMain!==localDevelopmentMain&&localDevelopmentMain!==destinationMain)throw new FinalizationError("unsafe-recovery","Local and remote development main disagree outside the resumable final target.");
    const session:FinalizationGitSession={observation,
      ensureReviewedTag:async(tag,target,message)=>{this.active(released);if(!safeTag(tag)||target!==request.expectedFinalDevelopmentSha||!message.trim())throw invalid();const destinationTag=await this.remoteRef(directory,"destination",`refs/tags/${tag}`,credential.token);if(destinationTag)throw new FinalizationError("unsafe-recovery","Reviewed tag exists in the destination repository.");const remote=await this.remoteRef(directory,"development",`refs/tags/${tag}`,credential.token);if(remote){await this.network(directory,["fetch","--no-tags","development",`refs/tags/${tag}:refs/shipyard/reviewed-tag`],credential.token);const peeled=await this.local(directory,["rev-parse","refs/shipyard/reviewed-tag^{}"]),kind=await this.local(directory,["cat-file","-t","refs/shipyard/reviewed-tag"]);if(peeled!==target||kind!=="tag")throw new FinalizationError("unsafe-recovery","Existing reviewed tag does not match the exact final product SHA.");return remote;}await this.local(directory,["fetch","--no-tags",request.repositoryPath,`${target}:refs/shipyard/reviewed-product`]);await this.local(directory,["tag","-a",tag,target,"-m",message],true,{GIT_AUTHOR_NAME:"shipyard",GIT_AUTHOR_EMAIL:"shipyard@local",GIT_COMMITTER_NAME:"shipyard",GIT_COMMITTER_EMAIL:"shipyard@local"});const object=await this.local(directory,["rev-parse",`refs/tags/${tag}`]),refspec=`refs/tags/${tag}:refs/tags/${tag}`;requireSourceFreePublication({refspecs:[refspec],payload:{tag,target}});await this.network(directory,["push","development",refspec],credential.token);if(await this.remoteRef(directory,"development",`refs/tags/${tag}`,credential.token)!==object)throw new FinalizationError("unsafe-recovery","Reviewed tag publication was not confirmed.");return object;},
      synchronizeDevelopmentMain:async(expectedBefore,target)=>{this.active(released);if(target!==observation.destinationMainSha||developmentMain!==expectedBefore&&developmentMain!==target)throw new FinalizationError("unsafe-recovery","Development-main synchronization pins changed.");await this.local(request.repositoryPath,["fetch","--no-tags","--no-write-fetch-head",directory,target]);await this.mainSync.fastForwardMainUnderLock(request.repositoryPath,{developmentBranch:request.development.defaultBranch,expectedDevelopmentSha:expectedBefore,targetDestinationSha:target,objectFormat:format});const remote=await this.remoteRef(directory,"development",`refs/heads/${request.development.defaultBranch}`,credential.token);if(remote!==expectedBefore&&remote!==target)throw new FinalizationError("unsafe-recovery","Remote development main changed before synchronization.");if(remote!==target){const publicationRef="refs/heads/shipyard-main-publication",refspec=`${publicationRef}:refs/heads/${request.development.defaultBranch}`;await this.local(directory,["update-ref",publicationRef,target]);requireSourceFreePublication({refspecs:[refspec]});await this.network(directory,["push","development",refspec],credential.token);}if(await this.remoteRef(directory,"development",`refs/heads/${request.development.defaultBranch}`,credential.token)!==target||await this.local(request.repositoryPath,["rev-parse",`refs/heads/${request.development.defaultBranch}`])!==target)throw new FinalizationError("unsafe-recovery","Development main did not synchronize exactly.");},
      deleteDevelopmentBranch:(branch,expected)=>this.deleteBranch(directory,"development",branch,expected,credential.token),
      deleteDestinationBranch:(branch,expected)=>this.deleteBranch(directory,"destination",branch,expected,credential.token),
      publishLedger:async seal=>{this.active(released);if(!fullSha(seal))throw invalid();await this.local(directory,["fetch","--no-tags",request.repositoryPath,`${seal}:refs/shipyard/final-ledger-seal`]);const parent=await this.local(directory,["rev-parse",`${seal}^`]),remote=await this.remoteRef(directory,"development","refs/heads/shipyard-ledger",credential.token);if(remote!==parent&&remote!==seal)throw new FinalizationError("unsafe-recovery","Remote ledger changed before final seal publication.");if(remote!==seal){const refspec=`${seal}:refs/heads/shipyard-ledger`;await this.network(directory,["push","development",refspec],credential.token);}if(await this.remoteRef(directory,"development","refs/heads/shipyard-ledger",credential.token)!==seal)throw new FinalizationError("unsafe-recovery","Final ledger seal publication was not confirmed.");},
      release:async()=>{if(released)return;released=true;await rm(directory,{recursive:true,force:true});},
    };return Object.freeze(session);
  }catch(error){await rm(directory,{recursive:true,force:true});if(error instanceof FinalizationError)throw error;throw new FinalizationError("unsafe-recovery","Finalization Git staging failed safely.");}}
  private async deleteBranch(directory:string,remote:string,branch:string,expected:string,token:string):Promise<void>{if(!safeBranch(branch)||!fullSha(expected))throw invalid();const current=await this.remoteRef(directory,remote,`refs/heads/${branch}`,token);if(current===undefined)return;if(current!==expected)throw new FinalizationError("unsafe-recovery",`Remote ${remote} delivery branch changed before deletion.`);const refspec=`:refs/heads/${branch}`;requireSourceFreePublication({refspecs:[refspec]});await this.network(directory,["push",`--force-with-lease=refs/heads/${branch}:${expected}`,remote,refspec],token);if(await this.remoteRef(directory,remote,`refs/heads/${branch}`,token)!==undefined)throw new FinalizationError("unsafe-recovery",`Remote ${remote} delivery branch deletion was not confirmed.`);}
  private active(released:boolean):void{if(released)throw new FinalizationError("unsafe-recovery","Finalization Git session was already released.");}
  private async fetchHead(directory:string,remote:string,branch:string,ref:string,token:string):Promise<string>{const head=await this.remoteRef(directory,remote,`refs/heads/${branch}`,token);if(!head)throw new FinalizationError("merge-unverified",`Required ${remote} branch is unavailable.`);await this.network(directory,["fetch","--no-tags",remote,`refs/heads/${branch}:${ref}`],token);return head;}
  private async fetchOptionalHead(directory:string,remote:string,branch:string,ref:string,token:string):Promise<string|undefined>{const head=await this.remoteRef(directory,remote,`refs/heads/${branch}`,token);if(head)await this.network(directory,["fetch","--no-tags",remote,`refs/heads/${branch}:${ref}`],token);return head;}
  private async remoteRef(directory:string,remote:string,ref:string,token:string):Promise<string|undefined>{const output=await this.network(directory,["ls-remote",remote,ref],token),lines=output.split("\n").filter(Boolean);if(lines.length===0)return undefined;if(lines.length!==1)throw new FinalizationError("unsafe-recovery","Remote ref observation is ambiguous.");const fields=lines[0]!.split(/\s+/);if(fields[1]!==ref||!fullSha(fields[0]))throw new FinalizationError("unsafe-recovery","Remote ref observation is malformed.");return fields[0];}
  private async ancestor(repo:string,left:string,right:string):Promise<boolean>{try{await exec(this.executable,["-C",repo,"merge-base","--is-ancestor",left,right],{encoding:"utf8",env:sanitizedGitEnvironment(),timeout:DEFAULT_GIT_COMMAND_TIMEOUT_MS,maxBuffer:DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES,killSignal:"SIGKILL"});return true;}catch(error){if((error as {code?:unknown}).code===1)return false;throw new FinalizationError("merge-unverified","Git ancestry could not be verified.");}}
  private async network(stage:string,args:string[],token:string):Promise<string>{const result=await this.runner.run({executable:this.executable,argv:["-C",stage,...args],env:credentialEnvironment(token),timeoutMs:DEFAULT_GIT_COMMAND_TIMEOUT_MS,maxOutputBytes:DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES});if(result.exitCode!==0||Buffer.byteLength(result.stdout)+Buffer.byteLength(result.stderr)>DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES)throw new FinalizationError("unsafe-recovery","Authenticated finalization Git failed safely.");return result.stdout.trim();}
  private async local(repositoryPath:string,args:string[],includeC=true,extra:Readonly<Record<string,string>>={}):Promise<string>{try{return (await exec(this.executable,includeC?["-C",repositoryPath,...args]:args,{encoding:"utf8",env:sanitizedGitEnvironment(extra),timeout:DEFAULT_GIT_COMMAND_TIMEOUT_MS,maxBuffer:DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES,killSignal:"SIGKILL"})).stdout.trim();}catch{throw new FinalizationError("unsafe-recovery","Local finalization Git failed safely.");}}
}
function credentialEnvironment(token:string):Readonly<Record<string,string>>{return {GIT_CONFIG_COUNT:"3",GIT_CONFIG_KEY_0:"credential.helper",GIT_CONFIG_VALUE_0:"",GIT_CONFIG_KEY_1:"http.https://github.com/.extraheader",GIT_CONFIG_VALUE_1:"",GIT_CONFIG_KEY_2:"http.https://github.com/.extraheader",GIT_CONFIG_VALUE_2:`AUTHORIZATION: bearer ${token}`,GIT_TERMINAL_PROMPT:"0"};}
function fullSha(value:unknown):value is string{return typeof value==="string"&&(/^[a-f0-9]{40}$/.test(value)||/^[a-f0-9]{64}$/.test(value));}
function safeBranch(value:string):boolean{return /^[A-Za-z0-9][A-Za-z0-9._/-]{0,255}$/.test(value)&&!value.includes("//")&&!value.endsWith("/");}
function safeTag(value:string):boolean{return /^shipyard\/reviewed\/[a-z0-9][a-z0-9._-]{0,63}$/.test(value);}
function invalid():FinalizationError{return new FinalizationError("invalid-state","Finalization Git request is invalid.");}
function freeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){for(const child of Object.values(value as Record<string,unknown>))freeze(child);Object.freeze(value);}return value;}
