export type MattPlanningStep = "wayfinder" | "grill-with-docs" | "to-spec" | "to-tickets" | "diagnosing-bugs" | "grilling";
export type PlanningArtifactResult = Readonly<{ step: MattPlanningStep | "ccpm-prd" | "ccpm-vertical-tasks"; path: string; sha256: string }>;
export type MattPlanningEnvelope = Readonly<{ role: "planner"; recordId: string; repositoryPath: string; productSha: string; objectFormat: "sha1" | "sha256"; lane: "large" | "small" | "bug"; steps: readonly MattPlanningStep[]; requestText: string }>;
export interface MattSkillsPlanner { plan(envelope: MattPlanningEnvelope): Promise<Readonly<{ resumeCheckpoint: string; artifacts: readonly PlanningArtifactResult[] }>>; }

export function mattSteps(lane: MattPlanningEnvelope["lane"], disposition: "ready" | "needs-grilling" | "needs-wayfinding"): readonly MattPlanningStep[] { if (disposition === "needs-wayfinding") return Object.freeze(["wayfinder"]); if (disposition === "needs-grilling") return Object.freeze(["grilling"]); if (lane === "large") return Object.freeze(["wayfinder"]); if (lane === "small") return Object.freeze(["grill-with-docs", "to-spec"]); return Object.freeze(["diagnosing-bugs"]); }
export function assertMattEnvelope(value: unknown): MattPlanningEnvelope { const v = doc(value, ["lane", "objectFormat", "productSha", "recordId", "repositoryPath", "requestText", "role", "steps"]); if (v.role !== "planner" || !id(v.recordId, 128) || typeof v.repositoryPath !== "string" || !v.repositoryPath.startsWith("/") || v.repositoryPath.length > 4096 || (v.objectFormat !== "sha1" && v.objectFormat !== "sha256") || !sha(v.productSha, v.objectFormat) || typeof v.requestText !== "string" || v.requestText.length === 0 || v.requestText.length > 16384 || !Array.isArray(v.steps) || v.steps.length === 0 || v.steps.length > 4 || !["large", "small", "bug"].includes(v.lane as string) || v.steps.some(step => typeof step !== "string" || !["wayfinder", "grill-with-docs", "to-spec", "to-tickets", "diagnosing-bugs", "grilling"].includes(step))) throw new Error("Codex planning envelope is invalid."); return freeze(v as MattPlanningEnvelope); }
export function assertPlanningResult(value: unknown, expectedSteps: readonly string[], recordId: string): Readonly<{ resumeCheckpoint: string; artifacts: readonly PlanningArtifactResult[] }> { const v = doc(value, ["artifacts", "resumeCheckpoint"]); if (!id(v.resumeCheckpoint, 128) || !Array.isArray(v.artifacts) || v.artifacts.length !== expectedSteps.length) throw new Error("Codex planning returned an invalid result."); const paths = new Set<string>(); const artifacts = v.artifacts.map((raw, index) => { const item = doc(raw, ["path", "sha256", "step"]); if (item.step !== expectedSteps[index] || typeof item.path !== "string" || !safePath(item.path, recordId) || paths.has(item.path) || typeof item.sha256 !== "string" || !/^[a-f0-9]{64}$/.test(item.sha256)) throw new Error("Codex planning returned an invalid result."); paths.add(item.path); return freeze({ step: item.step as PlanningArtifactResult["step"], path: item.path, sha256: item.sha256 }); }); return freeze({ resumeCheckpoint: v.resumeCheckpoint as string, artifacts }); }
function safePath(path: string, recordId: string): boolean { return path.startsWith(`planning/${recordId}/artifacts/`) && path.length <= 512 && /^[A-Za-z0-9._/-]+$/.test(path) && !path.includes("..") && !path.includes("//") && !/(^|\/)(product|provider|ledger|metadata)(\/|$)/.test(path) && !path.endsWith("/"); }
function sha(value: unknown, format: "sha1" | "sha256"): value is string { return typeof value === "string" && (format === "sha1" ? /^[a-f0-9]{40}$/.test(value) : /^[a-f0-9]{64}$/.test(value)); } function id(value: unknown, max: number): value is string { return typeof value === "string" && value.length > 0 && value.length <= max && /^[A-Za-z0-9._-]+$/.test(value); }
/** Snapshot every nested value before any consumer may enumerate, coerce, or read it. */
export function snapshotPlanningDocument(value: unknown): unknown { try { return snapshot(value); } catch { throw new Error("Codex planning document is invalid."); } }
function doc(value: unknown, keys: readonly string[]): Record<string, unknown> { const root = snapshotPlanningDocument(value); if (!root || typeof root !== "object" || Array.isArray(root)) throw new Error("Codex planning document is invalid."); const record = root as Record<string, unknown>; const actual = Object.keys(record); if (actual.length !== keys.length || actual.some(key => !keys.includes(key)) || keys.some(key => !(key in record))) throw new Error("Codex planning document is invalid."); return record; }
function snapshot(value: unknown, seen = new Set<object>(), depth = 0): unknown { if (depth > 16) throw new Error(); if (value === null || typeof value === "string" || typeof value === "boolean" || typeof value === "number") return value; if (!value || typeof value !== "object" || seen.has(value)) throw new Error(); seen.add(value); const rawKeys = Reflect.ownKeys(value); if (rawKeys.some(key => typeof key !== "string")) throw new Error(); const keys = rawKeys as string[]; const descriptors = Object.getOwnPropertyDescriptors(value); if (Object.values(descriptors).some(descriptor => !("value" in descriptor))) throw new Error(); if (Array.isArray(value)) { const length = descriptors.length; if (!length || !("value" in length) || typeof length.value !== "number" || !Number.isSafeInteger(length.value) || length.value > 64 || keys.length !== length.value + 1) throw new Error(); const out: unknown[] = []; for (let i = 0; i < length.value; i++) { const descriptor = descriptors[String(i)]; if (!descriptor || !("value" in descriptor) || !descriptor.enumerable) throw new Error(); out.push(snapshot(descriptor.value, seen, depth + 1)); } seen.delete(value); return out; } if (Object.getPrototypeOf(value) !== Object.prototype || Object.values(descriptors).some(descriptor => !descriptor.enumerable) || keys.length > 32) throw new Error(); const out: Record<string, unknown> = {}; for (const key of keys.sort()) out[key] = snapshot(descriptors[key]!.value, seen, depth + 1); seen.delete(value); return out; }
function freeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as Record<string, unknown>)) freeze(child); Object.freeze(value); } return value; }
