import { execFile } from "node:child_process";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import type { RepositoryRef } from "../contracts/types.js";
import type { UnderLockMainSyncGit } from "../sync/git.js";
import type { GitTransportCredentialResolver } from "../sync/transport.js";
import { requireSourceFreePublication } from "../sync/transport.js";
import { DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES, DEFAULT_GIT_COMMAND_TIMEOUT_MS, DEFAULT_NODE_GIT_EXECUTABLE, type GitTransportCommandRunner, nodeGitTransportCommandRunner, sanitizedGitEnvironment } from "./git-transport.js";
import { SingleRepositoryError } from "../single-repository/errors.js";
import type { SingleRepositoryFinalizationGitAuthority, SingleRepositoryFinalizationGitSession, SingleRepositoryRecoveryGitSession } from "../single-repository/types.js";
import type { MergeObservation } from "../finalization/types.js";

const execute = promisify(execFile);

/** Isolated command-scoped one-repository finalization. Human merge is observed; there is no merge operation. */
export class NodeSingleRepositoryFinalizationGitAuthority implements SingleRepositoryFinalizationGitAuthority {
  constructor(private readonly credentials: GitTransportCredentialResolver, private readonly mainSync: UnderLockMainSyncGit, private readonly runner: GitTransportCommandRunner = nodeGitTransportCommandRunner, private readonly executable = DEFAULT_NODE_GIT_EXECUTABLE) {}

  async observeLedger(request: Readonly<{ actorLogin: string; repository: RepositoryRef }>): Promise<string | undefined> {
    if (!request.actorLogin.trim() || !exactGitHubUrl(request.repository.remote.url, request.repository.owner, request.repository.name)) throw invalid();
    const credential = await this.credentials.resolve(request.actorLogin); if (!credential?.token.trim() || credential.verifiedActorLogin !== request.actorLogin) throw new SingleRepositoryError("authority-changed", "A verified command-scoped Git credential is required.");
    const directory = await mkdtemp(join(tmpdir(), "shipyard-single-observe-"));
    try { await this.local(directory, ["init", "--bare", directory], false); await this.local(directory, ["remote", "add", "repository", request.repository.remote.url]); return await this.remoteRef(directory, "refs/heads/shipyard-ledger", credential.token); }
    catch (error) { if (error instanceof SingleRepositoryError) throw error; throw new SingleRepositoryError("unsafe-recovery", "Single-repository ledger observation failed safely."); }
    finally { await rm(directory, { recursive: true, force: true }); }
  }

  async observeFinalizationStatus(request: Readonly<{ repositoryPath: string; actorLogin: string; repository: RepositoryRef; deliveryBranch: string; mergeCommitSha: string }>): Promise<Readonly<{ ledgerSha?: string; deliveryBranchSha?: string; mainSha: string; mergeReachableFromMain: boolean }>> {
    if (!request.repositoryPath.trim() || !request.actorLogin.trim() || !exactGitHubUrl(request.repository.remote.url, request.repository.owner, request.repository.name) || !safeBranch(request.deliveryBranch) || !fullSha(request.mergeCommitSha)) throw invalid();
    const credential = await this.credentials.resolve(request.actorLogin); if (!credential?.token.trim() || credential.verifiedActorLogin !== request.actorLogin) throw new SingleRepositoryError("authority-changed", "A verified command-scoped Git credential is required.");
    const objectFormat = await this.local(request.repositoryPath, ["rev-parse", "--show-object-format"]); if (objectFormat !== "sha1" && objectFormat !== "sha256") throw invalid();
    const directory = await mkdtemp(join(tmpdir(), "shipyard-single-status-"));
    try {
      await this.local(directory, ["init", "--bare", `--object-format=${objectFormat}`, directory], false); await this.local(directory, ["remote", "add", "repository", request.repository.remote.url]);
      const mainSha = await this.fetchHead(directory, request.repository.defaultBranch, "refs/shipyard/repository-main", credential.token), branch = await this.remoteRef(directory, `refs/heads/${request.deliveryBranch}`, credential.token), ledger = await this.remoteRef(directory, "refs/heads/shipyard-ledger", credential.token);
      return freeze({ ...(ledger ? { ledgerSha: ledger } : {}), ...(branch ? { deliveryBranchSha: branch } : {}), mainSha, mergeReachableFromMain: await this.ancestor(directory, request.mergeCommitSha, mainSha) });
    } catch (error) { if (error instanceof SingleRepositoryError) throw error; throw new SingleRepositoryError("unsafe-recovery", "Single-repository finalization status observation failed safely."); }
    finally { await rm(directory, { recursive: true, force: true }); }
  }

  async openRecovery(request: Readonly<{ repositoryPath: string; actorLogin: string; repository: RepositoryRef; deliveryBranch: string; expectedMergeSha: string; expectedFinalHeadSha: string }>): Promise<SingleRepositoryRecoveryGitSession> {
    if (!request.repositoryPath.trim() || !request.actorLogin.trim() || !exactGitHubUrl(request.repository.remote.url, request.repository.owner, request.repository.name) || !safeBranch(request.deliveryBranch) || !fullSha(request.expectedMergeSha) || !fullSha(request.expectedFinalHeadSha)) throw invalid();
    const credential = await this.credentials.resolve(request.actorLogin); if (!credential?.token.trim() || credential.verifiedActorLogin !== request.actorLogin) throw new SingleRepositoryError("authority-changed", "A verified command-scoped Git credential is required.");
    const objectFormat = await this.local(request.repositoryPath, ["rev-parse", "--show-object-format"]); if (objectFormat !== "sha1" && objectFormat !== "sha256") throw invalid();
    const directory = await mkdtemp(join(tmpdir(), "shipyard-single-recovery-")); let released = false;
    try {
      await this.local(directory, ["init", "--bare", `--object-format=${objectFormat}`, directory], false); await this.local(directory, ["remote", "add", "repository", request.repository.remote.url]);
      const active = () => this.active(released);
      return Object.freeze({
        observeDeliveryBranchSha: async (branch: string) => { active(); if (branch !== request.deliveryBranch) throw invalid(); return this.remoteRef(directory, `refs/heads/${branch}`, credential.token); },
        deleteDeliveryBranch: async (branch: string, expected: string) => { active(); if (branch !== request.deliveryBranch || expected !== request.expectedFinalHeadSha) throw invalid(); const current = await this.remoteRef(directory, `refs/heads/${branch}`, credential.token); if (current === undefined) return; if (current !== expected) throw new SingleRepositoryError("unsafe-recovery", "Remote delivery branch changed before deletion."); const refspec = `:refs/heads/${branch}`; requireSourceFreePublication({ refspecs: [refspec] }); await this.network(directory, ["push", `--force-with-lease=refs/heads/${branch}:${expected}`, "repository", refspec], credential.token); if (await this.remoteRef(directory, `refs/heads/${branch}`, credential.token) !== undefined) throw new SingleRepositoryError("unsafe-recovery", "Remote delivery branch deletion was not confirmed."); },
        publishLedger: async (seal: string) => { active(); if (!fullSha(seal)) throw invalid(); await this.local(directory, ["fetch", "--no-tags", request.repositoryPath, `${seal}:refs/shipyard/final-ledger-seal`]); const parent = await this.local(directory, ["rev-parse", `${seal}^`]), remote = await this.remoteRef(directory, "refs/heads/shipyard-ledger", credential.token); if (remote !== parent && remote !== seal) throw new SingleRepositoryError("unsafe-recovery", "Remote ledger changed before final seal publication."); if (remote !== seal) await this.network(directory, ["push", "repository", `${seal}:refs/heads/shipyard-ledger`], credential.token); if (await this.remoteRef(directory, "refs/heads/shipyard-ledger", credential.token) !== seal) throw new SingleRepositoryError("unsafe-recovery", "Final ledger seal publication was not confirmed."); },
        release: async () => { if (released) return; released = true; await rm(directory, { recursive: true, force: true }); },
      });
    } catch (error) { await rm(directory, { recursive: true, force: true }); if (error instanceof SingleRepositoryError) throw error; throw new SingleRepositoryError("unsafe-recovery", "Single-repository recovery Git failed safely."); }
  }

  async open(request: Readonly<{ repositoryPath: string; actorLogin: string; repository: RepositoryRef; deliveryBranch: string; expectedMergeSha: string; expectedFinalHeadSha: string }>): Promise<SingleRepositoryFinalizationGitSession> {
    if (!request.repositoryPath.trim() || !request.actorLogin.trim() || !exactGitHubUrl(request.repository.remote.url, request.repository.owner, request.repository.name) || !safeBranch(request.deliveryBranch) || !fullSha(request.expectedMergeSha) || !fullSha(request.expectedFinalHeadSha)) throw invalid();
    const credential = await this.credentials.resolve(request.actorLogin); if (!credential?.token.trim() || credential.verifiedActorLogin !== request.actorLogin) throw new SingleRepositoryError("authority-changed", "A verified command-scoped Git credential is required.");
    const objectFormat = await this.local(request.repositoryPath, ["rev-parse", "--show-object-format"]); if (objectFormat !== "sha1" && objectFormat !== "sha256") throw invalid();
    const directory = await mkdtemp(join(tmpdir(), "shipyard-single-finalize-")); let released = false;
    try {
      await this.local(directory, ["init", "--bare", `--object-format=${objectFormat}`, directory], false); await this.local(directory, ["remote", "add", "repository", request.repository.remote.url]);
      const mainSha = await this.fetchHead(directory, request.repository.defaultBranch, "refs/shipyard/repository-main", credential.token), branchSha = await this.fetchOptionalHead(directory, request.deliveryBranch, "refs/shipyard/delivery-branch", credential.token), localMain = await this.local(request.repositoryPath, ["rev-parse", `refs/heads/${request.repository.defaultBranch}`]);
      if (branchSha !== undefined && branchSha !== request.expectedFinalHeadSha) throw new SingleRepositoryError("unsafe-recovery", "Remote delivery branch changed before single-repository finalization.");
      if (branchSha === undefined) { const tag = reviewedTagForBranch(request.deliveryBranch), remoteTag = await this.remoteRef(directory, `refs/tags/${tag}`, credential.token); if (remoteTag) await this.network(directory, ["fetch", "--no-tags", "repository", `refs/tags/${tag}:refs/shipyard/reviewed-tag`], credential.token); }
      const mergeSha = await this.local(directory, ["rev-parse", "--verify", `${request.expectedMergeSha}^{commit}`]); if (mergeSha !== request.expectedMergeSha) throw new SingleRepositoryError("human-merge-required", "Expected human merge commit is unavailable.");
      const parents = (await this.local(directory, ["rev-list", "--parents", "-n", "1", mergeSha])).split(" "), tree = await this.local(directory, ["rev-parse", `${mergeSha}^{tree}`]);
      const observation: MergeObservation = freeze({ destinationMainSha: mainSha, developmentMainSha: localMain, ...(branchSha ? { destinationBranchSha: branchSha, developmentBranchSha: branchSha } : {}), mergeCommitSha: mergeSha, mergeCommitTreeSha: tree, mergeParents: Object.freeze(parents.slice(1)), mergeCommitAncestorOfMain: await this.ancestor(directory, mergeSha, mainSha), finalDestinationCommitAncestorOfMerge: await this.ancestor(directory, request.expectedFinalHeadSha, mergeSha) });
      const session: SingleRepositoryFinalizationGitSession = {
        observation,
        ensureReviewedTag: async (tag, target, message) => { this.active(released); if (!safeTag(tag) || target !== request.expectedFinalHeadSha || !message.trim()) throw invalid(); const current = await this.remoteRef(directory, `refs/tags/${tag}`, credential.token); if (current) { await this.network(directory, ["fetch", "--no-tags", "repository", `refs/tags/${tag}:refs/shipyard/reviewed-tag`], credential.token); const peeled = await this.local(directory, ["rev-parse", "refs/shipyard/reviewed-tag^{}"]), kind = await this.local(directory, ["cat-file", "-t", "refs/shipyard/reviewed-tag"]); if (peeled !== target || kind !== "tag") throw new SingleRepositoryError("unsafe-recovery", "Existing reviewed tag does not match the certified head."); return current; } if (await this.remoteRef(directory, `refs/heads/${request.deliveryBranch}`, credential.token) !== target) throw new SingleRepositoryError("unsafe-recovery", "Certified delivery head is unavailable for reviewed tag creation."); await this.local(directory, ["tag", "-a", tag, target, "-m", message], true, { GIT_AUTHOR_NAME: "shipyard", GIT_AUTHOR_EMAIL: "shipyard@local", GIT_COMMITTER_NAME: "shipyard", GIT_COMMITTER_EMAIL: "shipyard@local" }); const object = await this.local(directory, ["rev-parse", `refs/tags/${tag}`]), refspec = `refs/tags/${tag}:refs/tags/${tag}`; requireSourceFreePublication({ refspecs: [refspec], payload: { tag, target } }); await this.network(directory, ["push", "repository", refspec], credential.token); if (await this.remoteRef(directory, `refs/tags/${tag}`, credential.token) !== object) throw new SingleRepositoryError("unsafe-recovery", "Reviewed tag publication was not confirmed."); return object; },
        synchronizeLocalMain: async (expectedBefore, target) => { this.active(released); const remoteMain = await this.remoteRef(directory, `refs/heads/${request.repository.defaultBranch}`, credential.token); if (target !== observation.destinationMainSha || remoteMain !== target || (localMain !== expectedBefore && localMain !== target)) throw new SingleRepositoryError("unsafe-recovery", "Main synchronization pins changed."); if (localMain !== target) { await this.local(request.repositoryPath, ["fetch", "--no-tags", "--no-write-fetch-head", directory, target]); await this.mainSync.fastForwardMainUnderLock(request.repositoryPath, { developmentBranch: request.repository.defaultBranch, expectedDevelopmentSha: expectedBefore, targetDestinationSha: target, objectFormat }); } if (await this.local(request.repositoryPath, ["rev-parse", `refs/heads/${request.repository.defaultBranch}`]) !== target) throw new SingleRepositoryError("unsafe-recovery", "Local main did not synchronize exactly to merged main."); },
        deleteDeliveryBranch: async (branch, expected) => { this.active(released); if (branch !== request.deliveryBranch || expected !== request.expectedFinalHeadSha) throw invalid(); const current = await this.remoteRef(directory, `refs/heads/${branch}`, credential.token); if (current === undefined) return; if (current !== expected) throw new SingleRepositoryError("unsafe-recovery", "Remote delivery branch changed before deletion."); const refspec = `:refs/heads/${branch}`; requireSourceFreePublication({ refspecs: [refspec] }); await this.network(directory, ["push", `--force-with-lease=refs/heads/${branch}:${expected}`, "repository", refspec], credential.token); if (await this.remoteRef(directory, `refs/heads/${branch}`, credential.token) !== undefined) throw new SingleRepositoryError("unsafe-recovery", "Remote delivery branch deletion was not confirmed."); },
        observeDeliveryBranchSha: async (branch) => { this.active(released); if (branch !== request.deliveryBranch) throw invalid(); return this.remoteRef(directory, `refs/heads/${branch}`, credential.token); },
        observeMainSha: async () => { this.active(released); const current = await this.remoteRef(directory, `refs/heads/${request.repository.defaultBranch}`, credential.token); if (!current) throw new SingleRepositoryError("unsafe-recovery", "Repository main disappeared during finalization."); return current; },
        publishLedger: async (seal) => { this.active(released); if (!fullSha(seal)) throw invalid(); await this.local(directory, ["fetch", "--no-tags", request.repositoryPath, `${seal}:refs/shipyard/final-ledger-seal`]); const parent = await this.local(directory, ["rev-parse", `${seal}^`]), remote = await this.remoteRef(directory, "refs/heads/shipyard-ledger", credential.token); if (remote !== parent && remote !== seal) throw new SingleRepositoryError("unsafe-recovery", "Remote ledger changed before final seal publication."); if (remote !== seal) { const refspec = `${seal}:refs/heads/shipyard-ledger`; await this.network(directory, ["push", "repository", refspec], credential.token); } if (await this.remoteRef(directory, "refs/heads/shipyard-ledger", credential.token) !== seal) throw new SingleRepositoryError("unsafe-recovery", "Final ledger seal publication was not confirmed."); },
        release: async () => { if (released) return; released = true; await rm(directory, { recursive: true, force: true }); },
      };
      return Object.freeze(session);
    } catch (error) { await rm(directory, { recursive: true, force: true }); if (error instanceof SingleRepositoryError) throw error; throw new SingleRepositoryError("unsafe-recovery", "Single-repository finalization Git failed safely."); }
  }

  private active(released: boolean): void { if (released) throw new SingleRepositoryError("unsafe-recovery", "Finalization Git session was already released."); }
  private async fetchHead(directory: string, branch: string, ref: string, token: string): Promise<string> { const head = await this.remoteRef(directory, `refs/heads/${branch}`, token); if (!head) throw new SingleRepositoryError("human-merge-required", "Required repository main is unavailable."); await this.network(directory, ["fetch", "--no-tags", "repository", `refs/heads/${branch}:${ref}`], token); return head; }
  private async fetchOptionalHead(directory: string, branch: string, ref: string, token: string): Promise<string | undefined> { const head = await this.remoteRef(directory, `refs/heads/${branch}`, token); if (head) await this.network(directory, ["fetch", "--no-tags", "repository", `refs/heads/${branch}:${ref}`], token); return head; }
  private async remoteRef(directory: string, ref: string, token: string): Promise<string | undefined> { const output = await this.network(directory, ["ls-remote", "repository", ref], token), lines = output.split("\n").filter(Boolean); if (lines.length === 0) return undefined; if (lines.length !== 1) throw new SingleRepositoryError("unsafe-recovery", "Remote ref observation is ambiguous."); const fields = lines[0]!.split(/\s+/); if (fields[1] !== ref || !fullSha(fields[0])) throw new SingleRepositoryError("unsafe-recovery", "Remote ref observation is malformed."); return fields[0]; }
  private async ancestor(repositoryPath: string, left: string, right: string): Promise<boolean> { try { await execute(this.executable, ["-C", repositoryPath, "merge-base", "--is-ancestor", left, right], { encoding: "utf8", env: sanitizedGitEnvironment(), timeout: DEFAULT_GIT_COMMAND_TIMEOUT_MS, maxBuffer: DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES, killSignal: "SIGKILL" }); return true; } catch (error) { if ((error as { code?: unknown }).code === 1 || (error as { code?: unknown }).code === 128) return false; throw new SingleRepositoryError("human-merge-required", "Git ancestry could not be verified."); } }
  private async network(repositoryPath: string, argv: string[], token: string): Promise<string> { const result = await this.runner.run({ executable: this.executable, argv: ["-C", repositoryPath, ...argv], env: credentialEnvironment(token), timeoutMs: DEFAULT_GIT_COMMAND_TIMEOUT_MS, maxOutputBytes: DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES }); if (result.exitCode !== 0 || Buffer.byteLength(result.stdout) + Buffer.byteLength(result.stderr) > DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES) throw new SingleRepositoryError("unsafe-recovery", "Authenticated single-repository Git failed safely."); return result.stdout.trim(); }
  private async local(repositoryPath: string, args: string[], includeC = true, extra: Readonly<Record<string, string>> = {}): Promise<string> { try { return (await execute(this.executable, includeC ? ["-C", repositoryPath, ...args] : args, { encoding: "utf8", env: sanitizedGitEnvironment(extra), timeout: DEFAULT_GIT_COMMAND_TIMEOUT_MS, maxBuffer: DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES, killSignal: "SIGKILL" })).stdout.trim(); } catch { throw new SingleRepositoryError("unsafe-recovery", "Local single-repository Git failed safely."); } }
}

function reviewedTagForBranch(branch: string): string { const match = /^shipyard\/(.+)$/.exec(branch); if (!match) throw invalid(); return `shipyard/reviewed/${match[1]}`; }
function credentialEnvironment(token: string): Readonly<Record<string, string>> { return { GIT_CONFIG_COUNT: "3", GIT_CONFIG_KEY_0: "credential.helper", GIT_CONFIG_VALUE_0: "", GIT_CONFIG_KEY_1: "http.https://github.com/.extraheader", GIT_CONFIG_VALUE_1: "", GIT_CONFIG_KEY_2: "http.https://github.com/.extraheader", GIT_CONFIG_VALUE_2: `AUTHORIZATION: bearer ${token}`, GIT_TERMINAL_PROMPT: "0" }; }
function fullSha(value: unknown): value is string { return typeof value === "string" && (/^[a-f0-9]{40}$/.test(value) || /^[a-f0-9]{64}$/.test(value)); }
function safeBranch(value: string): boolean { return /^[A-Za-z0-9][A-Za-z0-9._/-]{0,255}$/.test(value) && !value.includes("//") && !value.endsWith("/") && !value.split("/").some((part) => part === "." || part === ".."); }
function safeTag(value: string): boolean { return /^shipyard\/reviewed\/[a-z0-9][a-z0-9._-]{0,63}$/.test(value); }
function exactGitHubUrl(value: string, owner: string, name: string): boolean { return value === `https://github.com/${owner}/${name}` || value === `https://github.com/${owner}/${name}.git`; }
function invalid(): SingleRepositoryError { return new SingleRepositoryError("invalid-state", "Single-repository finalization Git request is invalid."); }
function freeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as Record<string, unknown>)) freeze(child); Object.freeze(value); } return value; }
