import { execFile } from "node:child_process";
import { mkdir, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES, DEFAULT_GIT_COMMAND_TIMEOUT_MS, DEFAULT_NODE_GIT_EXECUTABLE, type GitTransportCommandRunner, nodeGitTransportCommandRunner, sanitizedGitEnvironment } from "./git-transport.js";
import type { GitTransportCredentialResolver } from "../sync/transport.js";
import { requireSourceFreePublication } from "../sync/transport.js";
import { PromotionError } from "../promotion/errors.js";
import type { StagedPromotionGit, StagedPromotionObservation, StagedPromotionSession, StagedPublicationReceipt } from "../promotion/git.js";
import { projectedEntries } from "../promotion/payload.js";
import type { GitObjectFormat } from "../ledger/types.js";
import type { GitTreeEntry, GitTreeMode, PayloadPlan } from "../promotion/types.js";

const exec=promisify(execFile),MAX_TREE_ENTRIES=100_000;

/** Isolated Git-native cargo builder. Destination credentials exist only in temporary bare-repository children. */
export class NodeStagedPromotionGit implements StagedPromotionGit {
  constructor(private readonly credentials:GitTransportCredentialResolver,private readonly runner:GitTransportCommandRunner=nodeGitTransportCommandRunner,private readonly executable=DEFAULT_NODE_GIT_EXECUTABLE){}
  async stage(request:Readonly<{repositoryPath:string;actorLogin:string;developmentBranch:string;expectedSourceSha:string;expectedPreviousSourceSha?:string;expectedDestinationParentSha?:string;sourceBaselineSha?:string;destination:{owner:string;name:string;remote:{name:string;url:string};defaultBranch:string};destinationBranch:string}>):Promise<StagedPromotionSession>{
    if(!request.actorLogin.trim()||!safeBranch(request.developmentBranch)||!safeBranch(request.destination.defaultBranch)||!safeBranch(request.destinationBranch)||!exactGitHubUrl(request.destination.remote.url,request.destination.owner,request.destination.name)||!fullSha(request.expectedSourceSha)||(request.expectedPreviousSourceSha!==undefined&&!fullSha(request.expectedPreviousSourceSha))||(request.expectedDestinationParentSha!==undefined&&!fullSha(request.expectedDestinationParentSha))||(request.sourceBaselineSha!==undefined&&!fullSha(request.sourceBaselineSha)))throw new PromotionError("authority-changed","Staged Git request is not exact bound authority.");
    const [dirty,branch,sourceSha,format]=await Promise.all([this.local(request.repositoryPath,["status","--porcelain"]),this.local(request.repositoryPath,["symbolic-ref","--short","HEAD"]),this.local(request.repositoryPath,["rev-parse","--verify","HEAD^{commit}"]),this.local(request.repositoryPath,["rev-parse","--show-object-format"])]);if(dirty!==""||branch!==request.developmentBranch||sourceSha!==request.expectedSourceSha||(format!=="sha1"&&format!=="sha256"))throw new PromotionError("git-observation-changed","Development worktree, branch, SHA, or object format changed before staging.");
    await this.rejectWritableDestinationRemote(request.repositoryPath,request.destination);
    const credential=await this.credentials.resolve(request.actorLogin);if(!credential?.token.trim()||credential.verifiedActorLogin!==request.actorLogin)throw new PromotionError("authority-changed","A command-scoped verified Git credential is required.");
    const directory=await mkdtemp(join(tmpdir(),"shipyard-promote-"));let released=false;
    try{
      await this.local(directory,["init","--bare",`--object-format=${format}`,directory],false);await this.local(directory,["remote","add","destination",request.destination.remote.url]);
      await this.local(directory,["fetch","--no-tags",request.repositoryPath,`${sourceSha}:refs/shipyard/development-product`]);
      if(request.expectedPreviousSourceSha){await this.local(directory,["fetch","--no-tags",request.repositoryPath,`${request.expectedPreviousSourceSha}:refs/shipyard/previous-development-product`]);if(!await this.ancestor(directory,request.expectedPreviousSourceSha,sourceSha))throw new PromotionError("git-observation-changed","Reviewed development revision is not a descendant of the previous reviewed source SHA.");}
      await this.network(directory,["fetch","--no-tags","destination",`refs/heads/${request.destination.defaultBranch}:refs/shipyard/destination-main`],credential.token);
      const remoteBranch=await this.remoteHead(directory,request.destinationBranch,credential.token);if(remoteBranch)await this.network(directory,["fetch","--no-tags","destination",`refs/heads/${request.destinationBranch}:refs/shipyard/destination-branch`],credential.token);
      const [sourceTreeSha,sourceEntries,destinationMainSha,destinationMainEntries]=await Promise.all([this.local(directory,["rev-parse","refs/shipyard/development-product^{tree}"]),this.tree(directory,"refs/shipyard/development-product",format as GitObjectFormat),this.local(directory,["rev-parse","refs/shipyard/destination-main"]),this.tree(directory,"refs/shipyard/destination-main",format as GitObjectFormat)]),sourceBaseline=request.sourceBaselineSha??destinationMainSha;if(await this.local(directory,["rev-parse","--verify",`${sourceBaseline}^{commit}`])!==sourceBaseline||!await this.ancestor(directory,sourceBaseline,sourceSha)||request.sourceBaselineSha!==undefined&&!await this.ancestor(directory,sourceBaseline,destinationMainSha))throw new PromotionError("git-observation-changed","Reviewed development SHA is not based on the required destination baseline.");
      if(request.expectedDestinationParentSha){if(!remoteBranch||!await this.ancestor(directory,request.expectedDestinationParentSha,remoteBranch))throw new PromotionError("git-observation-changed","Destination delivery branch no longer descends from its recorded head.");}
      const destinationBranchEntries=remoteBranch?await this.tree(directory,"refs/shipyard/destination-branch",format as GitObjectFormat):undefined,destinationBranchTreeSha=remoteBranch?await this.local(directory,["rev-parse","refs/shipyard/destination-branch^{tree}"]):undefined,recordedDestinationParentEntries=request.expectedDestinationParentSha?await this.tree(directory,request.expectedDestinationParentSha,format as GitObjectFormat):undefined;
      const observation:StagedPromotionObservation=freeze({objectFormat:format as GitObjectFormat,sourceSha,sourceTreeSha,sourceEntries,destinationMainSha,destinationMainEntries,...(remoteBranch?{destinationBranchHeadSha:remoteBranch,destinationBranchTreeSha,destinationBranchEntries}: {}),...(recordedDestinationParentEntries?{recordedDestinationParentEntries}:{})});
      const publish=async(plan:PayloadPlan,input:Readonly<{deliveryId:string;revision:number;destinationBranch:string;expectedRemoteHead?:string}>):Promise<StagedPublicationReceipt>=>{
        if(released||!stableId(input.deliveryId)||input.destinationBranch!==request.destinationBranch||input.revision<=0||plan.sourceSha!==observation.sourceSha||plan.parentDestinationSha!==(input.expectedRemoteHead??observation.destinationMainSha))throw new PromotionError("git-observation-changed","Prepared payload no longer matches staged Git authority.");
        const current=await this.remoteHead(directory,input.destinationBranch,credential.token);if(current!==input.expectedRemoteHead&&current!==observation.destinationBranchHeadSha)throw new PromotionError("git-observation-changed","Destination delivery branch changed before append-only publication.");
        const parent=input.expectedRemoteHead??observation.destinationMainSha,index=join(directory,`index-${input.revision}`),worktree=join(directory,"worktree");await mkdir(worktree,{recursive:true});
        const indexEnv={GIT_INDEX_FILE:index,GIT_WORK_TREE:worktree};await this.local(directory,["read-tree",parent],true,indexEnv);for(const path of plan.removedProductPaths)await this.local(directory,["update-index","--force-remove","--",path],true,indexEnv);for(const entry of plan.productEntries)await this.local(directory,["update-index","--add","--cacheinfo",`${entry.mode},${entry.objectId},${entry.path}`],true,indexEnv);
        const tree=await this.local(directory,["write-tree"],true,indexEnv),actual=await this.tree(directory,tree,format as GitObjectFormat),expected=projectedEntries(plan);if(!sameEntries(actual,expected))throw new PromotionError("unsafe-payload","Git-native destination tree does not equal the canonical product projection.");
        const sourceDate=await this.local(directory,["show","-s","--format=%aI",observation.sourceSha]),message=`Shipyard delivery ${input.deliveryId} revision ${String(input.revision).padStart(3,"0")}`,identity={GIT_AUTHOR_NAME:"shipyard",GIT_AUTHOR_EMAIL:"shipyard@local",GIT_COMMITTER_NAME:"shipyard",GIT_COMMITTER_EMAIL:"shipyard@local",GIT_AUTHOR_DATE:sourceDate,GIT_COMMITTER_DATE:sourceDate},commit=await this.local(directory,["commit-tree",tree,"-p",parent,"-m",message],true,identity);
        const rebuiltTree=await this.local(directory,["rev-parse",`${commit}^{tree}`]);if(rebuiltTree!==tree)throw new PromotionError("unsafe-payload","Destination commit changed the projected tree.");
        const before=await this.remoteHead(directory,input.destinationBranch,credential.token);if(before===commit)return freeze({sourceSha,destinationParentSha:parent,destinationCommitSha:commit,destinationTreeSha:tree,remoteHeadSha:commit});if(before!==input.expectedRemoteHead)throw new PromotionError("git-observation-changed","Destination delivery branch changed after payload construction.");
        const publicationRef=`refs/heads/shipyard-publish-${input.deliveryId}-${input.revision}`,refspec=`${publicationRef}:refs/heads/${input.destinationBranch}`;await this.local(directory,["update-ref",publicationRef,commit]);requireSourceFreePublication({refspecs:[refspec],payload:{deliveryId:input.deliveryId,commit,tree}});await this.network(directory,["push","--porcelain","destination",refspec],credential.token);const after=await this.remoteHead(directory,input.destinationBranch,credential.token);if(after!==commit)throw new PromotionError("git-observation-changed","Destination branch publication was not confirmed at the exact commit.");return freeze({sourceSha,destinationParentSha:parent,destinationCommitSha:commit,destinationTreeSha:tree,remoteHeadSha:after});
      };
      return Object.freeze({observation,publish,release:async()=>{if(released)return;released=true;await rm(directory,{recursive:true,force:true});}});
    }catch(error){await rm(directory,{recursive:true,force:true});if(error instanceof PromotionError)throw error;throw new PromotionError("git-observation-changed","Isolated staged Git operation failed.");}
  }
  private async rejectWritableDestinationRemote(repositoryPath:string,destination:{owner:string;name:string}):Promise<void>{const names=(await this.local(repositoryPath,["remote"])).split("\n").filter(Boolean);for(const name of names){const urls=(await this.local(repositoryPath,["remote","get-url","--push","--all",name])).split("\n").filter(Boolean);if(urls.some(url=>sameGitHubRepository(url,destination.owner,destination.name)))throw new PromotionError("authority-changed","Development clone retains a writable destination remote; remove it before promotion.");}}
  private async remoteHead(stage:string,branch:string,token:string):Promise<string|undefined>{const result=await this.network(stage,["ls-remote","--heads","destination",`refs/heads/${branch}`],token),lines=result.split("\n").filter(Boolean);if(lines.length===0)return undefined;if(lines.length!==1)throw new PromotionError("git-observation-changed","Destination branch resolved ambiguously.");const fields=lines[0]!.split(/\s+/);if(fields[1]!==`refs/heads/${branch}`||!fullSha(fields[0]))throw new PromotionError("git-observation-changed","Destination branch returned an invalid object ID.");return fields[0];}
  private async network(stage:string,args:string[],token:string):Promise<string>{const result=await this.runner.run({executable:this.executable,argv:["-C",stage,...args],env:credentialEnvironment(token),timeoutMs:DEFAULT_GIT_COMMAND_TIMEOUT_MS,maxOutputBytes:DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES});if(Buffer.byteLength(result.stdout)+Buffer.byteLength(result.stderr)>DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES||result.exitCode!==0)throw new PromotionError("git-observation-changed","Authenticated destination Git failed safely.");return result.stdout.trim();}
  private async tree(repositoryPath:string,ref:string,format:GitObjectFormat):Promise<readonly GitTreeEntry[]>{const raw=await this.localBytes(repositoryPath,["ls-tree","-r","-z",ref]);if(raw.length===0)return Object.freeze([]);const records=splitZero(raw);if(records.length>MAX_TREE_ENTRIES)throw new PromotionError("unsafe-payload","Git tree exceeds its entry budget.");const entries=records.map(record=>{const tab=record.indexOf(0x09);if(tab<=0||tab===record.length-1)throw new PromotionError("unsafe-payload","Git tree contains an unsupported entry.");const header=record.subarray(0,tab).toString("ascii"),match=/^(100644|100755|120000|160000) (?:blob|commit) ([a-f0-9]+)$/.exec(header),pathBytes=record.subarray(tab+1),path=pathBytes.toString("utf8");if(!match||match[2]!.length!==(format==="sha1"?40:64)||!Buffer.from(path,"utf8").equals(pathBytes))throw new PromotionError("unsafe-payload","Git tree contains a non-UTF-8 or unsupported entry; no lossy path conversion is permitted.");return Object.freeze({mode:match[1] as GitTreeMode,objectId:match[2]!,path});});return Object.freeze(entries.sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0));}
  private async ancestor(repositoryPath:string,left:string,right:string):Promise<boolean>{try{await exec(this.executable,["-C",repositoryPath,"merge-base","--is-ancestor",left,right],{encoding:"utf8",env:sanitizedGitEnvironment(),timeout:DEFAULT_GIT_COMMAND_TIMEOUT_MS,maxBuffer:DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES,killSignal:"SIGKILL"});return true;}catch(error){if((error as {code?:unknown}).code===1)return false;throw new PromotionError("git-observation-changed","Git ancestry could not be verified.");}}
  private async local(repositoryPath:string,args:string[],includeC=true,extraEnv:Readonly<Record<string,string>>={}):Promise<string>{try{return (await exec(this.executable,includeC?["-C",repositoryPath,...args]:args,{encoding:"utf8",env:sanitizedGitEnvironment(extraEnv),timeout:DEFAULT_GIT_COMMAND_TIMEOUT_MS,maxBuffer:DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES,killSignal:"SIGKILL"})).stdout.trim();}catch{throw new PromotionError("git-observation-changed","Local staged Git failed safely.");}}
  private async localBytes(repositoryPath:string,args:string[]):Promise<Buffer>{return new Promise((resolve,reject)=>{execFile(this.executable,["-C",repositoryPath,...args],{encoding:"buffer",env:sanitizedGitEnvironment(),timeout:DEFAULT_GIT_COMMAND_TIMEOUT_MS,maxBuffer:DEFAULT_GIT_COMMAND_MAX_OUTPUT_BYTES,killSignal:"SIGKILL"},(error,stdout)=>{if(error){reject(new PromotionError("git-observation-changed","Local staged Git failed safely."));return;}resolve(Buffer.isBuffer(stdout)?stdout:Buffer.from(stdout));});});}
}
function credentialEnvironment(token:string):Readonly<Record<string,string>>{return {GIT_CONFIG_COUNT:"3",GIT_CONFIG_KEY_0:"credential.helper",GIT_CONFIG_VALUE_0:"",GIT_CONFIG_KEY_1:"http.https://github.com/.extraheader",GIT_CONFIG_VALUE_1:"",GIT_CONFIG_KEY_2:"http.https://github.com/.extraheader",GIT_CONFIG_VALUE_2:`AUTHORIZATION: bearer ${token}`,GIT_TERMINAL_PROMPT:"0"};}
function safeBranch(value:string):boolean{return /^[A-Za-z0-9][A-Za-z0-9._/-]{0,255}$/.test(value)&&!value.includes("//")&&!value.endsWith("/")&&!value.split("/").some(part=>part==="."||part==="..");}
function stableId(value:string):boolean{return /^[a-z0-9][a-z0-9._-]{0,63}$/.test(value)&&!value.includes("..");}
function exactGitHubUrl(value:string,owner:string,name:string):boolean{return value===`https://github.com/${owner}/${name}.git`||value===`https://github.com/${owner}/${name}`;}
function sameGitHubRepository(value:string,owner:string,name:string):boolean{const expected=`${owner}/${name}`.toLowerCase(),scp=/^(?:[^@]+@)?github\.com:(.+)$/i.exec(value);if(scp&&normalizedRepositoryPath(scp[1]!)===expected)return true;try{const url=new URL(value),protocol=url.protocol.toLowerCase(),port=url.port;if(url.hostname.toLowerCase()!=="github.com"||protocol==="ssh:"&&port!==""&&port!=="22"||protocol==="https:"&&port!==""&&port!=="443"||protocol!=="ssh:"&&protocol!=="https:"&&protocol!=="git:")return false;return normalizedRepositoryPath(decodeURIComponent(url.pathname))===expected;}catch{return false;}}
function normalizedRepositoryPath(value:string):string{return value.replace(/^\/+|\/+$/g,"").replace(/\.git$/i,"").toLowerCase();}
function fullSha(value:unknown):value is string{return typeof value==="string"&&(/^[a-f0-9]{40}$/.test(value)||/^[a-f0-9]{64}$/.test(value));}
function sameEntries(left:readonly GitTreeEntry[],right:readonly GitTreeEntry[]):boolean{return left.length===right.length&&left.every((entry,index)=>entry.path===right[index]!.path&&entry.mode===right[index]!.mode&&entry.objectId===right[index]!.objectId);}
function splitZero(value:Buffer):Buffer[]{const records:Buffer[]=[];let start=0;for(let index=0;index<value.length;index++)if(value[index]===0){if(index>start)records.push(value.subarray(start,index));start=index+1;}if(start!==value.length)throw new PromotionError("unsafe-payload","Git tree output was not NUL terminated.");return records;}
function freeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){for(const child of Object.values(value as Record<string,unknown>))freeze(child);Object.freeze(value);}return value;}
