import type { LedgerCommitInspection, LedgerInventoryReader, LedgerStore, ObjectFormatAuthority } from "../ledger/types.js";
import type { PinnedLedgerReader } from "../context/types.js";
import { finalSealPath, sealDelivery, validateFinalLedgerSeal, verifyFinalLedgerSeal } from "../ledger/final-seal.js";
import { FinalizationError } from "./errors.js";
import { finalizationIntentContents, finalizationReceiptContents, validateFinalizationIntent, validateFinalizationReceipt } from "./schema.js";
import type { FinalizationIntent, FinalizationReceipt } from "./types.js";

export interface FinalizationLedgerStore extends LedgerStore,ObjectFormatAuthority,PinnedLedgerReader,LedgerInventoryReader {inspectCommit(ledgerSha:string):Promise<LedgerCommitInspection>;}
export function finalizationIntentPath(deliveryId:string):string{return `deliveries/${deliveryId}/finalization/intent.json`;}
export function finalizationReceiptPath(deliveryId:string):string{return `deliveries/${deliveryId}/finalization/receipt.json`;}
export class FinalizationLedger {
  constructor(readonly store:FinalizationLedgerStore){}
  async read(deliveryId:string):Promise<Readonly<{head:string|undefined;intent?:FinalizationIntent;receipt?:FinalizationReceipt;sealContents?:string}>>{const paths=[finalizationIntentPath(deliveryId),finalizationReceiptPath(deliveryId),finalSealPath(deliveryId)],snapshot=await this.store.snapshot(paths);try{return Object.freeze({head:snapshot.head,...(snapshot.records[paths[0]!]===undefined?{}:{intent:canonicalIntent(snapshot.records[paths[0]!]!)}),...(snapshot.records[paths[1]!]===undefined?{}:{receipt:canonicalReceipt(snapshot.records[paths[1]!]!)}),...(snapshot.records[paths[2]!]===undefined?{}:{sealContents:snapshot.records[paths[2]!]})});}catch{throw new FinalizationError("checkpoint-conflict","Finalization ledger records are malformed or non-canonical.");}}
  async writeIntent(intent:FinalizationIntent):Promise<string>{const path=finalizationIntentPath(intent.deliveryId),contents=finalizationIntentContents(intent),snapshot=await this.store.snapshot([path]);if(snapshot.records[path]!==undefined){if(snapshot.records[path]!==contents)throw new FinalizationError("checkpoint-conflict","A different immutable finalization intent already exists.");return snapshot.head!;}return this.store.transact({expectedHead:snapshot.head,writes:[{path,contents}],message:`Record finalization intent ${intent.deliveryId}`});}
  async writeReceipt(receipt:FinalizationReceipt):Promise<string>{const path=finalizationReceiptPath(receipt.deliveryId),contents=finalizationReceiptContents(receipt),snapshot=await this.store.snapshot([path]);if(snapshot.records[path]!==undefined){if(snapshot.records[path]!==contents)throw new FinalizationError("checkpoint-conflict","A different immutable finalization receipt already exists.");return snapshot.head!;}return this.store.transact({expectedHead:snapshot.head,writes:[{path,contents}],message:`Record finalization receipt ${receipt.deliveryId}`});}
  async seal(deliveryId:string,productSha:string,recordPaths:readonly string[]):Promise<string>{const existing=await this.read(deliveryId);if(!existing.sealContents)return sealDelivery(this.store,{deliveryId,productSha,recordPaths});const seal=validateFinalLedgerSeal(existing.sealContents),records=await this.store.read(seal.preSealLedgerSha,seal.manifest.map(entry=>entry.path)),inspection=await this.store.inspectCommit(existing.head!);verifyFinalLedgerSeal({objectFormat:await this.store.objectFormat(),externalSealCommitSha:existing.head!,observedCommit:inspection,currentProductSha:productSha,sealContents:existing.sealContents,records});return existing.head!;}
  /** Verifies an already-created seal without creating a transaction. */
  async verifyExistingSeal(deliveryId:string,productSha:string):Promise<string|undefined>{const existing=await this.read(deliveryId);if(!existing.sealContents)return undefined;const seal=validateFinalLedgerSeal(existing.sealContents),records=await this.store.read(seal.preSealLedgerSha,seal.manifest.map(entry=>entry.path)),inspection=await this.store.inspectCommit(existing.head!);verifyFinalLedgerSeal({objectFormat:await this.store.objectFormat(),externalSealCommitSha:existing.head!,observedCommit:inspection,currentProductSha:productSha,sealContents:existing.sealContents,records});return existing.head!;}
  async durableRecordPaths(deliveryId:string):Promise<readonly string[]>{const inventory=await this.store.currentInventory(`deliveries/${deliveryId}/`),seal=finalSealPath(deliveryId);return Object.freeze(inventory.entries.map(entry=>entry.path).filter(path=>path!==seal).sort());}
}
function canonicalIntent(bytes:string):FinalizationIntent{const value=validateFinalizationIntent(JSON.parse(bytes));if(finalizationIntentContents(value)!==bytes)throw new Error();return value;}
function canonicalReceipt(bytes:string):FinalizationReceipt{const value=validateFinalizationReceipt(JSON.parse(bytes));if(finalizationReceiptContents(value)!==bytes)throw new Error();return value;}
