import { canonicalJson } from "../evidence/schema.js";
import { stableDeliveryId } from "../delivery/registry.js";
import { FinalizationError } from "./errors.js";
import type { FinalizationIntent, FinalizationReceipt } from "./types.js";

export function finalizationIntentContents(value:FinalizationIntent):string{return canonicalJson(validateFinalizationIntent(value));}
export function finalizationReceiptContents(value:FinalizationReceipt):string{return canonicalJson(validateFinalizationReceipt(value));}
export function validateFinalizationIntent(value:unknown):FinalizationIntent{try{const root=record(value,["schemaVersion","deliveryId","manifestDigest","actorLogin","mergePolicy","finalDevelopmentSha","finalDestinationCommitSha","finalDestinationTreeSha","destinationMergeSha","destinationMainSha","developmentMainBeforeSha","reviewedTag","developmentRecords","createdAt"]);if(root.schemaVersion!==1||!text(root.actorLogin)||!new Set(["merge-commit","squash","rebase"]).has(String(root.mergePolicy))||!date(root.createdAt)||!tag(root.reviewedTag))invalid();const records=record(root.developmentRecords,["issue","pullRequest"]),issue=record(records.issue,["id","number","url","state"]),pull=record(records.pullRequest,["id","number","url","state","merged","headRef","headSha"]);if(!provider(issue)||!provider(pull)||!new Set(["open","closed"]).has(String(issue.state))||!new Set(["open","closed"]).has(String(pull.state))||typeof pull.merged!=="boolean"||!text(pull.headRef))invalid();const finalDevelopmentSha=sha(root.finalDevelopmentSha),objectIds=[finalDevelopmentSha,sha(root.finalDestinationCommitSha),sha(root.finalDestinationTreeSha),sha(root.destinationMergeSha),sha(root.destinationMainSha),sha(root.developmentMainBeforeSha),sha(pull.headSha)];if(objectIds.some(objectId=>objectId.length!==finalDevelopmentSha.length))invalid();return freeze({schemaVersion:1,deliveryId:stableDeliveryId(root.deliveryId),manifestDigest:digest(root.manifestDigest),actorLogin:root.actorLogin as string,mergePolicy:root.mergePolicy as FinalizationIntent["mergePolicy"],finalDevelopmentSha,finalDestinationCommitSha:objectIds[1]!,finalDestinationTreeSha:objectIds[2]!,destinationMergeSha:objectIds[3]!,destinationMainSha:objectIds[4]!,developmentMainBeforeSha:objectIds[5]!,reviewedTag:root.reviewedTag as string,developmentRecords:{issue:{id:issue.id as string,number:issue.number as number,url:issue.url as string,state:issue.state as "open"|"closed"},pullRequest:{id:pull.id as string,number:pull.number as number,url:pull.url as string,state:pull.state as "open"|"closed",merged:pull.merged as boolean,headRef:pull.headRef as string,headSha:objectIds[6]!}},createdAt:root.createdAt as string});}catch(error){if(error instanceof FinalizationError)throw error;invalid();}}
export function validateFinalizationReceipt(value:unknown):FinalizationReceipt{try{const root=record(value,["schemaVersion","deliveryId","manifestDigest","finalDevelopmentSha","destinationMainSha","destinationMergeSha","reviewedTag","developmentPullRequestState","developmentIssueState","developmentBranchDeleted","destinationBranchDeleted","completedAt"]);if(root.schemaVersion!==1||root.developmentPullRequestState!=="closed-unmerged"||root.developmentIssueState!=="closed"||root.developmentBranchDeleted!==true||root.destinationBranchDeleted!==true||!tag(root.reviewedTag)||!date(root.completedAt))invalid();const finalDevelopmentSha=sha(root.finalDevelopmentSha),destinationMainSha=sha(root.destinationMainSha),destinationMergeSha=sha(root.destinationMergeSha);if(destinationMainSha.length!==finalDevelopmentSha.length||destinationMergeSha.length!==finalDevelopmentSha.length)invalid();return freeze({schemaVersion:1,deliveryId:stableDeliveryId(root.deliveryId),manifestDigest:digest(root.manifestDigest),finalDevelopmentSha,destinationMainSha,destinationMergeSha,reviewedTag:root.reviewedTag as string,developmentPullRequestState:"closed-unmerged",developmentIssueState:"closed",developmentBranchDeleted:true,destinationBranchDeleted:true,completedAt:root.completedAt as string});}catch(error){if(error instanceof FinalizationError)throw error;invalid();}}
function record(value:unknown,keys:readonly string[]):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype||Reflect.ownKeys(value).some(key=>typeof key!=="string"||!keys.includes(key))||keys.some(key=>!Object.hasOwn(value,key)))invalid();const out:Record<string,unknown>={};for(const key of keys){const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor||!("value" in descriptor))invalid();out[key]=descriptor.value;}return out;}
function provider(value:Record<string,unknown>):boolean{return text(value.id)&&Number.isSafeInteger(value.number)&&(value.number as number)>0&&typeof value.url==="string"&&value.url.startsWith("https://github.com/");}
function text(value:unknown):value is string{return typeof value==="string"&&value.trim()!==""&&value.length<=4096;}
function sha(value:unknown):string{if(typeof value!=="string"||!(/^[a-f0-9]{40}$/.test(value)||/^[a-f0-9]{64}$/.test(value)))invalid();return value;}
function digest(value:unknown):string{if(typeof value!=="string"||!/^[a-f0-9]{64}$/.test(value))invalid();return value;}
function date(value:unknown):value is string{return typeof value==="string"&&new Date(value).toISOString()===value;}
function tag(value:unknown):value is string{return typeof value==="string"&&/^shipyard\/reviewed\/[a-z0-9][a-z0-9._-]{0,63}$/.test(value);}
function invalid():never{throw new FinalizationError("invalid-state","Finalization state is not a canonical version 1 document.");}
function freeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){for(const child of Object.values(value as Record<string,unknown>))freeze(child);Object.freeze(value);}return value;}
