import type { TrustedAcceptanceGate } from "../acceptance/gate.js";
import type { DeliveryResolver } from "../delivery/resolver.js";
import type { MutationLockService } from "../locking/mutation-lock.js";
import type { BoundProfileAuthority, BoundProfileAuthorityResolver } from "../profile/bound-authority.js";
import { profileFingerprint } from "../profile/fingerprint.js";
import { requireProfileAuthorization, sameTopology, type ProfileReader } from "../profile/policy.js";
import { classifyProfilePath, PathPolicyError } from "../policy/path-classifier.js";
import { PromotionError } from "../promotion/errors.js";
import type { StagedPromotionGit } from "../promotion/git.js";
import { PromotionLedger, promotionManifestDigest } from "../promotion/manifest.js";
import { createPayloadPlan } from "../promotion/payload.js";
import type { StagedProviderAuthority, StagedProviderSession } from "../promotion/provider.js";
import type { PromotionJournal, PromotionManifest, PromotionMapping, PromotionJournalStep } from "../promotion/types.js";
import { FinalizationError } from "./errors.js";
import type { FinalizationGitAuthority, FinalizationGitSession, OwnedWorkspaceCleanup } from "./git.js";
import { FinalizationLedger } from "./ledger.js";
import type { DestinationMergePolicy, FinalizationIntent, FinalizationReceipt, FinalizationStatus } from "./types.js";
import { verifyDestinationMerge } from "./merge-policy.js";

export interface DestinationMergePolicyResolver {resolve(profileName:string):Promise<DestinationMergePolicy>;}
export type TrustedStagedFinalizationDependencies=Readonly<{
  repositoryPath:string;authority:BoundProfileAuthorityResolver;profiles:ProfileReader;deliveries:Pick<DeliveryResolver,"resolve">;
  evidence:TrustedAcceptanceGate;stagedGit:StagedPromotionGit;git:FinalizationGitAuthority;provider:StagedProviderAuthority;
  promotionLedger:PromotionLedger;finalizationLedger:FinalizationLedger;cleanup:OwnedWorkspaceCleanup;
  mergePolicy:DestinationMergePolicyResolver;locks:MutationLockService;lockPath(commonDirectory:string):string;now?:()=>Date;
}>;
export interface TrustedStagedFinalizationOperation {observeAndFinalize(input:Readonly<{deliveryId:string}>):Promise<FinalizationStatus>;}
export function createTrustedStagedFinalizationOperation(raw:TrustedStagedFinalizationDependencies):TrustedStagedFinalizationOperation{const dependencies=construction(raw),service=new StagedFinalizationService(dependencies),operation:TrustedStagedFinalizationOperation={observeAndFinalize:(input:Readonly<{deliveryId:string}>)=>service.run(input)};return Object.freeze(operation);}

class StagedFinalizationService {
  constructor(private readonly dependencies:TrustedStagedFinalizationDependencies){}
  async run(input:Readonly<{deliveryId:string}>):Promise<FinalizationStatus>{const deliveryId=selection(input),pre=await this.dependencies.authority.resolve(this.dependencies.repositoryPath,"finalize"),lock=await this.dependencies.locks.acquire(this.dependencies.lockPath(pre.commonDirectory),pre.commonDirectory,"finalize");try{let promotion=await this.dependencies.promotionLedger.read(deliveryId);if(!promotion.manifest?.pullRequest)throw new FinalizationError("invalid-state","A checkpointed destination PR is required before finalization.");let finalState=await this.dependencies.finalizationLedger.read(deliveryId),scope=await this.scope(deliveryId,pre,promotion.manifest,finalState.intent===undefined),provider=await this.dependencies.provider.open({actorLogin:scope.authority.actorLogin,development:scope.authority.topology.development,destination:scope.authority.topology.destination}),intent=finalState.intent;
    if(!intent){const created=await this.createIntent(scope,promotion.manifest,provider);intent=created.intent;await this.dependencies.finalizationLedger.writeIntent(intent);promotion=await this.dependencies.promotionLedger.read(deliveryId);await this.dependencies.promotionLedger.writeManifest(promotion,{...promotion.manifest!,pullRequest:created.pullRequest,phase:"finalizing"});await this.journal(deliveryId,"final-intent-recorded",`final-intent:${intent.destinationMergeSha}`,intent.destinationMergeSha);}
    this.requireIntent(scope,promotion.manifest!,intent);const pull=await provider.observeDestinationPullRequest({number:promotion.manifest!.pullRequest!.number,marker:promotion.manifest!.pullRequest!.marker});this.requireMergedPull(pull,promotion.manifest!.pullRequest!,intent);const git=await this.dependencies.git.open({repositoryPath:this.dependencies.repositoryPath,actorLogin:scope.authority.actorLogin,development:scope.authority.topology.development,destination:scope.authority.topology.destination,developmentBranch:promotion.manifest!.development.branch,destinationBranch:promotion.manifest!.destination.branch,expectedMergeSha:intent.destinationMergeSha,expectedFinalDevelopmentSha:intent.finalDevelopmentSha,expectedFinalDestinationSha:intent.finalDestinationCommitSha});try{verifyDestinationMerge(intent.mergePolicy,intent,git.observation);await this.verifyResumeAuthority(scope,promotion.manifest!,intent,promotion.journal,git);const developmentRecords=await provider.observeDevelopmentRecords(scope.deliveryId);if(!sameDevelopmentIdentity(developmentRecords,intent.developmentRecords))throw new FinalizationError("unsafe-recovery","Development issue or PR identity changed before finalization mutation.");await this.execute(scope,promotion.manifest!,intent,provider,git);promotion=await this.dependencies.promotionLedger.read(deliveryId);if(promotion.manifest!.phase!=="complete")await this.dependencies.promotionLedger.writeManifest(promotion,{...promotion.manifest!,phase:"complete"});const complete=await this.dependencies.promotionLedger.read(deliveryId),currentFinal=await this.dependencies.finalizationLedger.read(deliveryId),receipt:FinalizationReceipt=currentFinal.receipt??freeze({schemaVersion:1,deliveryId,manifestDigest:promotionManifestDigest(complete.manifest!),finalDevelopmentSha:intent.finalDevelopmentSha,destinationMainSha:intent.destinationMainSha,destinationMergeSha:intent.destinationMergeSha,reviewedTag:intent.reviewedTag,developmentPullRequestState:"closed-unmerged",developmentIssueState:"closed",developmentBranchDeleted:true,destinationBranchDeleted:true,completedAt:this.now()});await this.dependencies.finalizationLedger.writeReceipt(receipt);await this.journal(deliveryId,"final-receipt-recorded",`final-receipt:${receipt.manifestDigest}`,receipt.destinationMainSha);const recordPaths=await this.dependencies.finalizationLedger.durableRecordPaths(deliveryId),seal=await this.dependencies.finalizationLedger.seal(deliveryId,intent.finalDevelopmentSha,recordPaths);await git.publishLedger(seal);return freeze({phase:"complete",deliveryId,destinationMainSha:intent.destinationMainSha,sealSha:seal,blockers:Object.freeze([]),nextSafeAction:"Delivery is finalized; retain the reviewed tag and sealed development ledger."});}finally{await git.release();}
  }finally{await lock.release();}}

  private async createIntent(scope:Scope,manifest:PromotionManifest,provider:StagedProviderSession):Promise<Readonly<{intent:FinalizationIntent;pullRequest:NonNullable<PromotionManifest["pullRequest"]>}>>{const last=manifest.mappings.at(-1)!,receipt=await this.dependencies.evidence.evaluateReceipt();if(!receipt.decision.promotionEligible||receipt.deliveryId!==scope.deliveryId||receipt.actorLogin!==scope.authority.actorLogin||!sameEvidence(last,receipt))throw new FinalizationError("invalid-state","Final exact-SHA acceptance/review receipt is stale.");await this.verifyFinalProjection(scope,manifest,scope.worktreePath!);
    const pull=await provider.observeDestinationPullRequest({number:manifest.pullRequest!.number,marker:manifest.pullRequest!.marker});this.requireMergedPull(pull,manifest.pullRequest!,{finalDestinationCommitSha:last.destinationCommitSha,destinationMergeSha:pull.mergeCommitSha} as FinalizationIntent);const developmentRecords=await provider.observeDevelopmentRecords(scope.deliveryId);if(developmentRecords.pullRequest.merged||developmentRecords.pullRequest.headSha!==last.developmentSha||developmentRecords.pullRequest.headRef!==manifest.development.branch)throw new FinalizationError("invalid-state","Development PR is missing, merged, or no longer names the reviewed final SHA.");const policy=await this.dependencies.mergePolicy.resolve(scope.authority.profileName),git=await this.dependencies.git.open({repositoryPath:this.dependencies.repositoryPath,actorLogin:scope.authority.actorLogin,development:scope.authority.topology.development,destination:scope.authority.topology.destination,developmentBranch:manifest.development.branch,destinationBranch:manifest.destination.branch,expectedMergeSha:pull.mergeCommitSha!,expectedFinalDevelopmentSha:last.developmentSha,expectedFinalDestinationSha:last.destinationCommitSha});try{verifyDestinationMerge(policy,{finalDestinationCommitSha:last.destinationCommitSha,finalDestinationTreeSha:last.destinationTreeSha,destinationMergeSha:pull.mergeCommitSha!,destinationMainSha:git.observation.destinationMainSha},git.observation);if(git.observation.developmentBranchSha!==last.developmentSha)throw new FinalizationError("invalid-state","Development delivery branch no longer names the final reviewed SHA.");const intent=freeze({schemaVersion:1 as const,deliveryId:scope.deliveryId,manifestDigest:promotionManifestDigest(manifest),actorLogin:scope.authority.actorLogin,mergePolicy:policy,finalDevelopmentSha:last.developmentSha,finalDestinationCommitSha:last.destinationCommitSha,finalDestinationTreeSha:last.destinationTreeSha,destinationMergeSha:pull.mergeCommitSha!,destinationMainSha:git.observation.destinationMainSha,developmentMainBeforeSha:git.observation.developmentMainSha,reviewedTag:`shipyard/reviewed/${scope.deliveryId}`,developmentRecords,createdAt:this.now()});return freeze({intent,pullRequest:pull});}finally{await git.release();}}

  private async execute(scope:Scope,manifest:PromotionManifest,intent:FinalizationIntent,provider:StagedProviderSession,git:FinalizationGitSession):Promise<void>{await this.revalidate(scope);const tagObject=await git.ensureReviewedTag(intent.reviewedTag,intent.finalDevelopmentSha,`Reviewed ${scope.deliveryId}; promotion manifest ${intent.manifestDigest}`);await this.journal(scope.deliveryId,"reviewed-tag-published",`reviewed-tag:${intent.reviewedTag}`,tagObject);await this.revalidate(scope);await git.synchronizeDevelopmentMain(intent.developmentMainBeforeSha,intent.destinationMainSha);await this.journal(scope.deliveryId,"development-main-synchronized",`development-main:${intent.destinationMainSha}`,intent.destinationMainSha);const records=await provider.observeDevelopmentRecords(scope.deliveryId);if(!sameDevelopmentIdentity(records,intent.developmentRecords))throw new FinalizationError("unsafe-recovery","Development issue or PR identity changed during finalization.");await provider.closeDevelopmentPullRequest(intent.developmentRecords.pullRequest);await this.journal(scope.deliveryId,"development-pr-closed",`development-pr:${intent.developmentRecords.pullRequest.id}`,undefined,intent.developmentRecords.pullRequest.id);await provider.closeDevelopmentIssue(intent.developmentRecords.issue);await this.journal(scope.deliveryId,"development-issue-closed",`development-issue:${intent.developmentRecords.issue.id}`,undefined,intent.developmentRecords.issue.id);await this.journal(scope.deliveryId,"development-branch-delete-started",`development-branch-delete-started:${intent.finalDevelopmentSha}`,intent.finalDevelopmentSha);await this.revalidate(scope);await git.deleteDevelopmentBranch(manifest.development.branch,intent.finalDevelopmentSha);await this.dependencies.cleanup.removeOwned({repositoryPath:this.dependencies.repositoryPath,deliveryId:scope.deliveryId,expectedBranch:manifest.development.branch,expectedSha:intent.finalDevelopmentSha});await this.journal(scope.deliveryId,"development-branch-deleted",`development-branch:${intent.finalDevelopmentSha}`,intent.finalDevelopmentSha);await this.journal(scope.deliveryId,"destination-branch-delete-started",`destination-branch-delete-started:${intent.finalDestinationCommitSha}`,intent.finalDestinationCommitSha);await this.revalidate(scope);await git.deleteDestinationBranch(manifest.destination.branch,intent.finalDestinationCommitSha);await this.journal(scope.deliveryId,"destination-branch-deleted",`destination-branch:${intent.finalDestinationCommitSha}`,intent.finalDestinationCommitSha);}
  private async verifyResumeAuthority(scope:Scope,manifest:PromotionManifest,intent:FinalizationIntent,journal:PromotionJournal,git:FinalizationGitSession):Promise<void>{const developmentDeleteAuthorized=hasStep(journal,"development-branch-delete-started")||hasStep(journal,"development-branch-deleted"),destinationDeleteAuthorized=hasStep(journal,"destination-branch-delete-started")||hasStep(journal,"destination-branch-deleted"),developmentDeleted=hasStep(journal,"development-branch-deleted"),destinationDeleted=hasStep(journal,"destination-branch-deleted");if(developmentDeleted&&git.observation.developmentBranchSha!==undefined)throw new FinalizationError("unsafe-recovery","Checkpointed deleted development branch was recreated; inspect it before retrying.");if(git.observation.developmentBranchSha===undefined){if(!developmentDeleteAuthorized)throw new FinalizationError("unsafe-recovery","Development branch disappeared without a Shipyard deletion-intent checkpoint.");}else{if(git.observation.developmentBranchSha!==intent.finalDevelopmentSha)throw new FinalizationError("unsafe-recovery","Development branch changed before its checkpointed cleanup.");if(!developmentDeleteAuthorized){const resolved=await this.dependencies.deliveries.resolve({repositoryPath:this.dependencies.repositoryPath,deliveryId:scope.deliveryId});if(resolved.workspace.branch!==manifest.development.branch||resolved.binding.commonDirectory!==scope.authority.commonDirectory)throw new FinalizationError("authority-changed","Delivery workspace no longer matches finalization authority.");const receipt=await this.dependencies.evidence.evaluateReceipt();if(!receipt.decision.promotionEligible||receipt.deliveryId!==scope.deliveryId||receipt.actorLogin!==scope.authority.actorLogin||!sameEvidence(manifest.mappings.at(-1)!,receipt))throw new FinalizationError("invalid-state","Final exact-SHA acceptance/review receipt changed before resume mutation.");await this.verifyFinalProjection(scope,manifest,resolved.workspace.worktreePath);}}if(destinationDeleted&&git.observation.destinationBranchSha!==undefined)throw new FinalizationError("unsafe-recovery","Checkpointed deleted destination branch was recreated; inspect it before retrying.");if(git.observation.destinationBranchSha===undefined){if(!destinationDeleteAuthorized)throw new FinalizationError("unsafe-recovery","Destination branch disappeared without a Shipyard deletion-intent checkpoint.");}else if(git.observation.destinationBranchSha!==intent.finalDestinationCommitSha)throw new FinalizationError("unsafe-recovery","Destination branch changed before its checkpointed cleanup.");}
  private async verifyFinalProjection(scope:Scope,manifest:PromotionManifest,worktreePath:string):Promise<void>{const last=manifest.mappings.at(-1)!,stage=await this.dependencies.stagedGit.stage({repositoryPath:worktreePath,actorLogin:scope.authority.actorLogin,developmentBranch:manifest.development.branch,expectedSourceSha:last.developmentSha,...(manifest.mappings.length>1?{expectedPreviousSourceSha:manifest.mappings.at(-2)!.developmentSha}:{}),expectedDestinationParentSha:last.destinationParentSha,sourceBaselineSha:manifest.destination.baselineSha,destination:scope.authority.topology.destination,destinationBranch:manifest.destination.branch});try{const observation=stage.observation;if(observation.destinationBranchHeadSha!==last.destinationCommitSha||observation.destinationBranchTreeSha!==last.destinationTreeSha||!observation.destinationBranchEntries)throw new FinalizationError("merge-unverified","Final destination branch no longer equals its manifest mapping.");const parentEntries=observation.recordedDestinationParentEntries??observation.destinationMainEntries,plan=createPayloadPlan({sourceSha:last.developmentSha,parentDestinationSha:last.destinationParentSha,sourceEntries:observation.sourceEntries,destinationEntries:parentEntries,classification:{source:this.classify(scope,observation.sourceEntries),destination:this.classify(scope,parentEntries)}});if(plan.policyDigest!==last.policyDigest||plan.projectionDigest!==last.projectionDigest)throw new FinalizationError("invalid-state","Current path policy no longer verifies the final product projection.");}finally{await stage.release();}}
  private requireMergedPull(pull:NonNullable<PromotionManifest["pullRequest"]>,expected:NonNullable<PromotionManifest["pullRequest"]>,intent:Pick<FinalizationIntent,"finalDestinationCommitSha"|"destinationMergeSha">):void{if(pull.state!=="merged"||pull.id!==expected.id||pull.number!==expected.number||pull.marker!==expected.marker||pull.url!==expected.url||pull.repository.owner!==expected.repository.owner||pull.repository.name!==expected.repository.name||pull.headRepository.owner!==expected.headRepository.owner||pull.headRepository.name!==expected.headRepository.name||pull.baseRepository.owner!==expected.baseRepository.owner||pull.baseRepository.name!==expected.baseRepository.name||pull.headRef!==expected.headRef||pull.baseRef!==expected.baseRef||pull.headSha!==intent.finalDestinationCommitSha||!pull.mergeCommitSha||pull.mergeCommitSha!==intent.destinationMergeSha)throw new FinalizationError("merge-unverified","Expected destination PR merge identity or topology is no longer verified.");}
  private async scope(deliveryId:string,expected:BoundProfileAuthority,manifest:PromotionManifest,requireWorkspace:boolean):Promise<Scope>{const authority=await this.dependencies.authority.resolve(this.dependencies.repositoryPath,"finalize"),profile=await this.dependencies.profiles.read(authority.profileName);if(authority.topology.kind!=="staged-pair"||authority.commonDirectory!==expected.commonDirectory||profile.name!==authority.profileName||profile.actor.login!==authority.actorLogin||profileFingerprint(profile)!==authority.profileFingerprint||!sameTopology(profile.topology,authority.topology)||manifest.actorLogin!==authority.actorLogin||!sameTopology({kind:"staged-pair",development:manifest.development.repository,destination:manifest.destination.repository},authority.topology))throw new FinalizationError("authority-changed","Finalization binding, actor, profile, or topology changed.");try{requireProfileAuthorization(profile,"finalize");}catch{throw new FinalizationError("authority-changed","Profile no longer authorizes finalization.");}let worktreePath:string|undefined;if(requireWorkspace){const resolved=await this.dependencies.deliveries.resolve({repositoryPath:this.dependencies.repositoryPath,deliveryId});if(resolved.workspace.branch!==manifest.development.branch||resolved.binding.commonDirectory!==authority.commonDirectory)throw new FinalizationError("authority-changed","Delivery workspace no longer matches the promotion manifest.");worktreePath=resolved.workspace.worktreePath;}return freeze({deliveryId,authority:authority as Scope["authority"],profile,...(worktreePath?{worktreePath}:{})});}
  private async revalidate(scope:Scope):Promise<void>{const current=await this.dependencies.authority.resolve(this.dependencies.repositoryPath,"finalize"),profile=await this.dependencies.profiles.read(current.profileName);if(current.commonDirectory!==scope.authority.commonDirectory||current.profileFingerprint!==scope.authority.profileFingerprint||current.actorLogin!==scope.authority.actorLogin||!sameTopology(current.topology,scope.authority.topology)||profileFingerprint(profile)!==scope.authority.profileFingerprint)throw new FinalizationError("authority-changed","Finalization authority changed before external mutation.");}
  private classify(scope:Scope,entries:readonly {path:string}[]):ReadonlyMap<string,import("../contracts/types.js").PathOwner>{const map=new Map<string,import("../contracts/types.js").PathOwner>();try{for(const entry of entries)map.set(entry.path,classifyProfilePath(scope.profile,entry.path));return map;}catch(error){if(error instanceof PathPolicyError)throw new FinalizationError("invalid-state",error.message);throw error;}}
  private requireIntent(scope:Scope,manifest:PromotionManifest,intent:FinalizationIntent):void{const last=manifest.mappings.at(-1)!;if(intent.deliveryId!==scope.deliveryId||intent.actorLogin!==scope.authority.actorLogin||intent.finalDevelopmentSha!==last.developmentSha||intent.finalDestinationCommitSha!==last.destinationCommitSha||intent.finalDestinationTreeSha!==last.destinationTreeSha||intent.manifestDigest!==promotionManifestDigest({...manifest,pullRequest:{...manifest.pullRequest!,state:"open",mergeCommitSha:undefined},phase:"awaiting-human-merge"}))throw new FinalizationError("checkpoint-conflict","Immutable finalization intent no longer matches its promotion authority.");}
  private async journal(deliveryId:string,step:PromotionJournalStep,key:string,sha?:string,providerId?:string):Promise<void>{const current=await this.dependencies.promotionLedger.read(deliveryId);await this.dependencies.promotionLedger.append(current,{step,idempotencyKey:key,...(sha?{observedSha:sha}:{}),...(providerId?{providerId}:{}),completedAt:this.now()});}
  private now():string{const value=(this.dependencies.now??(()=>new Date()))();if(!(value instanceof Date)||!Number.isFinite(value.getTime()))throw new FinalizationError("invalid-state","Trusted finalization clock is unavailable.");return value.toISOString();}
}

type Scope=Readonly<{deliveryId:string;authority:BoundProfileAuthority&{topology:Extract<BoundProfileAuthority["topology"],{kind:"staged-pair"}>};profile:Awaited<ReturnType<ProfileReader["read"]>>;worktreePath?:string}>;
function sameEvidence(mapping:PromotionMapping,receipt:Awaited<ReturnType<TrustedAcceptanceGate["evaluateReceipt"]>>):boolean{return mapping.developmentSha===receipt.productSha&&mapping.evidence.manifestDigest===receipt.manifestDigest&&mapping.evidence.acceptanceDigest===receipt.acceptanceDigest&&mapping.evidence.reviewId===receipt.reviewId&&mapping.evidence.reviewRequestDigest===receipt.reviewRequestDigest&&mapping.evidence.reviewResultDigest===receipt.reviewResultDigest&&mapping.evidence.reviewedLedgerSha===receipt.reviewedLedgerSha&&mapping.evidence.reviewerBundleDigest===receipt.reviewerBundleDigest;}
function sameDevelopmentIdentity(left:Awaited<ReturnType<StagedProviderSession["observeDevelopmentRecords"]>>,right:FinalizationIntent["developmentRecords"]):boolean{return left.issue.id===right.issue.id&&left.issue.number===right.issue.number&&left.pullRequest.id===right.pullRequest.id&&left.pullRequest.number===right.pullRequest.number&&left.pullRequest.headSha===right.pullRequest.headSha&&left.pullRequest.merged===false;}
function hasStep(journal:PromotionJournal,step:PromotionJournalStep):boolean{return journal.entries.some(entry=>entry.step===step);}
function selection(value:unknown):string{if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).join(",")!=="deliveryId"||typeof (value as {deliveryId?:unknown}).deliveryId!=="string")throw new FinalizationError("invalid-state","Finalization accepts only one stable delivery ID.");const id=(value as {deliveryId:string}).deliveryId;if(!/^[a-z0-9][a-z0-9._-]{0,63}$/.test(id)||id.includes(".."))throw new FinalizationError("invalid-state","Finalization accepts only one stable delivery ID.");return id;}
function construction(value:unknown):TrustedStagedFinalizationDependencies{const keys=["repositoryPath","authority","profiles","deliveries","evidence","stagedGit","git","provider","promotionLedger","finalizationLedger","cleanup","mergePolicy","locks","lockPath","now"],optional=["now"];if(!value||typeof value!=="object"||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)throw new FinalizationError("invalid-state","Trusted finalization dependencies are invalid.");const out:Record<string,unknown>={};for(const key of Reflect.ownKeys(value)){if(typeof key!=="string"||!keys.includes(key))throw new FinalizationError("invalid-state","Trusted finalization dependencies are invalid.");const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor||!("value" in descriptor))throw new FinalizationError("invalid-state","Trusted finalization dependencies are invalid.");out[key]=descriptor.value;}if(keys.some(key=>!optional.includes(key)&&!(key in out))||typeof out.repositoryPath!=="string")throw new FinalizationError("invalid-state","Trusted finalization dependencies are invalid.");return out as TrustedStagedFinalizationDependencies;}
function freeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){for(const child of Object.values(value as Record<string,unknown>))freeze(child);Object.freeze(value);}return value;}
