import { execFile } from "node:child_process";
import { stat } from "node:fs/promises";
import { promisify } from "node:util";
import type { DeliveryReadinessVerifier, DeliveryRegistry } from "../delivery/types.js";
import { validateDeliveryRegistryDocument } from "../delivery/registry.js";
import type { MutationLockService } from "../locking/mutation-lock.js";
import { canonicalGitExecutable, DEFAULT_NODE_GIT_EXECUTABLE, sanitizedGitEnvironment } from "../adapters/git-transport.js";
import { FinalizationError } from "./errors.js";
import type { OwnedWorkspaceCleanup } from "./git.js";

const execute=promisify(execFile);
/** Removes only the exact registry-owned worktree/branch, with dirty-state and ref CAS checks. */
export class RegistryOwnedWorkspaceCleanup implements OwnedWorkspaceCleanup {
  private readonly executable:string;
  constructor(private readonly registry:DeliveryRegistry,private readonly readiness:DeliveryReadinessVerifier,private readonly locks:MutationLockService,executable=DEFAULT_NODE_GIT_EXECUTABLE){this.executable=canonicalGitExecutable(executable);}
  async removeOwned(request:Readonly<{repositoryPath:string;deliveryId:string;expectedBranch:string;expectedSha:string;expectedCreationToken?:string;expectedWorktreePath?:string}>):Promise<void>{const scope=await this.registry.lockScope(),lock=await this.locks.acquire(scope.path,scope.scope,"finalize-workspace-cleanup");try{const document=validateDeliveryRegistryDocument(await this.registry.read());if(!document)throw unsafe();const matches=document.workspaces.filter(item=>item.deliveryId===request.deliveryId);if(matches.length===0)return;if(matches.length!==1)throw unsafe();const workspace=matches[0]!;if(workspace.branch!==request.expectedBranch||!fullSha(request.expectedSha)||(request.expectedCreationToken!==undefined&&workspace.creationToken!==request.expectedCreationToken)||(request.expectedWorktreePath!==undefined&&workspace.worktreePath!==request.expectedWorktreePath))throw unsafe();const branchRef=`refs/heads/${workspace.branch}`,branchSha=await this.optional(request.repositoryPath,["rev-parse","--verify","--quiet",branchRef]),exists=await pathExists(workspace.worktreePath);if(branchSha!==undefined&&branchSha!==request.expectedSha)throw new FinalizationError("unsafe-recovery","Delivery branch changed before owned cleanup.");if(exists){if(!await this.readiness.verifyReadyWorkspace(request.repositoryPath,workspace))throw new FinalizationError("unsafe-recovery","Delivery workspace ownership proof is no longer valid.");if(await this.required(workspace.worktreePath,["status","--porcelain"])!=="")throw new FinalizationError("unsafe-recovery","Delivery worktree has user changes; refusing cleanup.");const registrations=await this.worktrees(request.repositoryPath);if(registrations.filter(item=>item.branch===branchRef).some(item=>item.path!==workspace.worktreePath)||!registrations.some(item=>item.path===workspace.worktreePath&&item.branch===branchRef))throw new FinalizationError("unsafe-recovery","Delivery branch/worktree ownership is ambiguous.");await this.required(request.repositoryPath,["worktree","remove",workspace.worktreePath]);}if(branchSha!==undefined)await this.required(request.repositoryPath,["update-ref","-d",branchRef,request.expectedSha]);if(await this.optional(request.repositoryPath,["rev-parse","--verify","--quiet",branchRef])!==undefined||await pathExists(workspace.worktreePath))throw new FinalizationError("unsafe-recovery","Owned worktree or branch deletion was not confirmed.");await this.registry.write({...document,workspaces:document.workspaces.filter(item=>item.deliveryId!==request.deliveryId)});const after=validateDeliveryRegistryDocument(await this.registry.read());if(!after||after.workspaces.some(item=>item.deliveryId===request.deliveryId))throw new FinalizationError("unsafe-recovery","Delivery registry cleanup was not confirmed.");}finally{await lock.release();}}
  private async worktrees(repo:string):Promise<readonly {path:string;branch?:string}[]>{const lines=(await this.required(repo,["worktree","list","--porcelain"])).split("\n"),out:{path:string;branch?:string}[]=[];let current:{path:string;branch?:string}|undefined;for(const line of lines){if(line.startsWith("worktree ")){if(current)out.push(current);current={path:line.slice(9)};}else if(line.startsWith("branch ")&&current)current.branch=line.slice(7);}if(current)out.push(current);return out;}
  private async optional(repo:string,args:string[]):Promise<string|undefined>{try{return (await execute(this.executable,["-C",repo,...args],{encoding:"utf8",env:sanitizedGitEnvironment(),timeout:30_000,maxBuffer:1_048_576,killSignal:"SIGKILL"})).stdout.trim();}catch(error){const code=(error as {code?:unknown}).code;if(code===1||code===128)return undefined;throw new FinalizationError("unsafe-recovery","Owned workspace Git observation failed safely.");}}
  private async required(repo:string,args:string[]):Promise<string>{try{return (await execute(this.executable,["-C",repo,...args],{encoding:"utf8",env:sanitizedGitEnvironment(),timeout:30_000,maxBuffer:1_048_576,killSignal:"SIGKILL"})).stdout.trim();}catch{throw new FinalizationError("unsafe-recovery","Owned workspace Git mutation failed safely.");}}
}
async function pathExists(path:string):Promise<boolean>{try{await stat(path);return true;}catch{return false;}}
function fullSha(value:string):boolean{return /^[a-f0-9]{40}$/.test(value)||/^[a-f0-9]{64}$/.test(value);}
function unsafe():FinalizationError{return new FinalizationError("unsafe-recovery","Delivery registry ownership proof is unavailable for cleanup.");}
