import type { LedgerStore } from "../ledger/types.js";
import { canonicalJsonWithin } from "../evidence/schema.js";
import { validateAcceptanceEvidence, validateEvidenceManifest, validateFindingResolution, validateReviewRequest, validateReviewResult } from "../evidence/schema.js";
import { MAX_LEDGER_RECORD_BYTES, utf8Bytes } from "../evidence/limits.js";
const delivery=(id:string)=>{if(!/^[A-Za-z0-9][A-Za-z0-9-]*$/.test(id))throw new Error("Delivery ID must be one safe segment.");return id;};
const name=(n:string)=>{if(n==="manifest.json"||n==="acceptance.json"||/^review-request-[A-Za-z0-9-]+\.json$/.test(n)||/^review-result-[A-Za-z0-9-]+\.json$/.test(n)||/^finding-resolution-[A-Za-z0-9-]+\.json$/.test(n))return n;throw new Error("Evidence record name is not canonical.");};
export const evidencePath = (deliveryId:string, recordName:string) => `deliveries/${delivery(deliveryId)}/evidence/${name(recordName)}`;
function validated(recordName:string,document:unknown):unknown {if(recordName==="manifest.json")return validateEvidenceManifest(document);if(recordName==="acceptance.json")return validateAcceptanceEvidence(document);if(recordName.startsWith("review-request-"))return validateReviewRequest(document);if(recordName.startsWith("review-result-"))return validateReviewResult(document);return validateFindingResolution(document);}
export async function persistEvidence(ledger: LedgerStore, deliveryId: string, recordName: string, document: unknown): Promise<string> { const path=evidencePath(deliveryId,recordName);canonicalJsonWithin(document,MAX_LEDGER_RECORD_BYTES);const contents=canonicalJsonWithin(validated(recordName,document),MAX_LEDGER_RECORD_BYTES);if(utf8Bytes(contents)>MAX_LEDGER_RECORD_BYTES)throw new Error("Evidence record exceeds its canonical byte limit.");const snapshot=boundedSnapshot(await ledger.snapshot([path]),path); if(snapshot.records[path]===contents&&snapshot.head)return snapshot.head; const existing=snapshot.records[path],immutable=recordName==="manifest.json"||recordName.startsWith("review-request-")||recordName.startsWith("review-result-")||recordName.startsWith("finding-resolution-");if(existing!==undefined&&immutable)throw new Error("Immutable evidence record already exists with different canonical contents."); return ledger.transact({expectedHead:snapshot.head,writes:[{path,contents,...(existing!==undefined?{expectedContents:existing}:{})}],message:"shipyard evidence"}); }
function boundedSnapshot(raw:unknown,path:string):Readonly<{head:string|undefined;records:Readonly<Record<string,string>>}>{if(!raw||typeof raw!=="object"||Array.isArray(raw)||Object.getPrototypeOf(raw)!==Object.prototype)throw new Error("Ledger snapshot is invalid.");const headDescriptor=Object.getOwnPropertyDescriptor(raw,"head"),recordsDescriptor=Object.getOwnPropertyDescriptor(raw,"records");if(!headDescriptor||!("value" in headDescriptor)||!recordsDescriptor||!("value" in recordsDescriptor)||recordsDescriptor.value===null||typeof recordsDescriptor.value!=="object"||Array.isArray(recordsDescriptor.value)||Object.getPrototypeOf(recordsDescriptor.value)!==Object.prototype)throw new Error("Ledger snapshot is invalid.");const keys=Reflect.ownKeys(recordsDescriptor.value);if(keys.some(key=>key!==path))throw new Error("Ledger snapshot is invalid.");const valueDescriptor=Object.getOwnPropertyDescriptor(recordsDescriptor.value,path);if(valueDescriptor&&(!("value" in valueDescriptor)||typeof valueDescriptor.value!=="string"||utf8Bytes(valueDescriptor.value)>MAX_LEDGER_RECORD_BYTES))throw new Error("Ledger snapshot is invalid.");return {head:headDescriptor.value,records:valueDescriptor?{[path]:valueDescriptor.value}:{}};}
