import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtemp, realpath, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import test from "node:test";
import { createTrustedAcceptanceGate } from "../../../src/acceptance/gate.js";
import { persistEvidence } from "../../../src/acceptance/ledger.js";
import { GitLedgerStore } from "../../../src/adapters/ledger-git.js";
import { createEnvelope } from "../../../src/context/envelope.js";
import { ContextReader } from "../../../src/context/reader.js";
import { canonicalJson } from "../../../src/evidence/schema.js";
import { TrustedReviewDispatcher } from "../../../src/review/dispatch.js";

const exec=promisify(execFile),now="2026-08-04T00:00:00.000Z",topology={kind:"single-repository" as const,repository:{owner:"acme",name:"widget",remote:{name:"origin",url:"https://example.test/widget.git"},defaultBranch:"main"}};
async function git(path:string,args:string[]){return (await exec("/usr/bin/git",["-C",path,...args],{encoding:"utf8"})).stdout.trim();}
async function repo(){const path=await realpath(await mkdtemp(join(tmpdir(),"shipyard-acceptance-")));await git(path,["init","-b","main"]);await git(path,["config","user.name","test"]);await git(path,["config","user.email","test@example.test"]);await git(path,["commit","--allow-empty","-m","product"]);return path;}
async function addContextRecords(ledger:GitLedgerStore,deliveryId:string,head:string){return ledger.transact({expectedHead:head,writes:[{path:`deliveries/${deliveryId}/intent.md`,contents:"canonical intent"},{path:`deliveries/${deliveryId}/review.json`,contents:"review instructions"},{path:"proof/future.txt",contents:"external proof"}],message:"trusted delivery context"});}
function reviewerContext(path:string,deliveryId:string,productSha:string,ledgerSha:string,manifestDigest:string,ledger:GitLedgerStore){const envelopePath=join(path,"reviewer.json"),envelope=createEnvelope({host:"codex",role:"reviewer",envelopePath,repoRoot:path,deliveryId,profile:"local",topology,repository:topology.repository,productBranch:"main",objectFormat:"sha1",productSha,ledgerRef:GitLedgerStore.ref,ledgerSha,evidenceManifestDigest:manifestDigest}),expectation={profile:"local",profileFingerprint:"0".repeat(64),topology,repository:topology.repository,deliveryId,host:"codex",role:"reviewer" as const,envelopePath,repoRoot:path,productBranch:"main",objectFormat:"sha1" as const,productSha,ledgerRef:GitLedgerStore.ref,ledgerSha,evidenceManifestDigest:manifestDigest},products={currentProductSha:async()=>git(path,["rev-parse","HEAD"])},context=new ContextReader(expectation,{resolve:async()=>({profileName:"local",profileFingerprint:"0".repeat(64),commonDirectory:join(path,".git"),actorLogin:"actor",topology})},products,ledger);return {envelope,context,products};}

test("real pinned context, sealed reviewer bundle, ledger evidence, and acceptance gate share the same canonical records",async()=>{const path=await repo();try{const productSha=await git(path,["rev-parse","HEAD"]),deliveryId="future-8421",issueId="JG-8421",ledger=new GitLedgerStore(path),manifest={schemaVersion:1 as const,issueId,items:[{id:"arbitrary-future-item",kind:"acceptance" as const}]},manifestBytes=canonicalJson(manifest),manifestDigest=createHash("sha256").update(manifestBytes).digest("hex"),acceptance={schemaVersion:1 as const,issueId,productSha,items:[{id:"arbitrary-future-item",kind:"acceptance" as const,state:"pass" as const,evidenceRefs:["proof/future.txt"],verifier:"external",verifiedAt:now}]};
  const manifestSha=await persistEvidence(ledger,deliveryId,"manifest.json",manifest);assert.equal((await ledger.read(manifestSha,[`deliveries/${deliveryId}/evidence/manifest.json`]))[`deliveries/${deliveryId}/evidence/manifest.json`],manifestBytes);const acceptanceSha=await persistEvidence(ledger,deliveryId,"acceptance.json",acceptance),contextSha=await addContextRecords(ledger,deliveryId,acceptanceSha),{envelope,context,products}=reviewerContext(path,deliveryId,productSha,contextSha,manifestDigest,ledger),request={schemaVersion:1 as const,issueId,productSha,reviewId:"r-future",reviewerEnvelopePath:envelope.adapter.envelopePath,intentRefs:[`deliveries/${deliveryId}/intent.md`],evidenceRefs:[`deliveries/${deliveryId}/evidence/acceptance.json`],reviewedLedgerSha:contextSha,manifestDigest,acceptanceDigest:createHash("sha256").update(canonicalJson(acceptance)).digest("hex")};
  let calls=0,sealed:any;const dispatcher=new TrustedReviewDispatcher(context,{codex:{review:async(dispatch)=>{calls++;sealed=JSON.parse(dispatch.sealedBundle);const bundleDigest=createHash("sha256").update(dispatch.sealedBundle).digest("hex"),result={schemaVersion:1 as const,reviewId:request.reviewId,productSha,reviewer:"codex",startedAt:now,finishedAt:now,process:{processId:42,sessionId:"fresh-review",fresh:true as const,commandVersion:"codex-test-1",bundleDigest},findings:[],successful:true};return {result,attestation:result.process};}}}),dispatched=await dispatcher.dispatch(envelope,`deliveries/${deliveryId}/evidence/review-request-${request.reviewId}.json`,request);
  assert.equal(calls,1);assert.equal(sealed.records.manifest,manifestBytes);assert.equal(sealed.records.acceptance,canonicalJson(acceptance));assert.equal(JSON.stringify(sealed).includes(envelope.adapter.envelopePath),false);assert.equal(JSON.stringify(sealed).includes(path),false);await persistEvidence(ledger,deliveryId,`review-request-${request.reviewId}.json`,request);await persistEvidence(ledger,deliveryId,`review-result-${request.reviewId}.json`,dispatched.result);
  const inventory=await ledger.currentInventory(`deliveries/${deliveryId}/evidence/`),acceptanceEntry=inventory.entries.find(entry=>entry.path.endsWith("/acceptance.json"));assert.equal(sealed.records.acceptance,acceptanceEntry?.contents);
  const gate=createTrustedAcceptanceGate({context,products,ledger,clock:{now:()=>new Date("2026-08-05T00:00:00.000Z")}});assert.equal((await gate.evaluate()).promotionEligible,true);
}finally{await rm(path,{recursive:true,force:true});}});

test("a pinned reviewer context missing its canonical acceptance record fails before spawn",async()=>{const path=await repo();try{const productSha=await git(path,["rev-parse","HEAD"]),deliveryId="missing",ledger=new GitLedgerStore(path),manifest={schemaVersion:1 as const,issueId:"JG-missing",items:[{id:"x",kind:"acceptance" as const}]},bytes=canonicalJson(manifest),digest=createHash("sha256").update(bytes).digest("hex"),manifestSha=await persistEvidence(ledger,deliveryId,"manifest.json",manifest),{envelope,context}=reviewerContext(path,deliveryId,productSha,manifestSha,digest,ledger),request={schemaVersion:1 as const,issueId:manifest.issueId,productSha,reviewId:"r",reviewerEnvelopePath:envelope.adapter.envelopePath,intentRefs:[`deliveries/${deliveryId}/intent.md`],evidenceRefs:[`deliveries/${deliveryId}/evidence/acceptance.json`],reviewedLedgerSha:manifestSha,manifestDigest:digest,acceptanceDigest:"a".repeat(64)};let calls=0;const dispatcher=new TrustedReviewDispatcher(context,{codex:{review:async()=>{calls++;return {} as never;}}});await assert.rejects(dispatcher.dispatch(envelope,`deliveries/${deliveryId}/evidence/review-request-r.json`,request));assert.equal(calls,0);}finally{await rm(path,{recursive:true,force:true});}});

test("a canonical acceptance record whose issue mismatches the pinned manifest fails before spawn",async()=>{const path=await repo();try{const productSha=await git(path,["rev-parse","HEAD"]),deliveryId="mismatch",ledger=new GitLedgerStore(path),manifest={schemaVersion:1 as const,issueId:"JG-authority",items:[{id:"x",kind:"acceptance" as const}]},bytes=canonicalJson(manifest),digest=createHash("sha256").update(bytes).digest("hex");await persistEvidence(ledger,deliveryId,"manifest.json",manifest);const acceptanceSha=await persistEvidence(ledger,deliveryId,"acceptance.json",{schemaVersion:1,issueId:"JG-other",productSha,items:[{id:"x",kind:"acceptance",state:"pass",evidenceRefs:["proof/future.txt"],verifier:"external",verifiedAt:now}]}),contextSha=await addContextRecords(ledger,deliveryId,acceptanceSha),{envelope,context}=reviewerContext(path,deliveryId,productSha,contextSha,digest,ledger),request={schemaVersion:1 as const,issueId:manifest.issueId,productSha,reviewId:"r",reviewerEnvelopePath:envelope.adapter.envelopePath,intentRefs:[`deliveries/${deliveryId}/intent.md`],evidenceRefs:[`deliveries/${deliveryId}/evidence/acceptance.json`],reviewedLedgerSha:contextSha,manifestDigest:digest,acceptanceDigest:"a".repeat(64)};let calls=0;const dispatcher=new TrustedReviewDispatcher(context,{codex:{review:async()=>{calls++;return {} as never;}}});await assert.rejects(dispatcher.dispatch(envelope,`deliveries/${deliveryId}/evidence/review-request-r.json`,request));assert.equal(calls,0);}finally{await rm(path,{recursive:true,force:true});}});
