import assert from "node:assert/strict";
import test from "node:test";
import { createTrustedFindingResolutionWriter } from "../../src/acceptance/resolution.js";
import { canonicalJson } from "../../src/evidence/schema.js";

const sha="a".repeat(40),head="b".repeat(40),review={schemaVersion:1 as const,reviewId:"r-1",productSha:sha,reviewer:"codex",startedAt:"2026-08-04T00:00:00.000Z",finishedAt:"2026-08-04T00:00:00.000Z",process:{processId:1,sessionId:"s",fresh:true as const,commandVersion:"codex",bundleDigest:"c".repeat(64)},findings:[{id:"f-1",severity:"high" as const,disposition:"accepted" as const,evidenceRefs:["finding.txt"],recordedAt:"2026-08-04T00:00:00.000Z"}],successful:true};

test("resolution writer derives resolver identity, time, product, delivery, and lock scope from authorities",async()=>{let currentHead=head,writes=0,locks=0;const records:Record<string,string>={"deliveries/d/evidence/review-result-r-1.json":canonicalJson(review),"resolution/fix.txt":"proof"},ledger={snapshot:async(paths:readonly string[])=>({head:currentHead,records:Object.fromEntries(paths.filter(path=>records[path]!==undefined).map(path=>[path,records[path]]))}),read:async(_sha:string,paths:readonly string[])=>Object.fromEntries(paths.filter(path=>records[path]!==undefined).map(path=>[path,records[path]])),transact:async(transaction:any)=>{assert.equal(transaction.expectedHead,currentHead);for(const write of transaction.writes)records[write.path]=write.contents;writes++;currentHead="d".repeat(40);return currentHead;},objectFormat:async()=>"sha1" as const},writer=createTrustedFindingResolutionWriter({context:{authorityScope:async()=>({repoRoot:"/repo",deliveryId:"d",commonDirectory:"/repo/.git",actorLogin:"bound-actor"})} as any,products:{currentProductSha:async()=>sha},ledger,mutationLocks:{acquire:async(path:string,scope:string)=>{locks++;assert.equal(path,"/repo/.git/shipyard-review.lock");assert.equal(scope,"/repo/.git");return {record:{},release:async()=>{}};}} as any,filesystem:{realpath:async(path:string)=>path,isDirectory:async()=>true},clock:{now:()=>new Date("2026-08-05T12:00:00.000Z")}}),document=await writer.record({reviewId:"r-1",findingId:"f-1",evidenceRefs:["resolution/fix.txt"]});assert.equal(document.resolver,"bound-actor");assert.equal(document.resolvedAt,"2026-08-05T12:00:00.000Z");assert.equal(document.resolvedProductSha,sha);assert.equal(locks,1);assert.equal(writes,1);assert.equal(JSON.parse(records["deliveries/d/evidence/finding-resolution-f-1.json"]).resolver,"bound-actor");});

test("caller-authored resolver/time and hostile iterable fields are rejected before authority or writes",async()=>{let touched=0;const writer=createTrustedFindingResolutionWriter({context:{authorityScope:async()=>{touched++;return {repoRoot:"/repo",deliveryId:"d",commonDirectory:"/repo/.git",actorLogin:"actor"};}} as any,products:{currentProductSha:async()=>sha},ledger:{} as any,mutationLocks:{} as any,filesystem:{} as any,clock:{now:()=>new Date()}});await assert.rejects((writer.record as any)({reviewId:"r-1",findingId:"f-1",evidenceRefs:["fix.txt"],resolver:"attacker",resolvedAt:"2099-01-01T00:00:00.000Z"}));let iterated=0;const refs:any=[];Object.defineProperty(refs,Symbol.iterator,{value(){iterated++;throw new Error("secret");}});await assert.rejects((writer.record as any)({reviewId:"r-1",findingId:"f-1",evidenceRefs:refs}),error=>!String(error).includes("secret"));assert.equal(touched,0);assert.equal(iterated,0);});
