import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
import { verifyDependencies } from "../../src/dependencies/verification.js";
const manifest = JSON.parse(await readFile(join(process.cwd(), "config", "capabilities.v1.json"), "utf8"));
const matt = manifest.dependencies[0], ccpm = manifest.dependencies[1], codex = manifest.dependencies[2];
const observations = [
  {id:"matt-skills",source:matt.source,content:matt.content,discoveryPaths:matt.canonicalDiscovery,invocation:{command:"skills",frontmatterName:"wayfinder"},skillMetadata:matt.content.skills.map((skill:{name:string;requiredFiles:string[]})=>({name:skill.name,frontmatterName:skill.name,files:skill.requiredFiles})),runtimes:[{kind:"runtime-version",host:"codex",version:"0.144.4"}]},
  {id:"ccpm",source:ccpm.source,content:ccpm.content,discoveryPaths:ccpm.canonicalDiscovery,invocation:{command:"ccpm",frontmatterName:"ccpm"},runtimes:[{kind:"runtime-version",host:"codex",version:"0.144.4"}]},
  {id:"codex",content:codex.content,discoveryPaths:[],invocation:{command:"skills",frontmatterName:"codex"},runtimes:[{kind:"runtime-version",host:"codex",version:"0.144.4"}]}
];
const states=(items:any[]=observations,lane:any="large")=>verifyDependencies(manifest,items,{host:"codex",lane}).findings.map(item=>item.state);
test("ready exact receipts and blocks individual modified dependencies",()=>{assert.deepEqual(states(),["ready","ready","ready"]);const changed=structuredClone(observations);changed[0].content.skills[0].treeSha="0".repeat(40);assert.equal(states(changed)[0],"modified");const ccpmChanged=structuredClone(observations);ccpmChanged[1].content.treeSha="0".repeat(40);assert.equal(states(ccpmChanged)[1],"modified");});
test("missing, duplicate, unverified newer source/runtime are explainable",()=>{assert.equal(states([])[0],"missing");const duplicate=[...observations,structuredClone(observations[0])];assert.equal(states(duplicate)[0],"duplicate");const newer=structuredClone(observations);newer[1].source.commit="1".repeat(40);assert.equal(states(newer)[1],"unverified");const runtime=structuredClone(observations);runtime[2].runtimes[0].version="0.145.0";assert.equal(states(runtime)[2],"unverified");assert.equal(states(observations,"small")[1],"not-required");});
test("missing content, per-skill frontmatter, and hostile collections fail closed",()=>{const missing=structuredClone(observations);delete missing[0].content;assert.equal(states(missing)[0],"missing");const bad=structuredClone(observations);bad[0].skillMetadata[0].frontmatterName="forged";assert.equal(states(bad)[0],"incompatible");const sparse:any[]=[];sparse[1]=observations[0];assert.throws(()=>verifyDependencies(manifest,sparse,{host:"codex",lane:"large"}));assert.throws(()=>verifyDependencies(manifest,new Proxy([], {ownKeys(){throw new Error("trap")}}),{host:"codex",lane:"large"}));assert.throws(()=>verifyDependencies(manifest,observations,new Proxy({}, {get(){throw new Error("trap")}})));});
test("host and lane coercion hooks and hidden array items are never invoked",()=>{const hostile={toString(){throw new Error("coerced");},[Symbol.toPrimitive](){throw new Error("coerced");}};assert.throws(()=>verifyDependencies(manifest,observations,{host:hostile,lane:"large"}));assert.throws(()=>verifyDependencies(manifest,observations,{host:"codex",lane:hostile}));const hidden:any[]=[];Object.defineProperty(hidden,"0",{value:observations[0],enumerable:false});hidden.length=1;assert.throws(()=>verifyDependencies(manifest,hidden,{host:"codex",lane:"large"}));});
