import { canonicalJson, validateAcceptanceEvidence, validateFindingResolution, validateReviewRequest, validateReviewResult } from "./schema.js";
import type { AcceptanceEvidence, EvidenceDecision, EvidenceManifest, FindingResolution, ReviewRequest, ReviewResult } from "./types.js";
type Input=Readonly<{currentProductSha:string;manifest:EvidenceManifest;acceptance?:AcceptanceEvidence;request?:ReviewRequest;result?:ReviewResult;priorResults?:readonly ReviewResult[];resolutions?:readonly FindingResolution[];declaredEvidenceRefs?:readonly string[]}>;
const fullSha=(x:unknown):x is string=>typeof x==="string"&&(/^[a-f0-9]{40}$/.test(x)||/^[a-f0-9]{64}$/.test(x));
export function evaluateFreshness(raw:Input):EvidenceDecision {
  const input=JSON.parse(canonicalJson(raw)) as Input;
  if(!fullSha(input.currentProductSha)||!input.manifest||typeof input.manifest.issueId!=="string"||input.manifest.issueId.trim()===""||!Array.isArray(input.manifest.items))throw new Error("Evidence manifest is invalid.");
  const ids=new Set<string>(); for(const item of input.manifest.items){if(!item||typeof item.id!=="string"||item.id.trim()===""||ids.has(item.id)||!(item.kind==="acceptance"||item.kind==="definition-of-done")||(item.notApplicableEligible!==undefined&&typeof item.notApplicableEligible!=="boolean"))throw new Error("Evidence manifest is invalid.");ids.add(item.id);}
  const a=input.acceptance&&validateAcceptanceEvidence(input.acceptance),q=input.request&&validateReviewRequest(input.request),r=input.result&&validateReviewResult(input.result),prior=(input.priorResults??[]).map(validateReviewResult),resolutions=(input.resolutions??[]).map(validateFindingResolution);
  const documents=[a,q,r,...prior,...resolutions].filter(Boolean) as Array<{productSha?:string;resolvedProductSha?:string}>;if(documents.some(x=>(x.productSha??x.resolvedProductSha)!.length!==input.currentProductSha.length))return decision(false,false,[],["object-format-mismatch"],["evidence-incomplete"],"renew-acceptance-and-review");
  if(new Set(prior.concat(r?[r]:[]).map(x=>x.reviewId)).size!==prior.length+(r?1:0))throw new Error("Duplicate review history is invalid.");
  if(new Set(resolutions.map(x=>`${x.reviewId}:${x.findingId}`)).size!==resolutions.length)throw new Error("Duplicate finding resolutions are invalid.");
  const declared=new Set(input.declaredEvidenceRefs??[]),refs=[...(a?.items.flatMap(i=>i.evidenceRefs)??[]),...(q?.intentRefs??[]),...(q?.evidenceRefs??[]),...(r?.findings.flatMap(f=>f.evidenceRefs)??[]),...prior.flatMap(x=>x.findings.flatMap(f=>f.evidenceRefs)),...resolutions.flatMap(x=>x.evidenceRefs)],missing=input.declaredEvidenceRefs?refs.filter(x=>!declared.has(x)):[];
  const expected=new Map(input.manifest.items.map(x=>[x.id,x])),acceptanceFresh=!!a&&a.issueId===input.manifest.issueId&&a.productSha===input.currentProductSha&&a.items.length===expected.size&&a.items.every(i=>expected.get(i.id)?.kind===i.kind&&(i.state==="pass"||(i.state==="not-applicable"&&expected.get(i.id)?.notApplicableEligible===true&&!!i.justification)));
  const reviewFresh=!!q&&!!r&&q.issueId===input.manifest.issueId&&q.productSha===input.currentProductSha&&r.productSha===input.currentProductSha&&q.reviewId===r.reviewId&&r.successful&&r.process.fresh;
  const accepted=new Map<string,{reviewId:string;finishedAt:string}>();for(const review of prior.concat(r?[r]:[]).sort((x,y)=>Date.parse(x.finishedAt)-Date.parse(y.finishedAt)))for(const f of review.findings)if(f.disposition==="accepted")accepted.set(f.id,{reviewId:review.reviewId,finishedAt:review.finishedAt});
  const blocking=[...accepted].filter(([id,p])=>{const resolution=resolutions.find(x=>x.findingId===id&&x.reviewId===p.reviewId&&x.resolvedProductSha===input.currentProductSha&&Date.parse(x.resolvedAt)>Date.parse(p.finishedAt));return !resolution||!r||Date.parse(r.startedAt)<=Date.parse(resolution.resolvedAt)||!r.findings.some(x=>x.id===id&&x.disposition==="resolved");}).map(([id])=>id).sort();
  const stale=[...(!acceptanceFresh?["acceptance"]:[]),...(!reviewFresh?["review"]:[]),...(missing.length?["evidence-ref-missing"]:[])].sort(),blockers=[...(!acceptanceFresh?["acceptance-stale"]:[]),...(!reviewFresh?["review-stale"]:[]),...(missing.length?["evidence-incomplete"]:[]),...(blocking.length?["accepted-finding"]:[])].sort(),eligible=acceptanceFresh&&reviewFresh&&!missing.length&&!blocking.length;
  return decision(acceptanceFresh,reviewFresh,blocking,stale,blockers,blocking.length?"resolve-finding":eligible?"proceed-to-promotion-gate":"renew-acceptance-and-review");
}
function decision(acceptanceFresh:boolean,reviewFresh:boolean,blocking:string[],stale:string[],blockers:string[],nextAction:EvidenceDecision["nextAction"]):EvidenceDecision{return Object.freeze({acceptanceFresh,reviewFresh,blockingFindingIds:Object.freeze([...new Set(blocking)].sort()),staleRecordIds:Object.freeze([...new Set(stale)].sort()),blockers:Object.freeze([...new Set(blockers)].sort()),nextAction,promotionEligible:acceptanceFresh&&reviewFresh&&!blocking.length&&!blockers.includes("evidence-incomplete")});}
