import { canonicalJson, validateAcceptanceEvidence, validateFindingResolution, validateReviewRequest, validateReviewResult } from "./schema.js";
import type { AcceptanceEvidence, EvidenceDecision, EvidenceManifest, FindingResolution, ReviewRequest, ReviewResult } from "./types.js";
export type EvidenceSequence=Readonly<{reviews:readonly Readonly<{reviewId:string;ordinal:number}>[];resolutions:readonly Readonly<{reviewId:string;findingId:string;ordinal:number}>[]}>;
type Input=Readonly<{currentProductSha:string;manifest:EvidenceManifest;acceptance?:AcceptanceEvidence;request?:ReviewRequest;result?:ReviewResult;priorResults?:readonly ReviewResult[];resolutions?:readonly FindingResolution[];declaredEvidenceRefs?:readonly string[];sequence?:EvidenceSequence}>;
const fullSha=(x:unknown):x is string=>typeof x==="string"&&(/^[a-f0-9]{40}$/.test(x)||/^[a-f0-9]{64}$/.test(x));
export function evaluateFreshness(raw:Input):EvidenceDecision {
  const input=JSON.parse(canonicalJson(raw)) as Input;
  if(!fullSha(input.currentProductSha)||!input.manifest||typeof input.manifest.issueId!=="string"||input.manifest.issueId.trim()===""||!Array.isArray(input.manifest.items)||input.manifest.items.length===0)throw new Error("Evidence manifest is invalid.");
  const ids=new Set<string>(); for(const item of input.manifest.items){if(!item||typeof item.id!=="string"||item.id.trim()===""||ids.has(item.id)||!(item.kind==="acceptance"||item.kind==="definition-of-done")||(item.notApplicableEligible!==undefined&&typeof item.notApplicableEligible!=="boolean"))throw new Error("Evidence manifest is invalid.");ids.add(item.id);}
  const a=input.acceptance&&validateAcceptanceEvidence(input.acceptance),q=input.request&&validateReviewRequest(input.request),r=input.result&&validateReviewResult(input.result),prior=(input.priorResults??[]).map(validateReviewResult),resolutions=(input.resolutions??[]).map(validateFindingResolution);
  const documents=[a,q,r,...prior,...resolutions].filter(Boolean) as Array<{productSha?:string;resolvedProductSha?:string}>;if(documents.some(x=>(x.productSha??x.resolvedProductSha)!.length!==input.currentProductSha.length))return decision(false,false,[],["object-format-mismatch"],["evidence-incomplete"],"renew-acceptance-and-review");
  if(new Set(prior.concat(r?[r]:[]).map(x=>x.reviewId)).size!==prior.length+(r?1:0))throw new Error("Duplicate review history is invalid.");
  if(new Set(resolutions.map(x=>`${x.reviewId}:${x.findingId}`)).size!==resolutions.length)throw new Error("Duplicate finding resolutions are invalid.");
  const reviews=prior.concat(r?[r]:[]),reviewOrdinal=new Map<string,number>(),resolutionOrdinal=new Map<string,number>();
  if(input.sequence){if(!input.sequence||typeof input.sequence!=="object"||Object.keys(input.sequence).sort().join(",")!=="resolutions,reviews"||!Array.isArray(input.sequence.reviews)||!Array.isArray(input.sequence.resolutions))throw new Error("Evidence sequence is invalid.");for(const item of input.sequence.reviews){if(!item||Object.keys(item).sort().join(",")!=="ordinal,reviewId"||typeof item.reviewId!=="string"||!Number.isSafeInteger(item.ordinal)||item.ordinal<=0||reviewOrdinal.has(item.reviewId))throw new Error("Evidence sequence is invalid.");reviewOrdinal.set(item.reviewId,item.ordinal);}for(const item of input.sequence.resolutions){const key=`${item.reviewId}:${item.findingId}`;if(!item||Object.keys(item).sort().join(",")!=="findingId,ordinal,reviewId"||typeof item.reviewId!=="string"||typeof item.findingId!=="string"||!Number.isSafeInteger(item.ordinal)||item.ordinal<=0||resolutionOrdinal.has(key))throw new Error("Evidence sequence is invalid.");resolutionOrdinal.set(key,item.ordinal);}if(reviews.some(review=>!reviewOrdinal.has(review.reviewId))||resolutions.some(resolution=>!resolutionOrdinal.has(`${resolution.reviewId}:${resolution.findingId}`))||reviewOrdinal.size!==reviews.length||resolutionOrdinal.size!==resolutions.length)throw new Error("Evidence sequence is incomplete.");}else{reviews.forEach((review,index)=>reviewOrdinal.set(review.reviewId,index+1));}
  const declared=new Set(input.declaredEvidenceRefs??[]),refs=[...(a?.items.flatMap(i=>i.evidenceRefs)??[]),...(q?.intentRefs??[]),...(q?.evidenceRefs??[]),...(r?.findings.flatMap(f=>f.evidenceRefs)??[]),...prior.flatMap(x=>x.findings.flatMap(f=>f.evidenceRefs)),...resolutions.flatMap(x=>x.evidenceRefs)],missing=input.declaredEvidenceRefs?refs.filter(x=>!declared.has(x)):[];
  const expected=new Map(input.manifest.items.map(x=>[x.id,x])),acceptanceFresh=!!a&&a.issueId===input.manifest.issueId&&a.productSha===input.currentProductSha&&a.items.length===expected.size&&a.items.every(i=>expected.get(i.id)?.kind===i.kind&&(i.state==="pass"||(i.state==="not-applicable"&&expected.get(i.id)?.notApplicableEligible===true&&!!i.justification)));
  const reviewFresh=!!q&&!!r&&q.issueId===input.manifest.issueId&&q.productSha===input.currentProductSha&&r.productSha===input.currentProductSha&&q.reviewId===r.reviewId&&r.successful&&r.process.fresh;
  const orderedReviews=[...reviews].sort((left,right)=>reviewOrdinal.get(left.reviewId)!-reviewOrdinal.get(right.reviewId)!),accepted=new Map<string,{reviewId:string;ordinal:number}>();for(const review of orderedReviews)for(const f of review.findings)if(f.disposition==="accepted")accepted.set(f.id,{reviewId:review.reviewId,ordinal:reviewOrdinal.get(review.reviewId)!});
  const blocking=[...accepted].filter(([id,p])=>{const resolution=resolutions.find(x=>x.findingId===id&&x.reviewId===p.reviewId&&x.resolvedProductSha===input.currentProductSha),resolvedOrdinal=resolution&&(input.sequence?resolutionOrdinal.get(`${resolution.reviewId}:${resolution.findingId}`):p.ordinal+.5),renewed=resolvedOrdinal&&orderedReviews.find(review=>reviewOrdinal.get(review.reviewId)!>resolvedOrdinal&&review.findings.some(f=>f.id===id&&f.disposition==="resolved"));return !resolution||!resolvedOrdinal||resolvedOrdinal<=p.ordinal||!renewed;}).map(([id])=>id).sort();
  const stale=[...(!acceptanceFresh?["acceptance"]:[]),...(!reviewFresh?["review"]:[]),...(missing.length?["evidence-ref-missing"]:[])].sort(),blockers=[...(!acceptanceFresh?["acceptance-stale"]:[]),...(!reviewFresh?["review-stale"]:[]),...(missing.length?["evidence-incomplete"]:[]),...(blocking.length?["accepted-finding"]:[])].sort(),eligible=acceptanceFresh&&reviewFresh&&!missing.length&&!blocking.length;
  return decision(acceptanceFresh,reviewFresh,blocking,stale,blockers,blocking.length?"resolve-finding":eligible?"pin-evidence":"renew-acceptance-and-review");
}
function decision(acceptanceFresh:boolean,reviewFresh:boolean,blocking:string[],stale:string[],blockers:string[],nextAction:EvidenceDecision["nextAction"]):EvidenceDecision{return Object.freeze({acceptanceFresh,reviewFresh,blockingFindingIds:Object.freeze([...new Set(blocking)].sort()),staleRecordIds:Object.freeze([...new Set(stale)].sort()),blockers:Object.freeze([...new Set(blockers)].sort()),nextAction,promotionEligible:false});}
