import { EvidenceError } from "./errors.js";
import { type AcceptanceEvidence, type FindingResolution, type ReviewRequest, type ReviewResult } from "./types.js";

type RecordValue=Record<string,unknown>; const fail=():never=>{throw new EvidenceError("evidence-invalid","Evidence is not a canonical JSON evidence document.");};
const isSha=(v:unknown):v is string=>typeof v==="string"&&(/^[a-f0-9]{40}$/.test(v)||/^[a-f0-9]{64}$/.test(v));
const text=(v:unknown):v is string=>typeof v==="string"&&v.trim()!==""&&!v.includes("\0");
const timestamp=(v:unknown):v is string=>text(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString()===v;
const path=(v:unknown):v is string=>text(v)&&!v.startsWith("/")&&!v.includes("\\")&&!v.split("/").some(x=>x===""||x==="."||x==="..");
function snapshot(value:unknown, seen=new Set<object>()):unknown { try { if(value===null||typeof value==="string"||typeof value==="boolean")return value; if(typeof value==="number"){if(!Number.isFinite(value))fail();return value;} if(typeof value!=="object")fail(); const raw=value as object, container:any=value; if(seen.has(raw))fail();seen.add(raw); if(Array.isArray(container)){const d:any=Object.getOwnPropertyDescriptor(container,"length");if(!d||!("value"in d)||!Number.isSafeInteger(d.value)||d.value<0)fail();const out:unknown[]=[];for(let i=0;i<d.value;i++){const p:any=Object.getOwnPropertyDescriptor(container,String(i));if(!p||!p.enumerable||!("value"in p))fail();out.push(snapshot(p.value,seen));}if(Reflect.ownKeys(container).some(k=>k!=="length"&&(typeof k!=="string"||! /^(0|[1-9][0-9]*)$/.test(k))))fail();seen.delete(raw);return out;} if(Object.getPrototypeOf(container)!==Object.prototype)fail();const out:RecordValue={};for(const key of Reflect.ownKeys(container)){if(typeof key!=="string")fail();const p:any=Object.getOwnPropertyDescriptor(container,key as string);if(!p||!p.enumerable||!("value"in p))fail();out[key as string]=snapshot(p.value,seen);}seen.delete(raw);return out;}catch{fail();} }
function obj(value:unknown,keys:readonly string[]):RecordValue{if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).length!==keys.length||Object.keys(value).some(k=>!keys.includes(k)))fail();return value as RecordValue;}
const arr=(v:unknown):unknown[]=>{if(!Array.isArray(v))fail();return v as unknown[];}; const frozen=<T>(v:T):T=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){for(const child of Object.values(v as Record<string,unknown>))frozen(child);Object.freeze(v);}return v;};
export function canonicalJson(value:unknown):string { return JSON.stringify(sort(snapshot(value))); }
function sort(v:any):any{return Array.isArray(v)?v.map(sort):v&&typeof v==="object"?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v;}
export function validateAcceptanceEvidence(input:unknown):AcceptanceEvidence {const x=obj(snapshot(input),["schemaVersion","issueId","productSha","items"]);if(x.schemaVersion!==1||!text(x.issueId)||!isSha(x.productSha))fail();const items=arr(x.items).map(v=>{const o=obj(v,["id","kind","state","evidenceRefs","verifier","verifiedAt",...((v as any).justification===undefined?[]:["justification"])]);if(!text(o.id)||!(o.kind==="acceptance"||o.kind==="definition-of-done")||!(o.state==="pass"||o.state==="blocked"||o.state==="not-applicable")||!text(o.verifier)||!timestamp(o.verifiedAt)||arr(o.evidenceRefs).length===0||!arr(o.evidenceRefs).every(path)||(o.state==="not-applicable"&&!text(o.justification)))fail();return frozen(o);});if(new Set(items.map(i=>i.id)).size!==items.length)fail();return frozen({schemaVersion:1,issueId:x.issueId as string,productSha:x.productSha as string,items}) as unknown as AcceptanceEvidence;}
export function validateReviewRequest(input:unknown):ReviewRequest {const x=obj(snapshot(input),["schemaVersion","issueId","productSha","reviewId","reviewerEnvelopePath","intentRefs","evidenceRefs"]),intentRefs=arr(x.intentRefs),evidenceRefs=arr(x.evidenceRefs);if(x.schemaVersion!==1||!text(x.issueId)||!isSha(x.productSha)||!text(x.reviewId)||!text(x.reviewerEnvelopePath)||x.reviewerEnvelopePath.toString().includes("\0")||intentRefs.length===0||evidenceRefs.length===0||!intentRefs.every(path)||!evidenceRefs.every(path))fail();return frozen(x) as ReviewRequest;}
export function validateReviewResult(input:unknown):ReviewResult {const x=obj(snapshot(input),["schemaVersion","reviewId","productSha","reviewer","startedAt","finishedAt","process","findings","successful"]),p=obj(x.process,["processId","sessionId","fresh","commandVersion","bundleDigest"]);if(x.schemaVersion!==1||!text(x.reviewId)||!isSha(x.productSha)||!text(x.reviewer)||!timestamp(x.startedAt)||!timestamp(x.finishedAt)||Date.parse(x.finishedAt as string)<Date.parse(x.startedAt as string)||typeof x.successful!=="boolean"||!Number.isSafeInteger(p.processId)||Number(p.processId)<=0||!text(p.sessionId)||!text(p.commandVersion)||typeof p.bundleDigest!=="string"||!/^[a-f0-9]{64}$/.test(p.bundleDigest)||p.fresh!==true)fail();const findings=arr(x.findings).map(v=>{const f=obj(v,["id","severity","disposition","evidenceRefs","recordedAt"]),refs=arr(f.evidenceRefs);if(!text(f.id)||!["critical","high","medium","low"].includes(f.severity as string)||!["accepted","rejected","informational","resolved"].includes(f.disposition as string)||refs.length===0||!refs.every(path)||!timestamp(f.recordedAt)||Date.parse(f.recordedAt as string)<Date.parse(x.startedAt as string)||Date.parse(f.recordedAt as string)>Date.parse(x.finishedAt as string))fail();return frozen(f);});if(new Set(findings.map(f=>f.id)).size!==findings.length)fail();return frozen({...x,process:frozen(p),findings}) as unknown as ReviewResult;}
export function validateFindingResolution(input:unknown):FindingResolution {const x=obj(snapshot(input),["schemaVersion","findingId","reviewId","resolvedProductSha","resolver","resolvedAt","evidenceRefs"]);if(x.schemaVersion!==1||!text(x.findingId)||!text(x.reviewId)||!isSha(x.resolvedProductSha)||!text(x.resolver)||!timestamp(x.resolvedAt)||arr(x.evidenceRefs).length===0||!arr(x.evidenceRefs).every(path))fail();return frozen(x) as FindingResolution;}
